// Code generated by protoc-gen-go.
// source: econ_gcmessages.proto
// DO NOT EDIT!

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package protobuf is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package protobuf to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EGCItemMsg int32

const (
	EGCItemMsg_k_EMsgGCBase                                   EGCItemMsg = 1000
	EGCItemMsg_k_EMsgGCSetSingleItemPosition                  EGCItemMsg = 1001
	EGCItemMsg_k_EMsgGCCraft                                  EGCItemMsg = 1002
	EGCItemMsg_k_EMsgGCCraftResponse                          EGCItemMsg = 1003
	EGCItemMsg_k_EMsgGCDelete                                 EGCItemMsg = 1004
	EGCItemMsg_k_EMsgGCVerifyCacheSubscription                EGCItemMsg = 1005
	EGCItemMsg_k_EMsgGCNameItem                               EGCItemMsg = 1006
	EGCItemMsg_k_EMsgGCUnlockCrate                            EGCItemMsg = 1007
	EGCItemMsg_k_EMsgGCUnlockCrateResponse                    EGCItemMsg = 1008
	EGCItemMsg_k_EMsgGCPaintItem                              EGCItemMsg = 1009
	EGCItemMsg_k_EMsgGCPaintItemResponse                      EGCItemMsg = 1010
	EGCItemMsg_k_EMsgGCGoldenWrenchBroadcast                  EGCItemMsg = 1011
	EGCItemMsg_k_EMsgGCMOTDRequest                            EGCItemMsg = 1012
	EGCItemMsg_k_EMsgGCMOTDRequestResponse                    EGCItemMsg = 1013
	EGCItemMsg_k_EMsgGCNameBaseItem                           EGCItemMsg = 1019
	EGCItemMsg_k_EMsgGCNameBaseItemResponse                   EGCItemMsg = 1020
	EGCItemMsg_k_EMsgGCRemoveSocketItem_DEPRECATED            EGCItemMsg = 1021
	EGCItemMsg_k_EMsgGCRemoveSocketItemResponse_DEPRECATED    EGCItemMsg = 1022
	EGCItemMsg_k_EMsgGCCustomizeItemTexture                   EGCItemMsg = 1023
	EGCItemMsg_k_EMsgGCCustomizeItemTextureResponse           EGCItemMsg = 1024
	EGCItemMsg_k_EMsgGCUseItemRequest                         EGCItemMsg = 1025
	EGCItemMsg_k_EMsgGCUseItemResponse                        EGCItemMsg = 1026
	EGCItemMsg_k_EMsgGCRespawnPostLoadoutChange               EGCItemMsg = 1029
	EGCItemMsg_k_EMsgGCRemoveItemName                         EGCItemMsg = 1030
	EGCItemMsg_k_EMsgGCRemoveItemPaint                        EGCItemMsg = 1031
	EGCItemMsg_k_EMsgGCGiftWrapItem                           EGCItemMsg = 1032
	EGCItemMsg_k_EMsgGCGiftWrapItemResponse                   EGCItemMsg = 1033
	EGCItemMsg_k_EMsgGCDeliverGift                            EGCItemMsg = 1034
	EGCItemMsg_k_EMsgGCDeliverGiftResponseReceiver            EGCItemMsg = 1036
	EGCItemMsg_k_EMsgGCUnwrapGiftRequest                      EGCItemMsg = 1037
	EGCItemMsg_k_EMsgGCUnwrapGiftResponse                     EGCItemMsg = 1038
	EGCItemMsg_k_EMsgGCSetItemStyle                           EGCItemMsg = 1039
	EGCItemMsg_k_EMsgGCUsedClaimCodeItem                      EGCItemMsg = 1040
	EGCItemMsg_k_EMsgGCSortItems                              EGCItemMsg = 1041
	EGCItemMsg_k_EMsgGC_RevolvingLootList_DEPRECATED          EGCItemMsg = 1042
	EGCItemMsg_k_EMsgGCLookupAccount                          EGCItemMsg = 1043
	EGCItemMsg_k_EMsgGCLookupAccountResponse                  EGCItemMsg = 1044
	EGCItemMsg_k_EMsgGCLookupAccountName                      EGCItemMsg = 1045
	EGCItemMsg_k_EMsgGCLookupAccountNameResponse              EGCItemMsg = 1046
	EGCItemMsg_k_EMsgGCUpdateItemSchema                       EGCItemMsg = 1049
	EGCItemMsg_k_EMsgGCRequestInventoryRefresh                EGCItemMsg = 1050
	EGCItemMsg_k_EMsgGCRemoveCustomTexture                    EGCItemMsg = 1051
	EGCItemMsg_k_EMsgGCRemoveCustomTextureResponse            EGCItemMsg = 1052
	EGCItemMsg_k_EMsgGCRemoveMakersMark                       EGCItemMsg = 1053
	EGCItemMsg_k_EMsgGCRemoveMakersMarkResponse               EGCItemMsg = 1054
	EGCItemMsg_k_EMsgGCRemoveUniqueCraftIndex                 EGCItemMsg = 1055
	EGCItemMsg_k_EMsgGCRemoveUniqueCraftIndexResponse         EGCItemMsg = 1056
	EGCItemMsg_k_EMsgGCSaxxyBroadcast                         EGCItemMsg = 1057
	EGCItemMsg_k_EMsgGCBackpackSortFinished                   EGCItemMsg = 1058
	EGCItemMsg_k_EMsgGCAdjustItemEquippedState                EGCItemMsg = 1059
	EGCItemMsg_k_EMsgGCCollectItem                            EGCItemMsg = 1061
	EGCItemMsg_k_EMsgGCItemAcknowledged                       EGCItemMsg = 1062
	EGCItemMsg_k_EMsgGCPresets_SelectPresetForClass           EGCItemMsg = 1063
	EGCItemMsg_k_EMsgGCPresets_SetItemPosition                EGCItemMsg = 1064
	EGCItemMsg_k_EMsgGC_ReportAbuse                           EGCItemMsg = 1065
	EGCItemMsg_k_EMsgGC_ReportAbuseResponse                   EGCItemMsg = 1066
	EGCItemMsg_k_EMsgGCPresets_SelectPresetForClassReply      EGCItemMsg = 1067
	EGCItemMsg_k_EMsgGCNameItemNotification                   EGCItemMsg = 1068
	EGCItemMsg_k_EMsgGCClientDisplayNotification              EGCItemMsg = 1069
	EGCItemMsg_k_EMsgGCApplyStrangePart                       EGCItemMsg = 1070
	EGCItemMsg_k_EMsgGC_IncrementKillCountAttribute           EGCItemMsg = 1071
	EGCItemMsg_k_EMsgGC_IncrementKillCountResponse            EGCItemMsg = 1072
	EGCItemMsg_k_EMsgGCRemoveStrangePart                      EGCItemMsg = 1073
	EGCItemMsg_k_EMsgGCResetStrangeScores                     EGCItemMsg = 1074
	EGCItemMsg_k_EMsgGCGiftedItems                            EGCItemMsg = 1075
	EGCItemMsg_k_EMsgGCApplyUpgradeCard                       EGCItemMsg = 1077
	EGCItemMsg_k_EMsgGCRemoveUpgradeCard                      EGCItemMsg = 1078
	EGCItemMsg_k_EMsgGCApplyStrangeRestriction                EGCItemMsg = 1079
	EGCItemMsg_k_EMsgGCClientRequestMarketData                EGCItemMsg = 1080
	EGCItemMsg_k_EMsgGCClientRequestMarketDataResponse        EGCItemMsg = 1081
	EGCItemMsg_k_EMsgGCApplyXifier                            EGCItemMsg = 1082
	EGCItemMsg_k_EMsgGCApplyXifierResponse                    EGCItemMsg = 1083
	EGCItemMsg_k_EMsgGC_TrackUniquePlayerPairEvent            EGCItemMsg = 1084
	EGCItemMsg_k_EMsgGCFulfillDynamicRecipeComponent          EGCItemMsg = 1085
	EGCItemMsg_k_EMsgGCFulfillDynamicRecipeComponentResponse  EGCItemMsg = 1086
	EGCItemMsg_k_EMsgGCSetItemEffectVerticalOffset            EGCItemMsg = 1087
	EGCItemMsg_k_EMsgGCSetHatEffectUseHeadOrigin              EGCItemMsg = 1088
	EGCItemMsg_k_EMsgGCItemEaterRecharger                     EGCItemMsg = 1089
	EGCItemMsg_k_EMsgGCItemEaterRechargerResponse             EGCItemMsg = 1090
	EGCItemMsg_k_EMsgGCApplyBaseItemXifier                    EGCItemMsg = 1091
	EGCItemMsg_k_EMsgGCApplyClassTransmogrifier               EGCItemMsg = 1092
	EGCItemMsg_k_EMsgGCApplyHalloweenSpellbookPage            EGCItemMsg = 1093
	EGCItemMsg_k_EMsgGCRemoveKillStreak                       EGCItemMsg = 1094
	EGCItemMsg_k_EMsgGCRemoveKillStreakResponse               EGCItemMsg = 1095
	EGCItemMsg_k_EMsgGCTFSpecificItemBroadcast                EGCItemMsg = 1096
	EGCItemMsg_k_EMsgGC_IncrementKillCountAttribute_Multiple  EGCItemMsg = 1097
	EGCItemMsg_k_EMsgGCDeliverGiftResponseGiver               EGCItemMsg = 1098
	EGCItemMsg_k_EMsgGCSetItemPositions                       EGCItemMsg = 1100
	EGCItemMsg_k_EMsgGCLookupMultipleAccountNames             EGCItemMsg = 1101
	EGCItemMsg_k_EMsgGCLookupMultipleAccountNamesResponse     EGCItemMsg = 1102
	EGCItemMsg_k_EMsgGCTradingBase                            EGCItemMsg = 1500
	EGCItemMsg_k_EMsgGCTrading_InitiateTradeRequest           EGCItemMsg = 1501
	EGCItemMsg_k_EMsgGCTrading_InitiateTradeResponse          EGCItemMsg = 1502
	EGCItemMsg_k_EMsgGCTrading_StartSession                   EGCItemMsg = 1503
	EGCItemMsg_k_EMsgGCTrading_SessionClosed                  EGCItemMsg = 1509
	EGCItemMsg_k_EMsgGCTrading_CancelSession                  EGCItemMsg = 1510
	EGCItemMsg_k_EMsgGCTrading_InitiateTradeRequestResponse   EGCItemMsg = 1514
	EGCItemMsg_k_EMsgGCServerBrowser_FavoriteServer           EGCItemMsg = 1601
	EGCItemMsg_k_EMsgGCServerBrowser_BlacklistServer          EGCItemMsg = 1602
	EGCItemMsg_k_EMsgGCServerRentalsBase                      EGCItemMsg = 1700
	EGCItemMsg_k_EMsgGCItemPreviewCheckStatus                 EGCItemMsg = 1701
	EGCItemMsg_k_EMsgGCItemPreviewStatusResponse              EGCItemMsg = 1702
	EGCItemMsg_k_EMsgGCItemPreviewRequest                     EGCItemMsg = 1703
	EGCItemMsg_k_EMsgGCItemPreviewRequestResponse             EGCItemMsg = 1704
	EGCItemMsg_k_EMsgGCItemPreviewExpire                      EGCItemMsg = 1705
	EGCItemMsg_k_EMsgGCItemPreviewExpireNotification          EGCItemMsg = 1706
	EGCItemMsg_k_EMsgGCItemPreviewItemBoughtNotification      EGCItemMsg = 1708
	EGCItemMsg_k_EMsgGCDev_NewItemRequest                     EGCItemMsg = 2001
	EGCItemMsg_k_EMsgGCDev_NewItemRequestResponse             EGCItemMsg = 2002
	EGCItemMsg_k_EMsgGCDev_DebugRollLootRequest               EGCItemMsg = 2003
	EGCItemMsg_k_EMsgGCStoreGetUserData                       EGCItemMsg = 2500
	EGCItemMsg_k_EMsgGCStoreGetUserDataResponse               EGCItemMsg = 2501
	EGCItemMsg_k_EMsgGCStorePurchaseInit_DEPRECATED           EGCItemMsg = 2502
	EGCItemMsg_k_EMsgGCStorePurchaseInitResponse_DEPRECATED   EGCItemMsg = 2503
	EGCItemMsg_k_EMsgGCStorePurchaseFinalize                  EGCItemMsg = 2512
	EGCItemMsg_k_EMsgGCStorePurchaseFinalizeResponse          EGCItemMsg = 2513
	EGCItemMsg_k_EMsgGCStorePurchaseCancel                    EGCItemMsg = 2514
	EGCItemMsg_k_EMsgGCStorePurchaseCancelResponse            EGCItemMsg = 2515
	EGCItemMsg_k_EMsgGCStorePurchaseQueryTxn                  EGCItemMsg = 2508
	EGCItemMsg_k_EMsgGCStorePurchaseQueryTxnResponse          EGCItemMsg = 2509
	EGCItemMsg_k_EMsgGCStorePurchaseInit                      EGCItemMsg = 2510
	EGCItemMsg_k_EMsgGCStorePurchaseInitResponse              EGCItemMsg = 2511
	EGCItemMsg_k_EMsgGCToGCDirtySDOCache                      EGCItemMsg = 2516
	EGCItemMsg_k_EMsgGCToGCDirtyMultipleSDOCache              EGCItemMsg = 2517
	EGCItemMsg_k_EMsgGCToGCUpdateSQLKeyValue                  EGCItemMsg = 2518
	EGCItemMsg_k_EMsgGCToGCBroadcastConsoleCommand            EGCItemMsg = 2521
	EGCItemMsg_k_EMsgGCServerVersionUpdated                   EGCItemMsg = 2522
	EGCItemMsg_k_EMsgGCApplyAutograph                         EGCItemMsg = 2523
	EGCItemMsg_k_EMsgGCToGCWebAPIAccountChanged               EGCItemMsg = 2524
	EGCItemMsg_k_EMsgGCRequestAnnouncements                   EGCItemMsg = 2525
	EGCItemMsg_k_EMsgGCRequestAnnouncementsResponse           EGCItemMsg = 2526
	EGCItemMsg_k_EMsgGCRequestPassportItemGrant               EGCItemMsg = 2527
	EGCItemMsg_k_EMsgGCClientVersionUpdated                   EGCItemMsg = 2528
	EGCItemMsg_k_EMsgGCItemPurgatory_FinalizePurchase         EGCItemMsg = 2531
	EGCItemMsg_k_EMsgGCItemPurgatory_FinalizePurchaseResponse EGCItemMsg = 2532
	EGCItemMsg_k_EMsgGCItemPurgatory_RefundPurchase           EGCItemMsg = 2533
	EGCItemMsg_k_EMsgGCItemPurgatory_RefundPurchaseResponse   EGCItemMsg = 2534
	EGCItemMsg_k_EMsgGCToGCPlayerStrangeCountAdjustments      EGCItemMsg = 2535
	EGCItemMsg_k_EMsgGCRequestStoreSalesData                  EGCItemMsg = 2536
	EGCItemMsg_k_EMsgGCRequestStoreSalesDataResponse          EGCItemMsg = 2537
	EGCItemMsg_k_EMsgGCRequestStoreSalesDataUpToDateResponse  EGCItemMsg = 2538
	EGCItemMsg_k_EMsgGCToGCPingRequest                        EGCItemMsg = 2539
	EGCItemMsg_k_EMsgGCToGCPingResponse                       EGCItemMsg = 2540
	EGCItemMsg_k_EMsgGCToGCGetUserSessionServer               EGCItemMsg = 2541
	EGCItemMsg_k_EMsgGCToGCGetUserSessionServerResponse       EGCItemMsg = 2542
	EGCItemMsg_k_EMsgGCToGCGetUserServerMembers               EGCItemMsg = 2543
	EGCItemMsg_k_EMsgGCToGCGetUserServerMembersResponse       EGCItemMsg = 2544
	EGCItemMsg_k_EMsgGCToGCGrantSelfMadeItemToAccount         EGCItemMsg = 2555
	EGCItemMsg_k_EMsgGCToGCThankedByNewUser                   EGCItemMsg = 2556
	EGCItemMsg_k_EMsgGCShuffleCrateContents                   EGCItemMsg = 2557
	EGCItemMsg_k_EMsgGCQuestObjective_Progress                EGCItemMsg = 2558
	EGCItemMsg_k_EMsgGCQuestCompleted                         EGCItemMsg = 2559
	EGCItemMsg_k_EMsgGCApplyDuckToken                         EGCItemMsg = 2560
	EGCItemMsg_k_EMsgGCQuestComplete_Request                  EGCItemMsg = 2561
	EGCItemMsg_k_EMsgGCQuestObjective_PointsChange            EGCItemMsg = 2562
	EGCItemMsg_k_EMsgGCQuestObjective_PointsChangeResponse    EGCItemMsg = 2563
	EGCItemMsg_k_EMsgGCQuestObjective_RequestLoanerItems      EGCItemMsg = 2564
	EGCItemMsg_k_EMsgGCQuestObjective_RequestLoanerResponse   EGCItemMsg = 2565
	EGCItemMsg_k_EMsgGCApplyStrangeCountTransfer              EGCItemMsg = 2566
	EGCItemMsg_k_EMsgGCCraftCollectionUpgrade                 EGCItemMsg = 2567
	EGCItemMsg_k_EMsgGCCraftHalloweenOffering                 EGCItemMsg = 2568
	EGCItemMsg_k_EMsgGCQuestDiscard_Request                   EGCItemMsg = 2569
	EGCItemMsg_k_EMsgGCRemoveGiftedBy                         EGCItemMsg = 2570
	EGCItemMsg_k_EMsgGCRemoveGiftedByResponse                 EGCItemMsg = 2571
)

var EGCItemMsg_name = map[int32]string{
	1000: "k_EMsgGCBase",
	1001: "k_EMsgGCSetSingleItemPosition",
	1002: "k_EMsgGCCraft",
	1003: "k_EMsgGCCraftResponse",
	1004: "k_EMsgGCDelete",
	1005: "k_EMsgGCVerifyCacheSubscription",
	1006: "k_EMsgGCNameItem",
	1007: "k_EMsgGCUnlockCrate",
	1008: "k_EMsgGCUnlockCrateResponse",
	1009: "k_EMsgGCPaintItem",
	1010: "k_EMsgGCPaintItemResponse",
	1011: "k_EMsgGCGoldenWrenchBroadcast",
	1012: "k_EMsgGCMOTDRequest",
	1013: "k_EMsgGCMOTDRequestResponse",
	1019: "k_EMsgGCNameBaseItem",
	1020: "k_EMsgGCNameBaseItemResponse",
	1021: "k_EMsgGCRemoveSocketItem_DEPRECATED",
	1022: "k_EMsgGCRemoveSocketItemResponse_DEPRECATED",
	1023: "k_EMsgGCCustomizeItemTexture",
	1024: "k_EMsgGCCustomizeItemTextureResponse",
	1025: "k_EMsgGCUseItemRequest",
	1026: "k_EMsgGCUseItemResponse",
	1029: "k_EMsgGCRespawnPostLoadoutChange",
	1030: "k_EMsgGCRemoveItemName",
	1031: "k_EMsgGCRemoveItemPaint",
	1032: "k_EMsgGCGiftWrapItem",
	1033: "k_EMsgGCGiftWrapItemResponse",
	1034: "k_EMsgGCDeliverGift",
	1036: "k_EMsgGCDeliverGiftResponseReceiver",
	1037: "k_EMsgGCUnwrapGiftRequest",
	1038: "k_EMsgGCUnwrapGiftResponse",
	1039: "k_EMsgGCSetItemStyle",
	1040: "k_EMsgGCUsedClaimCodeItem",
	1041: "k_EMsgGCSortItems",
	1042: "k_EMsgGC_RevolvingLootList_DEPRECATED",
	1043: "k_EMsgGCLookupAccount",
	1044: "k_EMsgGCLookupAccountResponse",
	1045: "k_EMsgGCLookupAccountName",
	1046: "k_EMsgGCLookupAccountNameResponse",
	1049: "k_EMsgGCUpdateItemSchema",
	1050: "k_EMsgGCRequestInventoryRefresh",
	1051: "k_EMsgGCRemoveCustomTexture",
	1052: "k_EMsgGCRemoveCustomTextureResponse",
	1053: "k_EMsgGCRemoveMakersMark",
	1054: "k_EMsgGCRemoveMakersMarkResponse",
	1055: "k_EMsgGCRemoveUniqueCraftIndex",
	1056: "k_EMsgGCRemoveUniqueCraftIndexResponse",
	1057: "k_EMsgGCSaxxyBroadcast",
	1058: "k_EMsgGCBackpackSortFinished",
	1059: "k_EMsgGCAdjustItemEquippedState",
	1061: "k_EMsgGCCollectItem",
	1062: "k_EMsgGCItemAcknowledged",
	1063: "k_EMsgGCPresets_SelectPresetForClass",
	1064: "k_EMsgGCPresets_SetItemPosition",
	1065: "k_EMsgGC_ReportAbuse",
	1066: "k_EMsgGC_ReportAbuseResponse",
	1067: "k_EMsgGCPresets_SelectPresetForClassReply",
	1068: "k_EMsgGCNameItemNotification",
	1069: "k_EMsgGCClientDisplayNotification",
	1070: "k_EMsgGCApplyStrangePart",
	1071: "k_EMsgGC_IncrementKillCountAttribute",
	1072: "k_EMsgGC_IncrementKillCountResponse",
	1073: "k_EMsgGCRemoveStrangePart",
	1074: "k_EMsgGCResetStrangeScores",
	1075: "k_EMsgGCGiftedItems",
	1077: "k_EMsgGCApplyUpgradeCard",
	1078: "k_EMsgGCRemoveUpgradeCard",
	1079: "k_EMsgGCApplyStrangeRestriction",
	1080: "k_EMsgGCClientRequestMarketData",
	1081: "k_EMsgGCClientRequestMarketDataResponse",
	1082: "k_EMsgGCApplyXifier",
	1083: "k_EMsgGCApplyXifierResponse",
	1084: "k_EMsgGC_TrackUniquePlayerPairEvent",
	1085: "k_EMsgGCFulfillDynamicRecipeComponent",
	1086: "k_EMsgGCFulfillDynamicRecipeComponentResponse",
	1087: "k_EMsgGCSetItemEffectVerticalOffset",
	1088: "k_EMsgGCSetHatEffectUseHeadOrigin",
	1089: "k_EMsgGCItemEaterRecharger",
	1090: "k_EMsgGCItemEaterRechargerResponse",
	1091: "k_EMsgGCApplyBaseItemXifier",
	1092: "k_EMsgGCApplyClassTransmogrifier",
	1093: "k_EMsgGCApplyHalloweenSpellbookPage",
	1094: "k_EMsgGCRemoveKillStreak",
	1095: "k_EMsgGCRemoveKillStreakResponse",
	1096: "k_EMsgGCTFSpecificItemBroadcast",
	1097: "k_EMsgGC_IncrementKillCountAttribute_Multiple",
	1098: "k_EMsgGCDeliverGiftResponseGiver",
	1100: "k_EMsgGCSetItemPositions",
	1101: "k_EMsgGCLookupMultipleAccountNames",
	1102: "k_EMsgGCLookupMultipleAccountNamesResponse",
	1500: "k_EMsgGCTradingBase",
	1501: "k_EMsgGCTrading_InitiateTradeRequest",
	1502: "k_EMsgGCTrading_InitiateTradeResponse",
	1503: "k_EMsgGCTrading_StartSession",
	1509: "k_EMsgGCTrading_SessionClosed",
	1510: "k_EMsgGCTrading_CancelSession",
	1514: "k_EMsgGCTrading_InitiateTradeRequestResponse",
	1601: "k_EMsgGCServerBrowser_FavoriteServer",
	1602: "k_EMsgGCServerBrowser_BlacklistServer",
	1700: "k_EMsgGCServerRentalsBase",
	1701: "k_EMsgGCItemPreviewCheckStatus",
	1702: "k_EMsgGCItemPreviewStatusResponse",
	1703: "k_EMsgGCItemPreviewRequest",
	1704: "k_EMsgGCItemPreviewRequestResponse",
	1705: "k_EMsgGCItemPreviewExpire",
	1706: "k_EMsgGCItemPreviewExpireNotification",
	1708: "k_EMsgGCItemPreviewItemBoughtNotification",
	2001: "k_EMsgGCDev_NewItemRequest",
	2002: "k_EMsgGCDev_NewItemRequestResponse",
	2003: "k_EMsgGCDev_DebugRollLootRequest",
	2500: "k_EMsgGCStoreGetUserData",
	2501: "k_EMsgGCStoreGetUserDataResponse",
	2502: "k_EMsgGCStorePurchaseInit_DEPRECATED",
	2503: "k_EMsgGCStorePurchaseInitResponse_DEPRECATED",
	2512: "k_EMsgGCStorePurchaseFinalize",
	2513: "k_EMsgGCStorePurchaseFinalizeResponse",
	2514: "k_EMsgGCStorePurchaseCancel",
	2515: "k_EMsgGCStorePurchaseCancelResponse",
	2508: "k_EMsgGCStorePurchaseQueryTxn",
	2509: "k_EMsgGCStorePurchaseQueryTxnResponse",
	2510: "k_EMsgGCStorePurchaseInit",
	2511: "k_EMsgGCStorePurchaseInitResponse",
	2516: "k_EMsgGCToGCDirtySDOCache",
	2517: "k_EMsgGCToGCDirtyMultipleSDOCache",
	2518: "k_EMsgGCToGCUpdateSQLKeyValue",
	2521: "k_EMsgGCToGCBroadcastConsoleCommand",
	2522: "k_EMsgGCServerVersionUpdated",
	2523: "k_EMsgGCApplyAutograph",
	2524: "k_EMsgGCToGCWebAPIAccountChanged",
	2525: "k_EMsgGCRequestAnnouncements",
	2526: "k_EMsgGCRequestAnnouncementsResponse",
	2527: "k_EMsgGCRequestPassportItemGrant",
	2528: "k_EMsgGCClientVersionUpdated",
	2531: "k_EMsgGCItemPurgatory_FinalizePurchase",
	2532: "k_EMsgGCItemPurgatory_FinalizePurchaseResponse",
	2533: "k_EMsgGCItemPurgatory_RefundPurchase",
	2534: "k_EMsgGCItemPurgatory_RefundPurchaseResponse",
	2535: "k_EMsgGCToGCPlayerStrangeCountAdjustments",
	2536: "k_EMsgGCRequestStoreSalesData",
	2537: "k_EMsgGCRequestStoreSalesDataResponse",
	2538: "k_EMsgGCRequestStoreSalesDataUpToDateResponse",
	2539: "k_EMsgGCToGCPingRequest",
	2540: "k_EMsgGCToGCPingResponse",
	2541: "k_EMsgGCToGCGetUserSessionServer",
	2542: "k_EMsgGCToGCGetUserSessionServerResponse",
	2543: "k_EMsgGCToGCGetUserServerMembers",
	2544: "k_EMsgGCToGCGetUserServerMembersResponse",
	2555: "k_EMsgGCToGCGrantSelfMadeItemToAccount",
	2556: "k_EMsgGCToGCThankedByNewUser",
	2557: "k_EMsgGCShuffleCrateContents",
	2558: "k_EMsgGCQuestObjective_Progress",
	2559: "k_EMsgGCQuestCompleted",
	2560: "k_EMsgGCApplyDuckToken",
	2561: "k_EMsgGCQuestComplete_Request",
	2562: "k_EMsgGCQuestObjective_PointsChange",
	2563: "k_EMsgGCQuestObjective_PointsChangeResponse",
	2564: "k_EMsgGCQuestObjective_RequestLoanerItems",
	2565: "k_EMsgGCQuestObjective_RequestLoanerResponse",
	2566: "k_EMsgGCApplyStrangeCountTransfer",
	2567: "k_EMsgGCCraftCollectionUpgrade",
	2568: "k_EMsgGCCraftHalloweenOffering",
	2569: "k_EMsgGCQuestDiscard_Request",
	2570: "k_EMsgGCRemoveGiftedBy",
	2571: "k_EMsgGCRemoveGiftedByResponse",
}
var EGCItemMsg_value = map[string]int32{
	"k_EMsgGCBase":                                   1000,
	"k_EMsgGCSetSingleItemPosition":                  1001,
	"k_EMsgGCCraft":                                  1002,
	"k_EMsgGCCraftResponse":                          1003,
	"k_EMsgGCDelete":                                 1004,
	"k_EMsgGCVerifyCacheSubscription":                1005,
	"k_EMsgGCNameItem":                               1006,
	"k_EMsgGCUnlockCrate":                            1007,
	"k_EMsgGCUnlockCrateResponse":                    1008,
	"k_EMsgGCPaintItem":                              1009,
	"k_EMsgGCPaintItemResponse":                      1010,
	"k_EMsgGCGoldenWrenchBroadcast":                  1011,
	"k_EMsgGCMOTDRequest":                            1012,
	"k_EMsgGCMOTDRequestResponse":                    1013,
	"k_EMsgGCNameBaseItem":                           1019,
	"k_EMsgGCNameBaseItemResponse":                   1020,
	"k_EMsgGCRemoveSocketItem_DEPRECATED":            1021,
	"k_EMsgGCRemoveSocketItemResponse_DEPRECATED":    1022,
	"k_EMsgGCCustomizeItemTexture":                   1023,
	"k_EMsgGCCustomizeItemTextureResponse":           1024,
	"k_EMsgGCUseItemRequest":                         1025,
	"k_EMsgGCUseItemResponse":                        1026,
	"k_EMsgGCRespawnPostLoadoutChange":               1029,
	"k_EMsgGCRemoveItemName":                         1030,
	"k_EMsgGCRemoveItemPaint":                        1031,
	"k_EMsgGCGiftWrapItem":                           1032,
	"k_EMsgGCGiftWrapItemResponse":                   1033,
	"k_EMsgGCDeliverGift":                            1034,
	"k_EMsgGCDeliverGiftResponseReceiver":            1036,
	"k_EMsgGCUnwrapGiftRequest":                      1037,
	"k_EMsgGCUnwrapGiftResponse":                     1038,
	"k_EMsgGCSetItemStyle":                           1039,
	"k_EMsgGCUsedClaimCodeItem":                      1040,
	"k_EMsgGCSortItems":                              1041,
	"k_EMsgGC_RevolvingLootList_DEPRECATED":          1042,
	"k_EMsgGCLookupAccount":                          1043,
	"k_EMsgGCLookupAccountResponse":                  1044,
	"k_EMsgGCLookupAccountName":                      1045,
	"k_EMsgGCLookupAccountNameResponse":              1046,
	"k_EMsgGCUpdateItemSchema":                       1049,
	"k_EMsgGCRequestInventoryRefresh":                1050,
	"k_EMsgGCRemoveCustomTexture":                    1051,
	"k_EMsgGCRemoveCustomTextureResponse":            1052,
	"k_EMsgGCRemoveMakersMark":                       1053,
	"k_EMsgGCRemoveMakersMarkResponse":               1054,
	"k_EMsgGCRemoveUniqueCraftIndex":                 1055,
	"k_EMsgGCRemoveUniqueCraftIndexResponse":         1056,
	"k_EMsgGCSaxxyBroadcast":                         1057,
	"k_EMsgGCBackpackSortFinished":                   1058,
	"k_EMsgGCAdjustItemEquippedState":                1059,
	"k_EMsgGCCollectItem":                            1061,
	"k_EMsgGCItemAcknowledged":                       1062,
	"k_EMsgGCPresets_SelectPresetForClass":           1063,
	"k_EMsgGCPresets_SetItemPosition":                1064,
	"k_EMsgGC_ReportAbuse":                           1065,
	"k_EMsgGC_ReportAbuseResponse":                   1066,
	"k_EMsgGCPresets_SelectPresetForClassReply":      1067,
	"k_EMsgGCNameItemNotification":                   1068,
	"k_EMsgGCClientDisplayNotification":              1069,
	"k_EMsgGCApplyStrangePart":                       1070,
	"k_EMsgGC_IncrementKillCountAttribute":           1071,
	"k_EMsgGC_IncrementKillCountResponse":            1072,
	"k_EMsgGCRemoveStrangePart":                      1073,
	"k_EMsgGCResetStrangeScores":                     1074,
	"k_EMsgGCGiftedItems":                            1075,
	"k_EMsgGCApplyUpgradeCard":                       1077,
	"k_EMsgGCRemoveUpgradeCard":                      1078,
	"k_EMsgGCApplyStrangeRestriction":                1079,
	"k_EMsgGCClientRequestMarketData":                1080,
	"k_EMsgGCClientRequestMarketDataResponse":        1081,
	"k_EMsgGCApplyXifier":                            1082,
	"k_EMsgGCApplyXifierResponse":                    1083,
	"k_EMsgGC_TrackUniquePlayerPairEvent":            1084,
	"k_EMsgGCFulfillDynamicRecipeComponent":          1085,
	"k_EMsgGCFulfillDynamicRecipeComponentResponse":  1086,
	"k_EMsgGCSetItemEffectVerticalOffset":            1087,
	"k_EMsgGCSetHatEffectUseHeadOrigin":              1088,
	"k_EMsgGCItemEaterRecharger":                     1089,
	"k_EMsgGCItemEaterRechargerResponse":             1090,
	"k_EMsgGCApplyBaseItemXifier":                    1091,
	"k_EMsgGCApplyClassTransmogrifier":               1092,
	"k_EMsgGCApplyHalloweenSpellbookPage":            1093,
	"k_EMsgGCRemoveKillStreak":                       1094,
	"k_EMsgGCRemoveKillStreakResponse":               1095,
	"k_EMsgGCTFSpecificItemBroadcast":                1096,
	"k_EMsgGC_IncrementKillCountAttribute_Multiple":  1097,
	"k_EMsgGCDeliverGiftResponseGiver":               1098,
	"k_EMsgGCSetItemPositions":                       1100,
	"k_EMsgGCLookupMultipleAccountNames":             1101,
	"k_EMsgGCLookupMultipleAccountNamesResponse":     1102,
	"k_EMsgGCTradingBase":                            1500,
	"k_EMsgGCTrading_InitiateTradeRequest":           1501,
	"k_EMsgGCTrading_InitiateTradeResponse":          1502,
	"k_EMsgGCTrading_StartSession":                   1503,
	"k_EMsgGCTrading_SessionClosed":                  1509,
	"k_EMsgGCTrading_CancelSession":                  1510,
	"k_EMsgGCTrading_InitiateTradeRequestResponse":   1514,
	"k_EMsgGCServerBrowser_FavoriteServer":           1601,
	"k_EMsgGCServerBrowser_BlacklistServer":          1602,
	"k_EMsgGCServerRentalsBase":                      1700,
	"k_EMsgGCItemPreviewCheckStatus":                 1701,
	"k_EMsgGCItemPreviewStatusResponse":              1702,
	"k_EMsgGCItemPreviewRequest":                     1703,
	"k_EMsgGCItemPreviewRequestResponse":             1704,
	"k_EMsgGCItemPreviewExpire":                      1705,
	"k_EMsgGCItemPreviewExpireNotification":          1706,
	"k_EMsgGCItemPreviewItemBoughtNotification":      1708,
	"k_EMsgGCDev_NewItemRequest":                     2001,
	"k_EMsgGCDev_NewItemRequestResponse":             2002,
	"k_EMsgGCDev_DebugRollLootRequest":               2003,
	"k_EMsgGCStoreGetUserData":                       2500,
	"k_EMsgGCStoreGetUserDataResponse":               2501,
	"k_EMsgGCStorePurchaseInit_DEPRECATED":           2502,
	"k_EMsgGCStorePurchaseInitResponse_DEPRECATED":   2503,
	"k_EMsgGCStorePurchaseFinalize":                  2512,
	"k_EMsgGCStorePurchaseFinalizeResponse":          2513,
	"k_EMsgGCStorePurchaseCancel":                    2514,
	"k_EMsgGCStorePurchaseCancelResponse":            2515,
	"k_EMsgGCStorePurchaseQueryTxn":                  2508,
	"k_EMsgGCStorePurchaseQueryTxnResponse":          2509,
	"k_EMsgGCStorePurchaseInit":                      2510,
	"k_EMsgGCStorePurchaseInitResponse":              2511,
	"k_EMsgGCToGCDirtySDOCache":                      2516,
	"k_EMsgGCToGCDirtyMultipleSDOCache":              2517,
	"k_EMsgGCToGCUpdateSQLKeyValue":                  2518,
	"k_EMsgGCToGCBroadcastConsoleCommand":            2521,
	"k_EMsgGCServerVersionUpdated":                   2522,
	"k_EMsgGCApplyAutograph":                         2523,
	"k_EMsgGCToGCWebAPIAccountChanged":               2524,
	"k_EMsgGCRequestAnnouncements":                   2525,
	"k_EMsgGCRequestAnnouncementsResponse":           2526,
	"k_EMsgGCRequestPassportItemGrant":               2527,
	"k_EMsgGCClientVersionUpdated":                   2528,
	"k_EMsgGCItemPurgatory_FinalizePurchase":         2531,
	"k_EMsgGCItemPurgatory_FinalizePurchaseResponse": 2532,
	"k_EMsgGCItemPurgatory_RefundPurchase":           2533,
	"k_EMsgGCItemPurgatory_RefundPurchaseResponse":   2534,
	"k_EMsgGCToGCPlayerStrangeCountAdjustments":      2535,
	"k_EMsgGCRequestStoreSalesData":                  2536,
	"k_EMsgGCRequestStoreSalesDataResponse":          2537,
	"k_EMsgGCRequestStoreSalesDataUpToDateResponse":  2538,
	"k_EMsgGCToGCPingRequest":                        2539,
	"k_EMsgGCToGCPingResponse":                       2540,
	"k_EMsgGCToGCGetUserSessionServer":               2541,
	"k_EMsgGCToGCGetUserSessionServerResponse":       2542,
	"k_EMsgGCToGCGetUserServerMembers":               2543,
	"k_EMsgGCToGCGetUserServerMembersResponse":       2544,
	"k_EMsgGCToGCGrantSelfMadeItemToAccount":         2555,
	"k_EMsgGCToGCThankedByNewUser":                   2556,
	"k_EMsgGCShuffleCrateContents":                   2557,
	"k_EMsgGCQuestObjective_Progress":                2558,
	"k_EMsgGCQuestCompleted":                         2559,
	"k_EMsgGCApplyDuckToken":                         2560,
	"k_EMsgGCQuestComplete_Request":                  2561,
	"k_EMsgGCQuestObjective_PointsChange":            2562,
	"k_EMsgGCQuestObjective_PointsChangeResponse":    2563,
	"k_EMsgGCQuestObjective_RequestLoanerItems":      2564,
	"k_EMsgGCQuestObjective_RequestLoanerResponse":   2565,
	"k_EMsgGCApplyStrangeCountTransfer":              2566,
	"k_EMsgGCCraftCollectionUpgrade":                 2567,
	"k_EMsgGCCraftHalloweenOffering":                 2568,
	"k_EMsgGCQuestDiscard_Request":                   2569,
	"k_EMsgGCRemoveGiftedBy":                         2570,
	"k_EMsgGCRemoveGiftedByResponse":                 2571,
}

func (x EGCItemMsg) Enum() *EGCItemMsg {
	p := new(EGCItemMsg)
	*p = x
	return p
}
func (x EGCItemMsg) String() string {
	return proto.EnumName(EGCItemMsg_name, int32(x))
}
func (x *EGCItemMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCItemMsg_value, data, "EGCItemMsg")
	if err != nil {
		return err
	}
	*x = EGCItemMsg(value)
	return nil
}
func (EGCItemMsg) EnumDescriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{0} }

type EGCMsgResponse int32

const (
	EGCMsgResponse_k_EGCMsgResponseOK           EGCMsgResponse = 0
	EGCMsgResponse_k_EGCMsgResponseDenied       EGCMsgResponse = 1
	EGCMsgResponse_k_EGCMsgResponseServerError  EGCMsgResponse = 2
	EGCMsgResponse_k_EGCMsgResponseTimeout      EGCMsgResponse = 3
	EGCMsgResponse_k_EGCMsgResponseInvalid      EGCMsgResponse = 4
	EGCMsgResponse_k_EGCMsgResponseNoMatch      EGCMsgResponse = 5
	EGCMsgResponse_k_EGCMsgResponseUnknownError EGCMsgResponse = 6
	EGCMsgResponse_k_EGCMsgResponseNotLoggedOn  EGCMsgResponse = 7
	EGCMsgResponse_k_EGCMsgFailedToCreate       EGCMsgResponse = 8
)

var EGCMsgResponse_name = map[int32]string{
	0: "k_EGCMsgResponseOK",
	1: "k_EGCMsgResponseDenied",
	2: "k_EGCMsgResponseServerError",
	3: "k_EGCMsgResponseTimeout",
	4: "k_EGCMsgResponseInvalid",
	5: "k_EGCMsgResponseNoMatch",
	6: "k_EGCMsgResponseUnknownError",
	7: "k_EGCMsgResponseNotLoggedOn",
	8: "k_EGCMsgFailedToCreate",
}
var EGCMsgResponse_value = map[string]int32{
	"k_EGCMsgResponseOK":           0,
	"k_EGCMsgResponseDenied":       1,
	"k_EGCMsgResponseServerError":  2,
	"k_EGCMsgResponseTimeout":      3,
	"k_EGCMsgResponseInvalid":      4,
	"k_EGCMsgResponseNoMatch":      5,
	"k_EGCMsgResponseUnknownError": 6,
	"k_EGCMsgResponseNotLoggedOn":  7,
	"k_EGCMsgFailedToCreate":       8,
}

func (x EGCMsgResponse) Enum() *EGCMsgResponse {
	p := new(EGCMsgResponse)
	*p = x
	return p
}
func (x EGCMsgResponse) String() string {
	return proto.EnumName(EGCMsgResponse_name, int32(x))
}
func (x *EGCMsgResponse) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCMsgResponse_value, data, "EGCMsgResponse")
	if err != nil {
		return err
	}
	*x = EGCMsgResponse(value)
	return nil
}
func (EGCMsgResponse) EnumDescriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{1} }

type EUnlockStyle int32

const (
	EUnlockStyle_k_UnlockStyle_Succeeded               EUnlockStyle = 0
	EUnlockStyle_k_UnlockStyle_Failed_PreReq           EUnlockStyle = 1
	EUnlockStyle_k_UnlockStyle_Failed_CantAfford       EUnlockStyle = 2
	EUnlockStyle_k_UnlockStyle_Failed_CantCommit       EUnlockStyle = 3
	EUnlockStyle_k_UnlockStyle_Failed_CantLockCache    EUnlockStyle = 4
	EUnlockStyle_k_UnlockStyle_Failed_CantAffordAttrib EUnlockStyle = 5
	EUnlockStyle_k_UnlockStyle_Failed_CantAffordGem    EUnlockStyle = 6
)

var EUnlockStyle_name = map[int32]string{
	0: "k_UnlockStyle_Succeeded",
	1: "k_UnlockStyle_Failed_PreReq",
	2: "k_UnlockStyle_Failed_CantAfford",
	3: "k_UnlockStyle_Failed_CantCommit",
	4: "k_UnlockStyle_Failed_CantLockCache",
	5: "k_UnlockStyle_Failed_CantAffordAttrib",
	6: "k_UnlockStyle_Failed_CantAffordGem",
}
var EUnlockStyle_value = map[string]int32{
	"k_UnlockStyle_Succeeded":               0,
	"k_UnlockStyle_Failed_PreReq":           1,
	"k_UnlockStyle_Failed_CantAfford":       2,
	"k_UnlockStyle_Failed_CantCommit":       3,
	"k_UnlockStyle_Failed_CantLockCache":    4,
	"k_UnlockStyle_Failed_CantAffordAttrib": 5,
	"k_UnlockStyle_Failed_CantAffordGem":    6,
}

func (x EUnlockStyle) Enum() *EUnlockStyle {
	p := new(EUnlockStyle)
	*p = x
	return p
}
func (x EUnlockStyle) String() string {
	return proto.EnumName(EUnlockStyle_name, int32(x))
}
func (x *EUnlockStyle) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EUnlockStyle_value, data, "EUnlockStyle")
	if err != nil {
		return err
	}
	*x = EUnlockStyle(value)
	return nil
}
func (EUnlockStyle) EnumDescriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{2} }

type EItemPurgatoryResponse_Finalize int32

const (
	EItemPurgatoryResponse_Finalize_k_ItemPurgatoryResponse_Finalize_Succeeded                  EItemPurgatoryResponse_Finalize = 0
	EItemPurgatoryResponse_Finalize_k_ItemPurgatoryResponse_Finalize_Failed_Incomplete          EItemPurgatoryResponse_Finalize = 1
	EItemPurgatoryResponse_Finalize_k_ItemPurgatoryResponse_Finalize_Failed_ItemsNotInPurgatory EItemPurgatoryResponse_Finalize = 2
	EItemPurgatoryResponse_Finalize_k_ItemPurgatoryResponse_Finalize_Failed_CouldNotFindItems   EItemPurgatoryResponse_Finalize = 3
	EItemPurgatoryResponse_Finalize_k_ItemPurgatoryResponse_Finalize_Failed_NoSOCache           EItemPurgatoryResponse_Finalize = 4
	EItemPurgatoryResponse_Finalize_k_ItemPurgatoryResponse_Finalize_BackpackFull               EItemPurgatoryResponse_Finalize = 5
)

var EItemPurgatoryResponse_Finalize_name = map[int32]string{
	0: "k_ItemPurgatoryResponse_Finalize_Succeeded",
	1: "k_ItemPurgatoryResponse_Finalize_Failed_Incomplete",
	2: "k_ItemPurgatoryResponse_Finalize_Failed_ItemsNotInPurgatory",
	3: "k_ItemPurgatoryResponse_Finalize_Failed_CouldNotFindItems",
	4: "k_ItemPurgatoryResponse_Finalize_Failed_NoSOCache",
	5: "k_ItemPurgatoryResponse_Finalize_BackpackFull",
}
var EItemPurgatoryResponse_Finalize_value = map[string]int32{
	"k_ItemPurgatoryResponse_Finalize_Succeeded":                  0,
	"k_ItemPurgatoryResponse_Finalize_Failed_Incomplete":          1,
	"k_ItemPurgatoryResponse_Finalize_Failed_ItemsNotInPurgatory": 2,
	"k_ItemPurgatoryResponse_Finalize_Failed_CouldNotFindItems":   3,
	"k_ItemPurgatoryResponse_Finalize_Failed_NoSOCache":           4,
	"k_ItemPurgatoryResponse_Finalize_BackpackFull":               5,
}

func (x EItemPurgatoryResponse_Finalize) Enum() *EItemPurgatoryResponse_Finalize {
	p := new(EItemPurgatoryResponse_Finalize)
	*p = x
	return p
}
func (x EItemPurgatoryResponse_Finalize) String() string {
	return proto.EnumName(EItemPurgatoryResponse_Finalize_name, int32(x))
}
func (x *EItemPurgatoryResponse_Finalize) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EItemPurgatoryResponse_Finalize_value, data, "EItemPurgatoryResponse_Finalize")
	if err != nil {
		return err
	}
	*x = EItemPurgatoryResponse_Finalize(value)
	return nil
}
func (EItemPurgatoryResponse_Finalize) EnumDescriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{3}
}

type EItemPurgatoryResponse_Refund int32

const (
	EItemPurgatoryResponse_Refund_k_ItemPurgatoryResponse_Refund_Succeeded                 EItemPurgatoryResponse_Refund = 0
	EItemPurgatoryResponse_Refund_k_ItemPurgatoryResponse_Refund_Failed_ItemNotInPurgatory EItemPurgatoryResponse_Refund = 1
	EItemPurgatoryResponse_Refund_k_ItemPurgatoryResponse_Refund_Failed_CouldNotFindItem   EItemPurgatoryResponse_Refund = 2
	EItemPurgatoryResponse_Refund_k_ItemPurgatoryResponse_Refund_Failed_NoSOCache          EItemPurgatoryResponse_Refund = 3
	EItemPurgatoryResponse_Refund_k_ItemPurgatoryResponse_Refund_Failed_NoDetail           EItemPurgatoryResponse_Refund = 4
	EItemPurgatoryResponse_Refund_k_ItemPurgatoryResponse_Refund_Failed_NexonWebAPI        EItemPurgatoryResponse_Refund = 5
)

var EItemPurgatoryResponse_Refund_name = map[int32]string{
	0: "k_ItemPurgatoryResponse_Refund_Succeeded",
	1: "k_ItemPurgatoryResponse_Refund_Failed_ItemNotInPurgatory",
	2: "k_ItemPurgatoryResponse_Refund_Failed_CouldNotFindItem",
	3: "k_ItemPurgatoryResponse_Refund_Failed_NoSOCache",
	4: "k_ItemPurgatoryResponse_Refund_Failed_NoDetail",
	5: "k_ItemPurgatoryResponse_Refund_Failed_NexonWebAPI",
}
var EItemPurgatoryResponse_Refund_value = map[string]int32{
	"k_ItemPurgatoryResponse_Refund_Succeeded":                 0,
	"k_ItemPurgatoryResponse_Refund_Failed_ItemNotInPurgatory": 1,
	"k_ItemPurgatoryResponse_Refund_Failed_CouldNotFindItem":   2,
	"k_ItemPurgatoryResponse_Refund_Failed_NoSOCache":          3,
	"k_ItemPurgatoryResponse_Refund_Failed_NoDetail":           4,
	"k_ItemPurgatoryResponse_Refund_Failed_NexonWebAPI":        5,
}

func (x EItemPurgatoryResponse_Refund) Enum() *EItemPurgatoryResponse_Refund {
	p := new(EItemPurgatoryResponse_Refund)
	*p = x
	return p
}
func (x EItemPurgatoryResponse_Refund) String() string {
	return proto.EnumName(EItemPurgatoryResponse_Refund_name, int32(x))
}
func (x *EItemPurgatoryResponse_Refund) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EItemPurgatoryResponse_Refund_value, data, "EItemPurgatoryResponse_Refund")
	if err != nil {
		return err
	}
	*x = EItemPurgatoryResponse_Refund(value)
	return nil
}
func (EItemPurgatoryResponse_Refund) EnumDescriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{4}
}

type CMsgApplyAutograph struct {
	AutographItemId  *uint64 `protobuf:"varint,1,opt,name=autograph_item_id,json=autographItemId" json:"autograph_item_id,omitempty"`
	ItemItemId       *uint64 `protobuf:"varint,2,opt,name=item_item_id,json=itemItemId" json:"item_item_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgApplyAutograph) Reset()                    { *m = CMsgApplyAutograph{} }
func (m *CMsgApplyAutograph) String() string            { return proto.CompactTextString(m) }
func (*CMsgApplyAutograph) ProtoMessage()               {}
func (*CMsgApplyAutograph) Descriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{0} }

func (m *CMsgApplyAutograph) GetAutographItemId() uint64 {
	if m != nil && m.AutographItemId != nil {
		return *m.AutographItemId
	}
	return 0
}

func (m *CMsgApplyAutograph) GetItemItemId() uint64 {
	if m != nil && m.ItemItemId != nil {
		return *m.ItemItemId
	}
	return 0
}

type CMsgEconPlayerStrangeCountAdjustment struct {
	AccountId               *uint32                                                         `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	StrangeCountAdjustments []*CMsgEconPlayerStrangeCountAdjustment_CStrangeCountAdjustment `protobuf:"bytes,2,rep,name=strange_count_adjustments,json=strangeCountAdjustments" json:"strange_count_adjustments,omitempty"`
	XXX_unrecognized        []byte                                                          `json:"-"`
}

func (m *CMsgEconPlayerStrangeCountAdjustment) Reset()         { *m = CMsgEconPlayerStrangeCountAdjustment{} }
func (m *CMsgEconPlayerStrangeCountAdjustment) String() string { return proto.CompactTextString(m) }
func (*CMsgEconPlayerStrangeCountAdjustment) ProtoMessage()    {}
func (*CMsgEconPlayerStrangeCountAdjustment) Descriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{1}
}

func (m *CMsgEconPlayerStrangeCountAdjustment) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CMsgEconPlayerStrangeCountAdjustment) GetStrangeCountAdjustments() []*CMsgEconPlayerStrangeCountAdjustment_CStrangeCountAdjustment {
	if m != nil {
		return m.StrangeCountAdjustments
	}
	return nil
}

type CMsgEconPlayerStrangeCountAdjustment_CStrangeCountAdjustment struct {
	EventType        *uint32 `protobuf:"varint,1,opt,name=event_type,json=eventType" json:"event_type,omitempty"`
	ItemId           *uint64 `protobuf:"varint,2,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	Adjustment       *uint32 `protobuf:"varint,3,opt,name=adjustment" json:"adjustment,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgEconPlayerStrangeCountAdjustment_CStrangeCountAdjustment) Reset() {
	*m = CMsgEconPlayerStrangeCountAdjustment_CStrangeCountAdjustment{}
}
func (m *CMsgEconPlayerStrangeCountAdjustment_CStrangeCountAdjustment) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgEconPlayerStrangeCountAdjustment_CStrangeCountAdjustment) ProtoMessage() {}
func (*CMsgEconPlayerStrangeCountAdjustment_CStrangeCountAdjustment) Descriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{1, 0}
}

func (m *CMsgEconPlayerStrangeCountAdjustment_CStrangeCountAdjustment) GetEventType() uint32 {
	if m != nil && m.EventType != nil {
		return *m.EventType
	}
	return 0
}

func (m *CMsgEconPlayerStrangeCountAdjustment_CStrangeCountAdjustment) GetItemId() uint64 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

func (m *CMsgEconPlayerStrangeCountAdjustment_CStrangeCountAdjustment) GetAdjustment() uint32 {
	if m != nil && m.Adjustment != nil {
		return *m.Adjustment
	}
	return 0
}

type CMsgRequestItemPurgatory_FinalizePurchase struct {
	ItemIds          []uint64 `protobuf:"varint,1,rep,name=item_ids,json=itemIds" json:"item_ids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CMsgRequestItemPurgatory_FinalizePurchase) Reset() {
	*m = CMsgRequestItemPurgatory_FinalizePurchase{}
}
func (m *CMsgRequestItemPurgatory_FinalizePurchase) String() string { return proto.CompactTextString(m) }
func (*CMsgRequestItemPurgatory_FinalizePurchase) ProtoMessage()    {}
func (*CMsgRequestItemPurgatory_FinalizePurchase) Descriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{2}
}

func (m *CMsgRequestItemPurgatory_FinalizePurchase) GetItemIds() []uint64 {
	if m != nil {
		return m.ItemIds
	}
	return nil
}

type CMsgRequestItemPurgatory_FinalizePurchaseResponse struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgRequestItemPurgatory_FinalizePurchaseResponse) Reset() {
	*m = CMsgRequestItemPurgatory_FinalizePurchaseResponse{}
}
func (m *CMsgRequestItemPurgatory_FinalizePurchaseResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgRequestItemPurgatory_FinalizePurchaseResponse) ProtoMessage() {}
func (*CMsgRequestItemPurgatory_FinalizePurchaseResponse) Descriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{3}
}

func (m *CMsgRequestItemPurgatory_FinalizePurchaseResponse) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type CMsgRequestItemPurgatory_RefundPurchase struct {
	ItemId           *uint64 `protobuf:"varint,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgRequestItemPurgatory_RefundPurchase) Reset() {
	*m = CMsgRequestItemPurgatory_RefundPurchase{}
}
func (m *CMsgRequestItemPurgatory_RefundPurchase) String() string { return proto.CompactTextString(m) }
func (*CMsgRequestItemPurgatory_RefundPurchase) ProtoMessage()    {}
func (*CMsgRequestItemPurgatory_RefundPurchase) Descriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{4}
}

func (m *CMsgRequestItemPurgatory_RefundPurchase) GetItemId() uint64 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

type CMsgRequestItemPurgatory_RefundPurchaseResponse struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgRequestItemPurgatory_RefundPurchaseResponse) Reset() {
	*m = CMsgRequestItemPurgatory_RefundPurchaseResponse{}
}
func (m *CMsgRequestItemPurgatory_RefundPurchaseResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgRequestItemPurgatory_RefundPurchaseResponse) ProtoMessage() {}
func (*CMsgRequestItemPurgatory_RefundPurchaseResponse) Descriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{5}
}

func (m *CMsgRequestItemPurgatory_RefundPurchaseResponse) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type CMsgCraftingResponse struct {
	ItemIds          []uint64 `protobuf:"varint,1,rep,name=item_ids,json=itemIds" json:"item_ids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CMsgCraftingResponse) Reset()                    { *m = CMsgCraftingResponse{} }
func (m *CMsgCraftingResponse) String() string            { return proto.CompactTextString(m) }
func (*CMsgCraftingResponse) ProtoMessage()               {}
func (*CMsgCraftingResponse) Descriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{6} }

func (m *CMsgCraftingResponse) GetItemIds() []uint64 {
	if m != nil {
		return m.ItemIds
	}
	return nil
}

type CMsgGCRequestStoreSalesData struct {
	Version          *uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Currency         *uint32 `protobuf:"varint,2,opt,name=currency" json:"currency,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGCRequestStoreSalesData) Reset()                    { *m = CMsgGCRequestStoreSalesData{} }
func (m *CMsgGCRequestStoreSalesData) String() string            { return proto.CompactTextString(m) }
func (*CMsgGCRequestStoreSalesData) ProtoMessage()               {}
func (*CMsgGCRequestStoreSalesData) Descriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{7} }

func (m *CMsgGCRequestStoreSalesData) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *CMsgGCRequestStoreSalesData) GetCurrency() uint32 {
	if m != nil && m.Currency != nil {
		return *m.Currency
	}
	return 0
}

type CMsgGCRequestStoreSalesDataResponse struct {
	SalePrice        []*CMsgGCRequestStoreSalesDataResponse_Price `protobuf:"bytes,1,rep,name=sale_price,json=salePrice" json:"sale_price,omitempty"`
	Version          *uint32                                      `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	ExpirationTime   *uint32                                      `protobuf:"varint,3,opt,name=expiration_time,json=expirationTime" json:"expiration_time,omitempty"`
	XXX_unrecognized []byte                                       `json:"-"`
}

func (m *CMsgGCRequestStoreSalesDataResponse) Reset()         { *m = CMsgGCRequestStoreSalesDataResponse{} }
func (m *CMsgGCRequestStoreSalesDataResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgGCRequestStoreSalesDataResponse) ProtoMessage()    {}
func (*CMsgGCRequestStoreSalesDataResponse) Descriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{8}
}

func (m *CMsgGCRequestStoreSalesDataResponse) GetSalePrice() []*CMsgGCRequestStoreSalesDataResponse_Price {
	if m != nil {
		return m.SalePrice
	}
	return nil
}

func (m *CMsgGCRequestStoreSalesDataResponse) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *CMsgGCRequestStoreSalesDataResponse) GetExpirationTime() uint32 {
	if m != nil && m.ExpirationTime != nil {
		return *m.ExpirationTime
	}
	return 0
}

type CMsgGCRequestStoreSalesDataResponse_Price struct {
	ItemDef          *uint32 `protobuf:"varint,1,opt,name=item_def,json=itemDef" json:"item_def,omitempty"`
	Price            *uint32 `protobuf:"varint,2,opt,name=price" json:"price,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGCRequestStoreSalesDataResponse_Price) Reset() {
	*m = CMsgGCRequestStoreSalesDataResponse_Price{}
}
func (m *CMsgGCRequestStoreSalesDataResponse_Price) String() string { return proto.CompactTextString(m) }
func (*CMsgGCRequestStoreSalesDataResponse_Price) ProtoMessage()    {}
func (*CMsgGCRequestStoreSalesDataResponse_Price) Descriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{8, 0}
}

func (m *CMsgGCRequestStoreSalesDataResponse_Price) GetItemDef() uint32 {
	if m != nil && m.ItemDef != nil {
		return *m.ItemDef
	}
	return 0
}

func (m *CMsgGCRequestStoreSalesDataResponse_Price) GetPrice() uint32 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

type CMsgGCRequestStoreSalesDataUpToDateResponse struct {
	Version          *uint32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	ExpirationTime   *uint32 `protobuf:"varint,2,opt,name=expiration_time,json=expirationTime" json:"expiration_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGCRequestStoreSalesDataUpToDateResponse) Reset() {
	*m = CMsgGCRequestStoreSalesDataUpToDateResponse{}
}
func (m *CMsgGCRequestStoreSalesDataUpToDateResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgGCRequestStoreSalesDataUpToDateResponse) ProtoMessage() {}
func (*CMsgGCRequestStoreSalesDataUpToDateResponse) Descriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{9}
}

func (m *CMsgGCRequestStoreSalesDataUpToDateResponse) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *CMsgGCRequestStoreSalesDataUpToDateResponse) GetExpirationTime() uint32 {
	if m != nil && m.ExpirationTime != nil {
		return *m.ExpirationTime
	}
	return 0
}

type CMsgGCToGCPingRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMsgGCToGCPingRequest) Reset()                    { *m = CMsgGCToGCPingRequest{} }
func (m *CMsgGCToGCPingRequest) String() string            { return proto.CompactTextString(m) }
func (*CMsgGCToGCPingRequest) ProtoMessage()               {}
func (*CMsgGCToGCPingRequest) Descriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{10} }

type CMsgGCToGCPingResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMsgGCToGCPingResponse) Reset()                    { *m = CMsgGCToGCPingResponse{} }
func (m *CMsgGCToGCPingResponse) String() string            { return proto.CompactTextString(m) }
func (*CMsgGCToGCPingResponse) ProtoMessage()               {}
func (*CMsgGCToGCPingResponse) Descriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{11} }

type CMsgGCToGCGetUserSessionServer struct {
	AccountId        *uint32 `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGCToGCGetUserSessionServer) Reset()                    { *m = CMsgGCToGCGetUserSessionServer{} }
func (m *CMsgGCToGCGetUserSessionServer) String() string            { return proto.CompactTextString(m) }
func (*CMsgGCToGCGetUserSessionServer) ProtoMessage()               {}
func (*CMsgGCToGCGetUserSessionServer) Descriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{12} }

func (m *CMsgGCToGCGetUserSessionServer) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

type CMsgGCToGCGetUserSessionServerResponse struct {
	ServerSteamId    *uint64 `protobuf:"fixed64,1,opt,name=server_steam_id,json=serverSteamId" json:"server_steam_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGCToGCGetUserSessionServerResponse) Reset() {
	*m = CMsgGCToGCGetUserSessionServerResponse{}
}
func (m *CMsgGCToGCGetUserSessionServerResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgGCToGCGetUserSessionServerResponse) ProtoMessage()    {}
func (*CMsgGCToGCGetUserSessionServerResponse) Descriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{13}
}

func (m *CMsgGCToGCGetUserSessionServerResponse) GetServerSteamId() uint64 {
	if m != nil && m.ServerSteamId != nil {
		return *m.ServerSteamId
	}
	return 0
}

type CMsgGCToGCGetUserServerMembers struct {
	AccountId        *uint32 `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	MaxSpectators    *uint32 `protobuf:"varint,2,opt,name=max_spectators,json=maxSpectators" json:"max_spectators,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGCToGCGetUserServerMembers) Reset()                    { *m = CMsgGCToGCGetUserServerMembers{} }
func (m *CMsgGCToGCGetUserServerMembers) String() string            { return proto.CompactTextString(m) }
func (*CMsgGCToGCGetUserServerMembers) ProtoMessage()               {}
func (*CMsgGCToGCGetUserServerMembers) Descriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{14} }

func (m *CMsgGCToGCGetUserServerMembers) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CMsgGCToGCGetUserServerMembers) GetMaxSpectators() uint32 {
	if m != nil && m.MaxSpectators != nil {
		return *m.MaxSpectators
	}
	return 0
}

type CMsgGCToGCGetUserServerMembersResponse struct {
	MemberAccountId  []uint32 `protobuf:"varint,1,rep,name=member_account_id,json=memberAccountId" json:"member_account_id,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CMsgGCToGCGetUserServerMembersResponse) Reset() {
	*m = CMsgGCToGCGetUserServerMembersResponse{}
}
func (m *CMsgGCToGCGetUserServerMembersResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgGCToGCGetUserServerMembersResponse) ProtoMessage()    {}
func (*CMsgGCToGCGetUserServerMembersResponse) Descriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{15}
}

func (m *CMsgGCToGCGetUserServerMembersResponse) GetMemberAccountId() []uint32 {
	if m != nil {
		return m.MemberAccountId
	}
	return nil
}

type CMsgLookupMultipleAccountNames struct {
	Accountids       []uint32 `protobuf:"varint,1,rep,packed,name=accountids" json:"accountids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CMsgLookupMultipleAccountNames) Reset()                    { *m = CMsgLookupMultipleAccountNames{} }
func (m *CMsgLookupMultipleAccountNames) String() string            { return proto.CompactTextString(m) }
func (*CMsgLookupMultipleAccountNames) ProtoMessage()               {}
func (*CMsgLookupMultipleAccountNames) Descriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{16} }

func (m *CMsgLookupMultipleAccountNames) GetAccountids() []uint32 {
	if m != nil {
		return m.Accountids
	}
	return nil
}

type CMsgLookupMultipleAccountNamesResponse struct {
	Accounts         []*CMsgLookupMultipleAccountNamesResponse_Account `protobuf:"bytes,1,rep,name=accounts" json:"accounts,omitempty"`
	XXX_unrecognized []byte                                            `json:"-"`
}

func (m *CMsgLookupMultipleAccountNamesResponse) Reset() {
	*m = CMsgLookupMultipleAccountNamesResponse{}
}
func (m *CMsgLookupMultipleAccountNamesResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgLookupMultipleAccountNamesResponse) ProtoMessage()    {}
func (*CMsgLookupMultipleAccountNamesResponse) Descriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{17}
}

func (m *CMsgLookupMultipleAccountNamesResponse) GetAccounts() []*CMsgLookupMultipleAccountNamesResponse_Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type CMsgLookupMultipleAccountNamesResponse_Account struct {
	Accountid        *uint32 `protobuf:"varint,1,opt,name=accountid" json:"accountid,omitempty"`
	Persona          *string `protobuf:"bytes,2,opt,name=persona" json:"persona,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgLookupMultipleAccountNamesResponse_Account) Reset() {
	*m = CMsgLookupMultipleAccountNamesResponse_Account{}
}
func (m *CMsgLookupMultipleAccountNamesResponse_Account) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgLookupMultipleAccountNamesResponse_Account) ProtoMessage() {}
func (*CMsgLookupMultipleAccountNamesResponse_Account) Descriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{17, 0}
}

func (m *CMsgLookupMultipleAccountNamesResponse_Account) GetAccountid() uint32 {
	if m != nil && m.Accountid != nil {
		return *m.Accountid
	}
	return 0
}

func (m *CMsgLookupMultipleAccountNamesResponse_Account) GetPersona() string {
	if m != nil && m.Persona != nil {
		return *m.Persona
	}
	return ""
}

type CMsgGCToGCGrantSelfMadeItemToAccount struct {
	ItemDefIndex     *uint32 `protobuf:"varint,1,opt,name=item_def_index,json=itemDefIndex" json:"item_def_index,omitempty"`
	Accountid        *uint32 `protobuf:"varint,2,opt,name=accountid" json:"accountid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGCToGCGrantSelfMadeItemToAccount) Reset()         { *m = CMsgGCToGCGrantSelfMadeItemToAccount{} }
func (m *CMsgGCToGCGrantSelfMadeItemToAccount) String() string { return proto.CompactTextString(m) }
func (*CMsgGCToGCGrantSelfMadeItemToAccount) ProtoMessage()    {}
func (*CMsgGCToGCGrantSelfMadeItemToAccount) Descriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{18}
}

func (m *CMsgGCToGCGrantSelfMadeItemToAccount) GetItemDefIndex() uint32 {
	if m != nil && m.ItemDefIndex != nil {
		return *m.ItemDefIndex
	}
	return 0
}

func (m *CMsgGCToGCGrantSelfMadeItemToAccount) GetAccountid() uint32 {
	if m != nil && m.Accountid != nil {
		return *m.Accountid
	}
	return 0
}

type CMsgGCToGCThankedByNewUser struct {
	NewUserAccountid     *uint32 `protobuf:"varint,1,opt,name=new_user_accountid,json=newUserAccountid" json:"new_user_accountid,omitempty"`
	ThankedUserAccountid *uint32 `protobuf:"varint,2,opt,name=thanked_user_accountid,json=thankedUserAccountid" json:"thanked_user_accountid,omitempty"`
	XXX_unrecognized     []byte  `json:"-"`
}

func (m *CMsgGCToGCThankedByNewUser) Reset()                    { *m = CMsgGCToGCThankedByNewUser{} }
func (m *CMsgGCToGCThankedByNewUser) String() string            { return proto.CompactTextString(m) }
func (*CMsgGCToGCThankedByNewUser) ProtoMessage()               {}
func (*CMsgGCToGCThankedByNewUser) Descriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{19} }

func (m *CMsgGCToGCThankedByNewUser) GetNewUserAccountid() uint32 {
	if m != nil && m.NewUserAccountid != nil {
		return *m.NewUserAccountid
	}
	return 0
}

func (m *CMsgGCToGCThankedByNewUser) GetThankedUserAccountid() uint32 {
	if m != nil && m.ThankedUserAccountid != nil {
		return *m.ThankedUserAccountid
	}
	return 0
}

type CMsgGCShuffleCrateContents struct {
	CrateItemId      *uint64 `protobuf:"varint,1,opt,name=crate_item_id,json=crateItemId" json:"crate_item_id,omitempty"`
	UserCodeString   *string `protobuf:"bytes,2,opt,name=user_code_string,json=userCodeString" json:"user_code_string,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGCShuffleCrateContents) Reset()                    { *m = CMsgGCShuffleCrateContents{} }
func (m *CMsgGCShuffleCrateContents) String() string            { return proto.CompactTextString(m) }
func (*CMsgGCShuffleCrateContents) ProtoMessage()               {}
func (*CMsgGCShuffleCrateContents) Descriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{20} }

func (m *CMsgGCShuffleCrateContents) GetCrateItemId() uint64 {
	if m != nil && m.CrateItemId != nil {
		return *m.CrateItemId
	}
	return 0
}

func (m *CMsgGCShuffleCrateContents) GetUserCodeString() string {
	if m != nil && m.UserCodeString != nil {
		return *m.UserCodeString
	}
	return ""
}

type CMsgGCQuestObjective_Progress struct {
	QuestItemId      *uint64 `protobuf:"varint,1,opt,name=quest_item_id,json=questItemId" json:"quest_item_id,omitempty"`
	QuestAttribIndex *uint32 `protobuf:"varint,2,opt,name=quest_attrib_index,json=questAttribIndex" json:"quest_attrib_index,omitempty"`
	Delta            *uint32 `protobuf:"varint,3,opt,name=delta" json:"delta,omitempty"`
	OwnerSteamid     *uint64 `protobuf:"fixed64,4,opt,name=owner_steamid,json=ownerSteamid" json:"owner_steamid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGCQuestObjective_Progress) Reset()                    { *m = CMsgGCQuestObjective_Progress{} }
func (m *CMsgGCQuestObjective_Progress) String() string            { return proto.CompactTextString(m) }
func (*CMsgGCQuestObjective_Progress) ProtoMessage()               {}
func (*CMsgGCQuestObjective_Progress) Descriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{21} }

func (m *CMsgGCQuestObjective_Progress) GetQuestItemId() uint64 {
	if m != nil && m.QuestItemId != nil {
		return *m.QuestItemId
	}
	return 0
}

func (m *CMsgGCQuestObjective_Progress) GetQuestAttribIndex() uint32 {
	if m != nil && m.QuestAttribIndex != nil {
		return *m.QuestAttribIndex
	}
	return 0
}

func (m *CMsgGCQuestObjective_Progress) GetDelta() uint32 {
	if m != nil && m.Delta != nil {
		return *m.Delta
	}
	return 0
}

func (m *CMsgGCQuestObjective_Progress) GetOwnerSteamid() uint64 {
	if m != nil && m.OwnerSteamid != nil {
		return *m.OwnerSteamid
	}
	return 0
}

type CMsgGCQuestObjective_PointsChange struct {
	QuestItemId      *uint64 `protobuf:"varint,1,opt,name=quest_item_id,json=questItemId" json:"quest_item_id,omitempty"`
	StandardPoints   *uint32 `protobuf:"varint,2,opt,name=standard_points,json=standardPoints" json:"standard_points,omitempty"`
	BonusPoints      *uint32 `protobuf:"varint,3,opt,name=bonus_points,json=bonusPoints" json:"bonus_points,omitempty"`
	OwnerSteamid     *uint64 `protobuf:"fixed64,4,opt,name=owner_steamid,json=ownerSteamid" json:"owner_steamid,omitempty"`
	UpdateBasePoints *bool   `protobuf:"varint,5,opt,name=update_base_points,json=updateBasePoints,def=0" json:"update_base_points,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGCQuestObjective_PointsChange) Reset()         { *m = CMsgGCQuestObjective_PointsChange{} }
func (m *CMsgGCQuestObjective_PointsChange) String() string { return proto.CompactTextString(m) }
func (*CMsgGCQuestObjective_PointsChange) ProtoMessage()    {}
func (*CMsgGCQuestObjective_PointsChange) Descriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{22}
}

const Default_CMsgGCQuestObjective_PointsChange_UpdateBasePoints bool = false

func (m *CMsgGCQuestObjective_PointsChange) GetQuestItemId() uint64 {
	if m != nil && m.QuestItemId != nil {
		return *m.QuestItemId
	}
	return 0
}

func (m *CMsgGCQuestObjective_PointsChange) GetStandardPoints() uint32 {
	if m != nil && m.StandardPoints != nil {
		return *m.StandardPoints
	}
	return 0
}

func (m *CMsgGCQuestObjective_PointsChange) GetBonusPoints() uint32 {
	if m != nil && m.BonusPoints != nil {
		return *m.BonusPoints
	}
	return 0
}

func (m *CMsgGCQuestObjective_PointsChange) GetOwnerSteamid() uint64 {
	if m != nil && m.OwnerSteamid != nil {
		return *m.OwnerSteamid
	}
	return 0
}

func (m *CMsgGCQuestObjective_PointsChange) GetUpdateBasePoints() bool {
	if m != nil && m.UpdateBasePoints != nil {
		return *m.UpdateBasePoints
	}
	return Default_CMsgGCQuestObjective_PointsChange_UpdateBasePoints
}

type CMsgGCQuestObjective_PointsChangeResponse struct {
	QuestItemId      *uint64 `protobuf:"varint,1,opt,name=quest_item_id,json=questItemId" json:"quest_item_id,omitempty"`
	StandardPoints   *uint32 `protobuf:"varint,2,opt,name=standard_points,json=standardPoints" json:"standard_points,omitempty"`
	BonusPoints      *uint32 `protobuf:"varint,3,opt,name=bonus_points,json=bonusPoints" json:"bonus_points,omitempty"`
	UpdateBasePoints *bool   `protobuf:"varint,4,opt,name=update_base_points,json=updateBasePoints" json:"update_base_points,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGCQuestObjective_PointsChangeResponse) Reset() {
	*m = CMsgGCQuestObjective_PointsChangeResponse{}
}
func (m *CMsgGCQuestObjective_PointsChangeResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgGCQuestObjective_PointsChangeResponse) ProtoMessage()    {}
func (*CMsgGCQuestObjective_PointsChangeResponse) Descriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{23}
}

func (m *CMsgGCQuestObjective_PointsChangeResponse) GetQuestItemId() uint64 {
	if m != nil && m.QuestItemId != nil {
		return *m.QuestItemId
	}
	return 0
}

func (m *CMsgGCQuestObjective_PointsChangeResponse) GetStandardPoints() uint32 {
	if m != nil && m.StandardPoints != nil {
		return *m.StandardPoints
	}
	return 0
}

func (m *CMsgGCQuestObjective_PointsChangeResponse) GetBonusPoints() uint32 {
	if m != nil && m.BonusPoints != nil {
		return *m.BonusPoints
	}
	return 0
}

func (m *CMsgGCQuestObjective_PointsChangeResponse) GetUpdateBasePoints() bool {
	if m != nil && m.UpdateBasePoints != nil {
		return *m.UpdateBasePoints
	}
	return false
}

type CMsgGCQuestComplete_Request struct {
	QuestItemId      *uint64 `protobuf:"varint,1,opt,name=quest_item_id,json=questItemId" json:"quest_item_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGCQuestComplete_Request) Reset()                    { *m = CMsgGCQuestComplete_Request{} }
func (m *CMsgGCQuestComplete_Request) String() string            { return proto.CompactTextString(m) }
func (*CMsgGCQuestComplete_Request) ProtoMessage()               {}
func (*CMsgGCQuestComplete_Request) Descriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{24} }

func (m *CMsgGCQuestComplete_Request) GetQuestItemId() uint64 {
	if m != nil && m.QuestItemId != nil {
		return *m.QuestItemId
	}
	return 0
}

type CMsgGCQuestCompleted struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMsgGCQuestCompleted) Reset()                    { *m = CMsgGCQuestCompleted{} }
func (m *CMsgGCQuestCompleted) String() string            { return proto.CompactTextString(m) }
func (*CMsgGCQuestCompleted) ProtoMessage()               {}
func (*CMsgGCQuestCompleted) Descriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{25} }

type CMsgGCQuestObjective_RequestLoanerItems struct {
	QuestItemId      *uint64 `protobuf:"varint,1,opt,name=quest_item_id,json=questItemId" json:"quest_item_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGCQuestObjective_RequestLoanerItems) Reset() {
	*m = CMsgGCQuestObjective_RequestLoanerItems{}
}
func (m *CMsgGCQuestObjective_RequestLoanerItems) String() string { return proto.CompactTextString(m) }
func (*CMsgGCQuestObjective_RequestLoanerItems) ProtoMessage()    {}
func (*CMsgGCQuestObjective_RequestLoanerItems) Descriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{26}
}

func (m *CMsgGCQuestObjective_RequestLoanerItems) GetQuestItemId() uint64 {
	if m != nil && m.QuestItemId != nil {
		return *m.QuestItemId
	}
	return 0
}

type CMsgGCQuestObjective_RequestLoanerResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMsgGCQuestObjective_RequestLoanerResponse) Reset() {
	*m = CMsgGCQuestObjective_RequestLoanerResponse{}
}
func (m *CMsgGCQuestObjective_RequestLoanerResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgGCQuestObjective_RequestLoanerResponse) ProtoMessage() {}
func (*CMsgGCQuestObjective_RequestLoanerResponse) Descriptor() ([]byte, []int) {
	return econ_fileDescriptor0, []int{27}
}

type CMsgCraftCollectionUpgrade struct {
	ItemId           []uint64 `protobuf:"varint,1,rep,name=item_id,json=itemId" json:"item_id,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CMsgCraftCollectionUpgrade) Reset()                    { *m = CMsgCraftCollectionUpgrade{} }
func (m *CMsgCraftCollectionUpgrade) String() string            { return proto.CompactTextString(m) }
func (*CMsgCraftCollectionUpgrade) ProtoMessage()               {}
func (*CMsgCraftCollectionUpgrade) Descriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{28} }

func (m *CMsgCraftCollectionUpgrade) GetItemId() []uint64 {
	if m != nil {
		return m.ItemId
	}
	return nil
}

type CMsgCraftHalloweenOffering struct {
	ToolId           *uint64  `protobuf:"varint,1,opt,name=tool_id,json=toolId" json:"tool_id,omitempty"`
	ItemId           []uint64 `protobuf:"varint,2,rep,name=item_id,json=itemId" json:"item_id,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CMsgCraftHalloweenOffering) Reset()                    { *m = CMsgCraftHalloweenOffering{} }
func (m *CMsgCraftHalloweenOffering) String() string            { return proto.CompactTextString(m) }
func (*CMsgCraftHalloweenOffering) ProtoMessage()               {}
func (*CMsgCraftHalloweenOffering) Descriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{29} }

func (m *CMsgCraftHalloweenOffering) GetToolId() uint64 {
	if m != nil && m.ToolId != nil {
		return *m.ToolId
	}
	return 0
}

func (m *CMsgCraftHalloweenOffering) GetItemId() []uint64 {
	if m != nil {
		return m.ItemId
	}
	return nil
}

type CMsgGCQuestDiscard_Request struct {
	QuestItemId      *uint64 `protobuf:"varint,1,opt,name=quest_item_id,json=questItemId" json:"quest_item_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGCQuestDiscard_Request) Reset()                    { *m = CMsgGCQuestDiscard_Request{} }
func (m *CMsgGCQuestDiscard_Request) String() string            { return proto.CompactTextString(m) }
func (*CMsgGCQuestDiscard_Request) ProtoMessage()               {}
func (*CMsgGCQuestDiscard_Request) Descriptor() ([]byte, []int) { return econ_fileDescriptor0, []int{30} }

func (m *CMsgGCQuestDiscard_Request) GetQuestItemId() uint64 {
	if m != nil && m.QuestItemId != nil {
		return *m.QuestItemId
	}
	return 0
}

func init() {
	proto.RegisterType((*CMsgApplyAutograph)(nil), "CMsgApplyAutograph")
	proto.RegisterType((*CMsgEconPlayerStrangeCountAdjustment)(nil), "CMsgEconPlayerStrangeCountAdjustment")
	proto.RegisterType((*CMsgEconPlayerStrangeCountAdjustment_CStrangeCountAdjustment)(nil), "CMsgEconPlayerStrangeCountAdjustment.CStrangeCountAdjustment")
	proto.RegisterType((*CMsgRequestItemPurgatory_FinalizePurchase)(nil), "CMsgRequestItemPurgatory_FinalizePurchase")
	proto.RegisterType((*CMsgRequestItemPurgatory_FinalizePurchaseResponse)(nil), "CMsgRequestItemPurgatory_FinalizePurchaseResponse")
	proto.RegisterType((*CMsgRequestItemPurgatory_RefundPurchase)(nil), "CMsgRequestItemPurgatory_RefundPurchase")
	proto.RegisterType((*CMsgRequestItemPurgatory_RefundPurchaseResponse)(nil), "CMsgRequestItemPurgatory_RefundPurchaseResponse")
	proto.RegisterType((*CMsgCraftingResponse)(nil), "CMsgCraftingResponse")
	proto.RegisterType((*CMsgGCRequestStoreSalesData)(nil), "CMsgGCRequestStoreSalesData")
	proto.RegisterType((*CMsgGCRequestStoreSalesDataResponse)(nil), "CMsgGCRequestStoreSalesDataResponse")
	proto.RegisterType((*CMsgGCRequestStoreSalesDataResponse_Price)(nil), "CMsgGCRequestStoreSalesDataResponse.Price")
	proto.RegisterType((*CMsgGCRequestStoreSalesDataUpToDateResponse)(nil), "CMsgGCRequestStoreSalesDataUpToDateResponse")
	proto.RegisterType((*CMsgGCToGCPingRequest)(nil), "CMsgGCToGCPingRequest")
	proto.RegisterType((*CMsgGCToGCPingResponse)(nil), "CMsgGCToGCPingResponse")
	proto.RegisterType((*CMsgGCToGCGetUserSessionServer)(nil), "CMsgGCToGCGetUserSessionServer")
	proto.RegisterType((*CMsgGCToGCGetUserSessionServerResponse)(nil), "CMsgGCToGCGetUserSessionServerResponse")
	proto.RegisterType((*CMsgGCToGCGetUserServerMembers)(nil), "CMsgGCToGCGetUserServerMembers")
	proto.RegisterType((*CMsgGCToGCGetUserServerMembersResponse)(nil), "CMsgGCToGCGetUserServerMembersResponse")
	proto.RegisterType((*CMsgLookupMultipleAccountNames)(nil), "CMsgLookupMultipleAccountNames")
	proto.RegisterType((*CMsgLookupMultipleAccountNamesResponse)(nil), "CMsgLookupMultipleAccountNamesResponse")
	proto.RegisterType((*CMsgLookupMultipleAccountNamesResponse_Account)(nil), "CMsgLookupMultipleAccountNamesResponse.Account")
	proto.RegisterType((*CMsgGCToGCGrantSelfMadeItemToAccount)(nil), "CMsgGCToGCGrantSelfMadeItemToAccount")
	proto.RegisterType((*CMsgGCToGCThankedByNewUser)(nil), "CMsgGCToGCThankedByNewUser")
	proto.RegisterType((*CMsgGCShuffleCrateContents)(nil), "CMsgGCShuffleCrateContents")
	proto.RegisterType((*CMsgGCQuestObjective_Progress)(nil), "CMsgGCQuestObjective_Progress")
	proto.RegisterType((*CMsgGCQuestObjective_PointsChange)(nil), "CMsgGCQuestObjective_PointsChange")
	proto.RegisterType((*CMsgGCQuestObjective_PointsChangeResponse)(nil), "CMsgGCQuestObjective_PointsChangeResponse")
	proto.RegisterType((*CMsgGCQuestComplete_Request)(nil), "CMsgGCQuestComplete_Request")
	proto.RegisterType((*CMsgGCQuestCompleted)(nil), "CMsgGCQuestCompleted")
	proto.RegisterType((*CMsgGCQuestObjective_RequestLoanerItems)(nil), "CMsgGCQuestObjective_RequestLoanerItems")
	proto.RegisterType((*CMsgGCQuestObjective_RequestLoanerResponse)(nil), "CMsgGCQuestObjective_RequestLoanerResponse")
	proto.RegisterType((*CMsgCraftCollectionUpgrade)(nil), "CMsgCraftCollectionUpgrade")
	proto.RegisterType((*CMsgCraftHalloweenOffering)(nil), "CMsgCraftHalloweenOffering")
	proto.RegisterType((*CMsgGCQuestDiscard_Request)(nil), "CMsgGCQuestDiscard_Request")
	proto.RegisterEnum("EGCItemMsg", EGCItemMsg_name, EGCItemMsg_value)
	proto.RegisterEnum("EGCMsgResponse", EGCMsgResponse_name, EGCMsgResponse_value)
	proto.RegisterEnum("EUnlockStyle", EUnlockStyle_name, EUnlockStyle_value)
	proto.RegisterEnum("EItemPurgatoryResponse_Finalize", EItemPurgatoryResponse_Finalize_name, EItemPurgatoryResponse_Finalize_value)
	proto.RegisterEnum("EItemPurgatoryResponse_Refund", EItemPurgatoryResponse_Refund_name, EItemPurgatoryResponse_Refund_value)
}

func init() { proto.RegisterFile("econ_gcmessages.proto", econ_fileDescriptor0) }

var econ_fileDescriptor0 = []byte{
	// 3559 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x3a, 0x69, 0x70, 0x1c, 0xc5,
	0xb9, 0x48, 0xb2, 0xbc, 0xe3, 0x96, 0xd6, 0x6e, 0x66, 0xd7, 0x07, 0x32, 0xe6, 0x58, 0x83, 0x31,
	0xc2, 0xc8, 0xcf, 0xe6, 0x41, 0xf1, 0x78, 0x8f, 0xe2, 0x49, 0xbb, 0x92, 0xac, 0xb2, 0x65, 0x89,
	0x5d, 0x19, 0xde, 0xbf, 0xad, 0xd1, 0x4c, 0xaf, 0x34, 0x68, 0x76, 0x66, 0x99, 0x99, 0x95, 0xb4,
	0xef, 0x97, 0xe1, 0x3d, 0xce, 0x9c, 0xe4, 0xaa, 0x4a, 0xc8, 0x9d, 0x70, 0x84, 0x90, 0x93, 0x4a,
	0x42, 0xee, 0x40, 0x38, 0x42, 0x0a, 0x48, 0x80, 0x24, 0x55, 0x49, 0x20, 0xa4, 0x2a, 0xe1, 0x3e,
	0x13, 0x92, 0x5f, 0x5c, 0xf9, 0xba, 0x7b, 0xa6, 0xd5, 0xbd, 0x3b, 0xbb, 0xda, 0xfc, 0xc9, 0x0f,
	0x97, 0x35, 0x5f, 0x7f, 0xfd, 0xdd, 0x57, 0x77, 0x2f, 0xda, 0x4a, 0x4c, 0xcf, 0x2d, 0x2f, 0x98,
	0x55, 0x12, 0x04, 0xc6, 0x02, 0x09, 0x46, 0x6a, 0xbe, 0x17, 0x7a, 0x43, 0x99, 0x20, 0x24, 0x46,
	0x55, 0x05, 0xe6, 0xe6, 0x91, 0x9e, 0x9f, 0x0e, 0x16, 0x46, 0x6b, 0x35, 0xa7, 0x31, 0x5a, 0x0f,
	0xbd, 0x05, 0xdf, 0xa8, 0x2d, 0xea, 0xc3, 0xe8, 0x44, 0x23, 0xfe, 0x28, 0xdb, 0x21, 0xa9, 0x96,
	0x6d, 0x6b, 0x47, 0xcf, 0x69, 0x3d, 0x7b, 0x37, 0x14, 0xb7, 0x88, 0x85, 0x29, 0x80, 0x4f, 0x59,
	0xfa, 0x69, 0x68, 0x90, 0x63, 0x44, 0x68, 0xbd, 0x0c, 0x0d, 0xd1, 0x4f, 0x8e, 0x91, 0xbb, 0xab,
	0x17, 0x9d, 0x41, 0x99, 0x8c, 0x83, 0x58, 0xb3, 0x8e, 0xd1, 0x20, 0x7e, 0x29, 0xf4, 0x0d, 0x77,
	0x81, 0xe4, 0xbd, 0xba, 0x1b, 0x8e, 0x5a, 0x57, 0xd4, 0x83, 0xb0, 0x4a, 0xdc, 0x50, 0xdf, 0x85,
	0x90, 0x61, 0x9a, 0x14, 0x18, 0xf3, 0x4b, 0x17, 0x37, 0x45, 0x10, 0xe0, 0xd4, 0x40, 0x27, 0x05,
	0x7c, 0x63, 0x99, 0x23, 0x19, 0x62, 0x6b, 0x00, 0x6c, 0xfb, 0xf6, 0x0e, 0x1c, 0xbc, 0x78, 0xa4,
	0x1b, 0x46, 0x23, 0xf9, 0x64, 0x78, 0x71, 0x7b, 0x90, 0x08, 0x0f, 0x86, 0xae, 0x44, 0xdb, 0xf3,
	0xed, 0x85, 0x26, 0xcb, 0xf0, 0x47, 0x39, 0x6c, 0xd4, 0x48, 0x2c, 0x34, 0x83, 0xcc, 0x01, 0x40,
	0xdf, 0x8e, 0x52, 0xaa, 0x65, 0x36, 0xda, 0xdc, 0x6e, 0xa7, 0x80, 0xb2, 0x82, 0xca, 0x8e, 0x3e,
	0xb6, 0x4f, 0x82, 0xe4, 0x26, 0xd0, 0xd9, 0x54, 0x97, 0x22, 0xb9, 0xb2, 0x4e, 0x82, 0x90, 0x9a,
	0x72, 0xb6, 0xee, 0x2f, 0x18, 0xa1, 0xe7, 0x37, 0xca, 0x13, 0xb6, 0x6b, 0x38, 0xf6, 0xff, 0x12,
	0x80, 0x98, 0x8b, 0x46, 0x40, 0xf4, 0x93, 0x90, 0x16, 0x71, 0x09, 0x40, 0x84, 0x3e, 0x60, 0x93,
	0xe2, 0x6c, 0x82, 0xdc, 0x61, 0x74, 0xa0, 0x6b, 0x3a, 0x45, 0x12, 0xd4, 0x3c, 0x17, 0xe8, 0x6d,
	0x43, 0x1b, 0x7d, 0x12, 0xd4, 0x9d, 0x30, 0x52, 0x28, 0xfa, 0xca, 0x8d, 0xa1, 0xb3, 0xda, 0x12,
	0x2b, 0x92, 0x4a, 0xdd, 0xb5, 0x84, 0x48, 0x92, 0xe2, 0x3d, 0xb2, 0xe2, 0xb9, 0x29, 0xb4, 0xbf,
	0x4b, 0x1a, 0xeb, 0x8a, 0x73, 0x00, 0x65, 0x29, 0xa9, 0xbc, 0x6f, 0x54, 0x42, 0xdb, 0x5d, 0x10,
	0xf8, 0x1d, 0xcc, 0x51, 0x42, 0x3b, 0xe9, 0x96, 0xc9, 0x7c, 0xc4, 0xbf, 0x04, 0x7c, 0x49, 0xc9,
	0x70, 0x48, 0x50, 0x30, 0x42, 0x43, 0xdf, 0x81, 0x52, 0xcb, 0xc4, 0x0f, 0x6c, 0xcf, 0x8d, 0x58,
	0xc5, 0x9f, 0xfa, 0x10, 0xd2, 0xcc, 0xba, 0xef, 0x13, 0xd7, 0x6c, 0x30, 0x4f, 0xa6, 0x8b, 0xe2,
	0x3b, 0xf7, 0x4a, 0x0f, 0xda, 0xdd, 0x81, 0xaa, 0x90, 0x6b, 0x0a, 0xa1, 0x00, 0x80, 0xe5, 0x9a,
	0x6f, 0x9b, 0x84, 0x49, 0x36, 0x70, 0x70, 0x78, 0xa4, 0x8b, 0x9d, 0x23, 0xb3, 0x74, 0x47, 0x71,
	0x13, 0xdd, 0xcd, 0xfe, 0x94, 0x05, 0xed, 0x55, 0x05, 0x3d, 0x0b, 0x6d, 0x21, 0xab, 0x35, 0xdb,
	0x37, 0x42, 0xf8, 0x2a, 0x87, 0x76, 0x95, 0x44, 0xd1, 0xb5, 0x79, 0x0d, 0x3c, 0x07, 0xd0, 0xa1,
	0x0b, 0x51, 0x3f, 0xa7, 0x15, 0x9b, 0xcb, 0x22, 0x95, 0x58, 0x6b, 0xfa, 0x5d, 0x20, 0x15, 0x3d,
	0x8b, 0xfa, 0xb9, 0xb0, 0x9c, 0x09, 0xff, 0xc8, 0xd5, 0xd0, 0x39, 0x1d, 0x84, 0x3e, 0x56, 0x9b,
	0xf3, 0xe0, 0xff, 0x35, 0xf7, 0xb5, 0x37, 0x6a, 0x82, 0xac, 0xbd, 0x49, 0xb2, 0xe6, 0xb6, 0xa3,
	0xad, 0x9c, 0xe3, 0x9c, 0x37, 0x99, 0x9f, 0x65, 0xbe, 0x66, 0x9c, 0x73, 0x3b, 0xd0, 0xb6, 0xe6,
	0x05, 0xce, 0x35, 0x77, 0x09, 0x3a, 0x65, 0x6d, 0x65, 0x92, 0x84, 0xc7, 0x02, 0xa8, 0x07, 0x50,
	0xfd, 0x80, 0x64, 0x89, 0xf8, 0x20, 0xc1, 0x3a, 0xf5, 0x26, 0x37, 0x8b, 0xf6, 0x74, 0x26, 0x20,
	0x14, 0xdc, 0x83, 0xb6, 0x04, 0x0c, 0x52, 0x66, 0x35, 0x36, 0xa6, 0xb6, 0xb1, 0x98, 0xe6, 0xe0,
	0x12, 0x85, 0x02, 0xc5, 0x4a, 0xa2, 0x48, 0x14, 0x63, 0x9a, 0x54, 0xe7, 0xc1, 0x26, 0xeb, 0x95,
	0xc0, 0x33, 0xd1, 0xe6, 0xaa, 0xb1, 0x5a, 0x0e, 0x6a, 0xc4, 0x0c, 0x69, 0xc6, 0x04, 0x91, 0xb9,
	0xd2, 0x00, 0x2d, 0x09, 0x60, 0x6e, 0x2e, 0x51, 0x72, 0x89, 0x8f, 0x90, 0x1c, 0x2a, 0x7d, 0x95,
	0x81, 0xca, 0x0a, 0xdb, 0x3e, 0xa0, 0xb9, 0x85, 0x2f, 0x8c, 0x0a, 0x7b, 0x14, 0xb8, 0xf4, 0x47,
	0x3c, 0x6f, 0xa9, 0x5e, 0x9b, 0x86, 0xfc, 0xb3, 0x6b, 0x0e, 0x89, 0x96, 0x8f, 0x1a, 0xd0, 0x58,
	0xf4, 0x9c, 0x90, 0x3e, 0xce, 0xbc, 0xf4, 0x58, 0x2f, 0xee, 0x29, 0x4a, 0xd0, 0xdc, 0xdd, 0x3d,
	0x5c, 0xb8, 0xf6, 0x64, 0x84, 0x70, 0x87, 0x91, 0x16, 0x6d, 0x0c, 0xa2, 0x64, 0xd9, 0x3f, 0xd2,
	0xdd, 0xd6, 0x91, 0x08, 0x58, 0x14, 0x04, 0x86, 0x46, 0x51, 0x2a, 0x02, 0xea, 0x27, 0xa3, 0x4d,
	0x42, 0xa0, 0x26, 0x1b, 0xdb, 0x16, 0x8d, 0xd6, 0x1a, 0x98, 0xc8, 0x73, 0x0d, 0x66, 0xdc, 0x4d,
	0xc5, 0xf8, 0x33, 0x77, 0x05, 0xef, 0x63, 0x91, 0x59, 0xa1, 0x1b, 0x84, 0x25, 0xe2, 0x54, 0xa6,
	0x0d, 0x8b, 0xd0, 0x2a, 0x36, 0xe7, 0xc5, 0xf4, 0xcf, 0x40, 0x9b, 0xe3, 0x7c, 0x2a, 0xdb, 0xae,
	0x45, 0x56, 0x23, 0x26, 0x83, 0x51, 0x56, 0x4d, 0x51, 0x98, 0x2a, 0x45, 0x6f, 0x93, 0x14, 0xb9,
	0xe3, 0x3d, 0x68, 0x68, 0x8d, 0xd9, 0xdc, 0xa2, 0xe1, 0x2e, 0x11, 0x6b, 0xac, 0x71, 0x94, 0xac,
	0x50, 0x67, 0xea, 0xfb, 0x90, 0xee, 0x92, 0x95, 0x72, 0x3d, 0x58, 0xf3, 0x9c, 0xd0, 0x05, 0xbb,
	0x1c, 0x69, 0x54, 0xa8, 0xf4, 0xef, 0x68, 0x5b, 0xc8, 0x29, 0x34, 0xef, 0xe0, 0x7c, 0xb3, 0xd1,
	0xaa, 0xb2, 0x0b, 0xd4, 0x8d, 0x24, 0x28, 0x2d, 0xd6, 0x2b, 0x15, 0x87, 0x40, 0x99, 0x0d, 0xa1,
	0xfd, 0xb9, 0x21, 0x6d, 0x89, 0xe0, 0xeb, 0xb4, 0x49, 0x01, 0x4d, 0xf3, 0xc1, 0x00, 0x03, 0x46,
	0xb3, 0xc1, 0x5e, 0x84, 0x19, 0x3f, 0xd3, 0xb3, 0x08, 0xa4, 0x86, 0x0f, 0xe9, 0x19, 0xd9, 0x74,
	0x33, 0x85, 0xe7, 0x01, 0x5c, 0x62, 0xd0, 0xdc, 0x9d, 0x3d, 0x68, 0x17, 0x67, 0x76, 0x29, 0x4d,
	0xeb, 0x99, 0xf9, 0x2b, 0x20, 0x98, 0xed, 0x65, 0x52, 0x9e, 0xf5, 0x61, 0xda, 0x80, 0xa4, 0xa3,
	0xfc, 0x58, 0xc6, 0x37, 0xf3, 0x13, 0x5d, 0x04, 0xf8, 0x81, 0x55, 0x38, 0x8e, 0x11, 0x02, 0xd9,
	0xf9, 0xc8, 0xf8, 0x5c, 0x47, 0xcc, 0x56, 0x46, 0xd9, 0x02, 0x77, 0x00, 0xd4, 0x36, 0x8b, 0x38,
	0xa1, 0x11, 0x95, 0x47, 0xfe, 0xa1, 0xef, 0x46, 0x69, 0x6f, 0xc5, 0x8d, 0x53, 0x19, 0xf8, 0x6c,
	0x60, 0x99, 0x3c, 0xc8, 0x80, 0x25, 0x0e, 0xa3, 0x05, 0xff, 0xf4, 0x64, 0x71, 0x3d, 0x1b, 0x8c,
	0x93, 0x5f, 0xa4, 0x93, 0x42, 0x57, 0x22, 0x43, 0x05, 0x0c, 0x42, 0xc3, 0xb5, 0x0c, 0xdf, 0x2a,
	0xd7, 0xd8, 0xe6, 0xb8, 0x02, 0xc6, 0x60, 0x4e, 0x52, 0x3f, 0x1d, 0x0d, 0xce, 0x7b, 0x6e, 0x3d,
	0x88, 0xb1, 0xb8, 0xd0, 0x03, 0x0c, 0x16, 0xa1, 0x74, 0x23, 0xba, 0x7e, 0x1e, 0xd2, 0xeb, 0x35,
	0x8b, 0x3a, 0x6e, 0x1e, 0x5a, 0x6c, 0x4c, 0xad, 0x1f, 0x30, 0xb5, 0x8b, 0xfa, 0x2b, 0x86, 0x03,
	0x6d, 0x17, 0x73, 0x84, 0x31, 0x58, 0xe7, 0x94, 0x73, 0x0f, 0xf5, 0xf0, 0x69, 0xa4, 0xa3, 0xbe,
	0x22, 0x6f, 0xff, 0xd5, 0x7a, 0xef, 0x4b, 0x54, 0x89, 0x2a, 0xaf, 0x25, 0xe8, 0x32, 0x1a, 0x4f,
	0x00, 0x4c, 0x95, 0xbc, 0x57, 0x85, 0x1a, 0x02, 0x5b, 0xa3, 0x86, 0xd2, 0x8d, 0xf0, 0xb9, 0x6d,
	0x7c, 0xee, 0x68, 0x22, 0x61, 0xe5, 0xa6, 0xf9, 0x78, 0xd4, 0x62, 0xa5, 0x88, 0xf6, 0x11, 0xcf,
	0x00, 0x47, 0x50, 0x1a, 0x5d, 0x85, 0x73, 0x6e, 0x1f, 0x1a, 0x5e, 0x9f, 0x9c, 0xe8, 0x77, 0xe7,
	0xf3, 0x74, 0x65, 0xc3, 0x50, 0xde, 0x73, 0x1c, 0x8a, 0xec, 0xb9, 0xc7, 0x6a, 0x30, 0xac, 0x5b,
	0x4d, 0xe3, 0x58, 0x9f, 0x34, 0x8e, 0x1d, 0x95, 0xb6, 0x1d, 0x32, 0x1c, 0xc7, 0x5b, 0x21, 0xc4,
	0x9d, 0xa9, 0x54, 0x08, 0xcd, 0x4b, 0xba, 0x2d, 0xf4, 0x3c, 0x47, 0x9a, 0xe2, 0xe8, 0x27, 0xf8,
	0x4f, 0x99, 0x6b, 0x65, 0x7a, 0xff, 0x1d, 0x57, 0x0d, 0x26, 0x74, 0xc1, 0x0e, 0x4c, 0xea, 0xe2,
	0x7f, 0xc2, 0xba, 0xc3, 0x77, 0xef, 0x47, 0x68, 0x7c, 0x32, 0x4f, 0xbf, 0x80, 0x90, 0x7e, 0x22,
	0x1a, 0x5c, 0x2a, 0x8f, 0x33, 0x92, 0xd4, 0x8b, 0xf8, 0xf9, 0x14, 0x50, 0xd9, 0x15, 0x83, 0x4a,
	0x24, 0x2c, 0x81, 0xa0, 0x0e, 0x2b, 0x39, 0xb3, 0x5e, 0x60, 0x53, 0xa5, 0xf1, 0x0b, 0x29, 0x5d,
	0x47, 0xe9, 0x18, 0x87, 0xe9, 0x86, 0x5f, 0x4c, 0xc1, 0x0c, 0xb7, 0x55, 0x81, 0xc5, 0xb6, 0xc3,
	0x2f, 0xa5, 0xf4, 0x0c, 0xda, 0x1c, 0xaf, 0x15, 0x08, 0x75, 0x27, 0x7e, 0x39, 0x05, 0x95, 0xfc,
	0xd4, 0x18, 0x78, 0x19, 0x18, 0xa4, 0xd2, 0xc8, 0x1b, 0xe6, 0x22, 0x29, 0xd5, 0xe7, 0x03, 0xd3,
	0xb7, 0x6b, 0x8c, 0xd5, 0x2b, 0x29, 0x7d, 0x2b, 0xc2, 0x31, 0x16, 0xed, 0x42, 0x54, 0x12, 0xfc,
	0x6a, 0x0a, 0x1a, 0x49, 0x26, 0x06, 0x1f, 0x73, 0x1d, 0xcf, 0x5c, 0x62, 0x05, 0x14, 0xbf, 0x96,
	0x82, 0x33, 0xd3, 0xce, 0x84, 0x15, 0x21, 0xcd, 0xeb, 0x29, 0x98, 0x78, 0x4f, 0x8c, 0x31, 0x66,
	0x0d, 0x08, 0x5b, 0x46, 0xf3, 0x2f, 0x29, 0x38, 0x35, 0x9c, 0xd4, 0x02, 0x17, 0xfb, 0xfe, 0xaa,
	0x58, 0x66, 0xd2, 0x73, 0x2c, 0xe2, 0x5e, 0x4e, 0x27, 0xd4, 0xc5, 0x31, 0xdf, 0x33, 0x2c, 0xd3,
	0x08, 0x42, 0xfc, 0x86, 0x22, 0xd7, 0xf4, 0xcc, 0x5c, 0x21, 0x72, 0x0d, 0xfe, 0x9b, 0x22, 0x97,
	0xb4, 0x22, 0xe8, 0xff, 0x3d, 0x05, 0xa3, 0x62, 0x56, 0x56, 0x95, 0x3a, 0x84, 0x89, 0xf6, 0x66,
	0x0a, 0x12, 0xf5, 0xe4, 0xa4, 0x25, 0xb1, 0xfb, 0xad, 0x14, 0xf4, 0x83, 0xdd, 0x31, 0x4a, 0x91,
	0x54, 0xbd, 0x65, 0x52, 0x02, 0xdd, 0x09, 0x53, 0xa2, 0x5c, 0x18, 0x9f, 0x2d, 0x8e, 0xe7, 0x47,
	0xe7, 0xc6, 0x0b, 0xf8, 0xed, 0x94, 0xfe, 0x6f, 0xe8, 0x9c, 0x76, 0x98, 0x31, 0x41, 0x79, 0xc7,
	0x3b, 0x0a, 0xfb, 0x3c, 0x9c, 0xa1, 0xbc, 0x2a, 0x9c, 0x6b, 0x58, 0x5b, 0x26, 0xab, 0x61, 0xdd,
	0x27, 0xf8, 0xdd, 0x94, 0x7e, 0x36, 0x3a, 0xa3, 0x13, 0x8a, 0x90, 0xf4, 0xb8, 0xa6, 0xef, 0x44,
	0xdb, 0x84, 0x87, 0x62, 0x3d, 0xb8, 0x99, 0xae, 0xd2, 0xa0, 0x73, 0x6f, 0x6f, 0x59, 0x8c, 0xb6,
	0x5e, 0xad, 0xc1, 0x8c, 0x76, 0xda, 0x9a, 0xe8, 0x41, 0xcd, 0x58, 0x71, 0x21, 0x2c, 0x69, 0xb2,
	0x5a, 0x5e, 0x3d, 0xe4, 0x95, 0x12, 0x5f, 0xa3, 0x70, 0xe0, 0x1a, 0x52, 0x3a, 0xd4, 0x70, 0xf8,
	0x5a, 0x85, 0xc3, 0xda, 0x22, 0x73, 0x38, 0xbe, 0x4e, 0x93, 0x9d, 0x30, 0x69, 0x57, 0xc2, 0xcb,
	0xe1, 0x34, 0xce, 0x9c, 0x70, 0xbd, 0x26, 0x5b, 0x41, 0x5e, 0x12, 0xf2, 0xdd, 0xa0, 0xc9, 0xee,
	0x87, 0x40, 0x87, 0x7a, 0xe2, 0x53, 0x4c, 0x7c, 0xa3, 0x26, 0xbb, 0x47, 0x5a, 0x89, 0xf7, 0x16,
	0x89, 0x49, 0x28, 0x0c, 0xbf, 0x57, 0x93, 0xc3, 0xf0, 0x98, 0xbb, 0x02, 0x4c, 0x38, 0x22, 0xb7,
	0xd0, 0xfb, 0x34, 0xfd, 0x54, 0x34, 0x94, 0xb4, 0x1e, 0x09, 0xf1, 0x7e, 0x45, 0x85, 0x12, 0x77,
	0x6b, 0x29, 0x6c, 0x38, 0x04, 0x7f, 0x40, 0xa5, 0x1d, 0x10, 0x2b, 0xef, 0x18, 0x76, 0x95, 0x4e,
	0x0a, 0x4c, 0xc5, 0x0f, 0x6a, 0x72, 0x6a, 0x94, 0x3c, 0x9f, 0xed, 0x0d, 0xf0, 0x4d, 0x1a, 0x8c,
	0xb2, 0x67, 0xc6, 0x70, 0x28, 0x37, 0xcb, 0x9e, 0xb3, 0x0c, 0x75, 0x01, 0x46, 0xc5, 0xf0, 0x88,
	0x0d, 0xf5, 0x46, 0x0a, 0x96, 0x0f, 0x69, 0x72, 0x21, 0xe0, 0xc3, 0x64, 0x34, 0xf5, 0xe0, 0x0f,
	0x6b, 0x72, 0x0a, 0x29, 0x6b, 0x42, 0xfc, 0x8f, 0x28, 0x32, 0x2a, 0x38, 0xcc, 0x7f, 0x1f, 0xd5,
	0xe0, 0x40, 0x70, 0x7a, 0xdb, 0x75, 0x41, 0xe7, 0x63, 0x1a, 0x8c, 0xfb, 0x3b, 0x84, 0xae, 0xac,
	0x4f, 0x31, 0x4b, 0x40, 0x89, 0xa9, 0x1a, 0xf8, 0xe3, 0x9a, 0x5c, 0x7e, 0xe2, 0xe3, 0xb2, 0x4b,
	0x6f, 0x16, 0xe0, 0xa8, 0x0c, 0x27, 0x65, 0x18, 0x8b, 0x16, 0xf1, 0x27, 0x34, 0x39, 0x6b, 0x79,
	0xb0, 0xf0, 0xe0, 0x8e, 0x03, 0xff, 0x66, 0xad, 0x35, 0xef, 0x14, 0x0c, 0x21, 0xd0, 0x27, 0x15,
	0x81, 0x38, 0xe6, 0xb4, 0xb1, 0x04, 0xd3, 0xef, 0xb4, 0xe1, 0x2f, 0xe1, 0x4f, 0x35, 0xc5, 0xb6,
	0xba, 0x2c, 0xa8, 0x7c, 0x5a, 0x83, 0x41, 0xe4, 0x14, 0x15, 0xed, 0x98, 0x6b, 0x83, 0xf8, 0xac,
	0xe6, 0xb2, 0xd9, 0x0b, 0x7f, 0x46, 0xd3, 0xcf, 0x41, 0x7b, 0x3a, 0x23, 0x09, 0x8a, 0x9f, 0x55,
	0xb2, 0xa5, 0x64, 0xac, 0xae, 0x36, 0xd6, 0x0a, 0xda, 0xe7, 0x94, 0xa0, 0x1f, 0x33, 0xcc, 0xa5,
	0x1a, 0xfc, 0xa3, 0x91, 0x31, 0x61, 0xbb, 0x76, 0xb0, 0x48, 0x2c, 0xfc, 0x79, 0xc5, 0x92, 0xfc,
	0xee, 0x86, 0x1a, 0x7a, 0xfc, 0xca, 0xba, 0x5d, 0xab, 0x11, 0xab, 0x14, 0xd2, 0xba, 0xfc, 0x05,
	0x25, 0x35, 0xa2, 0x0e, 0xca, 0x82, 0xee, 0x16, 0xc5, 0x2e, 0x14, 0x34, 0x6a, 0x2e, 0xb9, 0xde,
	0x8a, 0x43, 0xac, 0x05, 0x20, 0x7f, 0xab, 0x26, 0x57, 0x96, 0x59, 0x70, 0x0b, 0x09, 0x83, 0x32,
	0x1c, 0x0d, 0x60, 0x3f, 0xff, 0x9a, 0xf0, 0x7c, 0x08, 0xe3, 0x20, 0xc0, 0xb7, 0x29, 0x92, 0xac,
	0xa1, 0x86, 0x4a, 0xf7, 0xba, 0x5d, 0xc9, 0x0f, 0x08, 0xe6, 0x1a, 0x68, 0x33, 0x3a, 0x0f, 0x23,
	0x33, 0xfe, 0x92, 0xa2, 0xad, 0xbc, 0x24, 0xac, 0x75, 0x87, 0xa6, 0x8f, 0xa0, 0xb3, 0xbb, 0x11,
	0x07, 0x76, 0x3b, 0x0d, 0xfc, 0x65, 0xad, 0xb9, 0x74, 0xb3, 0x4a, 0xe4, 0x85, 0x76, 0xc5, 0x36,
	0xd9, 0x09, 0x1c, 0xdf, 0xa9, 0x44, 0x74, 0xde, 0xb1, 0x21, 0x06, 0xa1, 0xb3, 0xd7, 0x1c, 0xa3,
	0xa1, 0xe0, 0x7d, 0x45, 0x31, 0x14, 0xbb, 0x54, 0x8c, 0x6e, 0xcd, 0x66, 0x0d, 0x3f, 0xc4, 0x5f,
	0x55, 0x0c, 0x55, 0x9e, 0x72, 0x4d, 0x9f, 0xd0, 0xbb, 0xae, 0xc3, 0xb6, 0xe3, 0xf0, 0x6b, 0x35,
	0x36, 0x9d, 0xd7, 0xc1, 0x19, 0x5f, 0x53, 0x82, 0x36, 0x01, 0x55, 0xa8, 0xfb, 0x75, 0x25, 0x1b,
	0xa3, 0x66, 0x21, 0x31, 0xfd, 0x86, 0x52, 0x8d, 0x8a, 0x54, 0xff, 0x68, 0xb9, 0x64, 0x7a, 0x60,
	0x0e, 0xfc, 0x4d, 0xc5, 0xef, 0xb4, 0x50, 0x11, 0x8b, 0x17, 0x95, 0xbb, 0x5a, 0xd5, 0x89, 0xc6,
	0xa9, 0x3c, 0xcc, 0x34, 0xf8, 0x5b, 0x09, 0x9c, 0xe5, 0xf5, 0x6f, 0xab, 0x61, 0x27, 0x59, 0x03,
	0xa4, 0x00, 0x45, 0xd9, 0x7c, 0x86, 0xbf, 0xa3, 0x60, 0x71, 0xdb, 0x46, 0xc9, 0x4e, 0xd3, 0x8a,
	0x84, 0xf4, 0x4a, 0x05, 0xdf, 0xad, 0xc1, 0x94, 0x7b, 0xd6, 0x3a, 0x58, 0xc2, 0x26, 0xdf, 0x55,
	0x54, 0x62, 0x9c, 0xff, 0x07, 0xbc, 0x04, 0xb5, 0xfb, 0x7b, 0x4a, 0xb9, 0x90, 0x56, 0xc4, 0xde,
	0xef, 0xab, 0x96, 0x9f, 0xf3, 0x21, 0x9b, 0x78, 0x66, 0xf2, 0x2b, 0x55, 0xe8, 0x42, 0xfe, 0x38,
	0x2d, 0x42, 0xf8, 0x07, 0x4a, 0xcd, 0x9d, 0xa8, 0x3b, 0x15, 0x70, 0x4e, 0xa1, 0xe1, 0xc2, 0x31,
	0xc3, 0x84, 0x66, 0x61, 0xd7, 0x08, 0x9d, 0x8c, 0x3d, 0x97, 0xe2, 0xfe, 0x50, 0xd3, 0x0f, 0xa2,
	0x73, 0xbb, 0xc2, 0x15, 0x92, 0xfc, 0x48, 0x91, 0x24, 0x4a, 0x92, 0x71, 0x98, 0x4c, 0xcd, 0x10,
	0x86, 0xb1, 0x10, 0x82, 0xce, 0x81, 0x39, 0x15, 0xfc, 0x89, 0x7f, 0xac, 0xc4, 0x27, 0x60, 0x1e,
	0x32, 0x42, 0x8e, 0x08, 0x1d, 0xe4, 0x10, 0x31, 0xac, 0x19, 0xdf, 0x5e, 0xb0, 0x5d, 0xfc, 0x13,
	0x25, 0x16, 0x18, 0x39, 0xc8, 0x7c, 0xd0, 0xdd, 0x5c, 0x34, 0xfc, 0x05, 0x30, 0xcf, 0x3d, 0x1a,
	0x1c, 0x4c, 0x72, 0xed, 0x11, 0x84, 0x6c, 0xf7, 0xb6, 0xda, 0x31, 0x1e, 0x78, 0x22, 0x4b, 0xff,
	0x54, 0xa9, 0x96, 0x0c, 0x83, 0x25, 0x1d, 0x18, 0xd4, 0x0d, 0xaa, 0x70, 0xa8, 0xe5, 0x68, 0xf7,
	0x29, 0x4a, 0x32, 0x34, 0x31, 0x85, 0x97, 0x6a, 0xc4, 0x71, 0xe6, 0xa1, 0x7f, 0xcc, 0x1a, 0x30,
	0x33, 0xdc, 0x9f, 0x50, 0x9d, 0x69, 0x3a, 0x40, 0x4c, 0x11, 0x63, 0x09, 0x3f, 0x90, 0x50, 0x9d,
	0xd7, 0x96, 0x85, 0xe0, 0x0f, 0x2a, 0xe1, 0x36, 0x37, 0x41, 0x6f, 0x8d, 0x68, 0x02, 0x53, 0xc9,
	0xd7, 0x8a, 0xea, 0xcf, 0x14, 0x77, 0x75, 0xca, 0xd4, 0x72, 0x7c, 0x0d, 0x83, 0x1f, 0x52, 0x04,
	0x48, 0x18, 0x20, 0x26, 0xd9, 0xf4, 0xf0, 0x73, 0x45, 0x8d, 0xa6, 0xd2, 0x17, 0xe0, 0x87, 0x15,
	0x0f, 0xb4, 0xbf, 0xe9, 0xc1, 0x8f, 0x68, 0xfa, 0x7e, 0x34, 0xbc, 0x3e, 0xa2, 0xd0, 0xfc, 0x51,
	0x25, 0x29, 0xc0, 0x0d, 0x16, 0xcc, 0x07, 0xec, 0x44, 0xf1, 0xe4, 0x80, 0x5c, 0x97, 0xa2, 0x15,
	0x50, 0x1a, 0x44, 0x02, 0xef, 0xd3, 0x6f, 0x12, 0xcf, 0x36, 0x4f, 0x0d, 0xc8, 0x31, 0xdf, 0x06,
	0x35, 0x62, 0xf8, 0x87, 0x01, 0xb9, 0xb0, 0xc6, 0xb8, 0xd0, 0x6c, 0xfc, 0x30, 0xba, 0x46, 0xc4,
	0x4f, 0x0f, 0xc8, 0xe3, 0x86, 0x40, 0xe1, 0xab, 0x79, 0xc7, 0x83, 0xf9, 0x07, 0x3f, 0x93, 0x88,
	0x93, 0x37, 0x5c, 0x93, 0x38, 0x31, 0x9d, 0x67, 0x07, 0xf4, 0x03, 0x68, 0x5f, 0x37, 0x1a, 0x08,
	0xe9, 0x5e, 0x54, 0x94, 0xe6, 0xb7, 0x83, 0x10, 0x00, 0x2b, 0xf4, 0xbe, 0x66, 0xc2, 0x58, 0xf6,
	0x7c, 0x38, 0xa1, 0x71, 0x28, 0xbe, 0x67, 0x50, 0x56, 0x5a, 0x45, 0x1d, 0x73, 0xa0, 0x3e, 0x38,
	0x30, 0x61, 0x45, 0xb8, 0xf7, 0x0e, 0xca, 0x45, 0x31, 0xbe, 0x27, 0x75, 0x43, 0xc3, 0x09, 0x98,
	0xad, 0xbf, 0x98, 0x96, 0xa7, 0x03, 0xe6, 0x7b, 0x9f, 0x2c, 0xdb, 0x64, 0x25, 0xbf, 0x48, 0xa0,
	0x6d, 0x43, 0x27, 0xae, 0x07, 0xf8, 0x96, 0xb4, 0x9c, 0xcf, 0x12, 0x12, 0x5f, 0x17, 0x3a, 0xdc,
	0x9a, 0x6e, 0xce, 0xe7, 0x08, 0x2f, 0x76, 0xd7, 0x6d, 0xe9, 0xe6, 0x7c, 0x56, 0x11, 0x04, 0xa5,
	0xdb, 0xd3, 0xb2, 0xd8, 0x12, 0xe2, 0x38, 0xbd, 0x87, 0x86, 0xbe, 0x9b, 0x96, 0x4d, 0xd0, 0xb2,
	0xae, 0x74, 0xc1, 0x3b, 0xd2, 0x72, 0x03, 0x96, 0x70, 0x59, 0x8e, 0x79, 0xf5, 0x85, 0xc5, 0x50,
	0xed, 0xae, 0x8a, 0x16, 0x05, 0xb2, 0x5c, 0x3e, 0xca, 0x71, 0x63, 0x2d, 0x1e, 0xdb, 0x22, 0x6b,
	0xd1, 0x8a, 0x20, 0xb4, 0x78, 0x7c, 0x8b, 0x9a, 0x82, 0xcb, 0xe5, 0x02, 0x99, 0xaf, 0x2f, 0x14,
	0x61, 0x96, 0xa1, 0x83, 0x70, 0x4c, 0xef, 0x89, 0x2d, 0x4a, 0x0a, 0xd2, 0xcb, 0xfb, 0xe8, 0x92,
	0x98, 0xf5, 0x9a, 0xfb, 0x32, 0x32, 0x95, 0xe6, 0x65, 0xc1, 0xec, 0xfe, 0x8c, 0x12, 0x40, 0x14,
	0x2d, 0x7e, 0xb8, 0xa1, 0x81, 0x27, 0x4f, 0xdc, 0x0f, 0x64, 0xe4, 0xf0, 0x6c, 0x41, 0x4d, 0x3a,
	0xd1, 0x3d, 0x98, 0x51, 0x4e, 0xf9, 0xf2, 0x96, 0xf8, 0xd5, 0x0a, 0xff, 0x32, 0xa3, 0xc4, 0x65,
	0x12, 0x8e, 0x90, 0xf6, 0xb1, 0x8c, 0x5c, 0xb0, 0x15, 0x5c, 0x9e, 0x4a, 0xf8, 0xf1, 0x8c, 0xd2,
	0x6e, 0x5a, 0x31, 0x04, 0xad, 0x27, 0xda, 0xcb, 0x76, 0x69, 0x9d, 0xf8, 0x8d, 0xb9, 0x55, 0x17,
	0x3f, 0xdc, 0x5e, 0xb6, 0x18, 0x47, 0xd0, 0x7b, 0x24, 0xa3, 0xe4, 0x4c, 0xb3, 0x79, 0xf0, 0xa3,
	0x19, 0xa5, 0xbd, 0xb5, 0x33, 0x1f, 0xfe, 0x85, 0x42, 0x87, 0xde, 0x1b, 0x17, 0x6c, 0x3f, 0x6c,
	0x94, 0x0a, 0x33, 0xec, 0xda, 0x02, 0xff, 0x4a, 0xa1, 0x23, 0xd6, 0xe3, 0xaa, 0x29, 0xf0, 0x7e,
	0xad, 0xe8, 0x47, 0xf1, 0xf8, 0xe1, 0xa4, 0x74, 0xe9, 0x91, 0xc3, 0xa4, 0x71, 0x99, 0xe1, 0xd4,
	0x09, 0xfe, 0x8d, 0x62, 0x2d, 0x8a, 0x23, 0xba, 0x47, 0x1e, 0x84, 0xf1, 0x1c, 0xda, 0xd0, 0xab,
	0x86, 0x6b, 0xe1, 0xdf, 0x66, 0xe4, 0x32, 0xc8, 0x2b, 0xc2, 0x65, 0xfc, 0xfd, 0x87, 0x93, 0xb5,
	0xf0, 0xef, 0x32, 0xf2, 0x80, 0xaf, 0x3e, 0x46, 0xe3, 0xdf, 0x2b, 0xe1, 0x48, 0x39, 0x5d, 0x4e,
	0xe6, 0x47, 0x67, 0xa7, 0xa2, 0x22, 0xcf, 0x4f, 0xd4, 0x16, 0x7e, 0x52, 0x61, 0x13, 0x85, 0xfa,
	0xa8, 0xeb, 0x02, 0x8e, 0xc9, 0x7a, 0x57, 0x80, 0x9f, 0x52, 0x22, 0x36, 0x09, 0x65, 0xad, 0x76,
	0x67, 0xd4, 0x6e, 0xca, 0x50, 0x67, 0xa1, 0x7d, 0xd7, 0xa2, 0x23, 0x27, 0xbb, 0xfe, 0xc7, 0x4f,
	0x2b, 0x4c, 0xf9, 0x58, 0xd6, 0xa4, 0xdb, 0x1f, 0x33, 0xf2, 0x49, 0xa7, 0xf3, 0xfb, 0x2b, 0xfe,
	0x53, 0x46, 0x3f, 0x0f, 0x8d, 0x74, 0x87, 0x2c, 0x64, 0xfd, 0xb3, 0xa2, 0x56, 0xa7, 0x07, 0x55,
	0xfc, 0x8c, 0x92, 0x88, 0xdd, 0xbc, 0xbd, 0xe2, 0x67, 0x33, 0x72, 0x35, 0x63, 0xaf, 0x6c, 0x1d,
	0x9e, 0xd6, 0x03, 0xfc, 0x9c, 0x12, 0x3c, 0x89, 0x0f, 0x84, 0xf8, 0x79, 0x25, 0x39, 0x3a, 0xbe,
	0x7c, 0xe2, 0x17, 0x32, 0xf2, 0x28, 0xd2, 0xd5, 0x83, 0x23, 0x7e, 0x31, 0x23, 0xdf, 0xa0, 0x34,
	0x3d, 0x19, 0xe2, 0x97, 0x32, 0x72, 0xf9, 0x6b, 0x7e, 0x37, 0xc4, 0x2f, 0xb7, 0xc4, 0x5b, 0xd2,
	0xdb, 0x1f, 0x7e, 0x25, 0xa3, 0x9f, 0x8b, 0xf6, 0xae, 0x87, 0x26, 0xa8, 0xbe, 0xda, 0x9e, 0xaa,
	0xf4, 0x2e, 0x87, 0x5f, 0x6b, 0x4f, 0x35, 0xe1, 0xf9, 0x0e, 0xbf, 0xae, 0x04, 0x57, 0xe7, 0x67,
	0x29, 0xfc, 0xa6, 0x12, 0xac, 0x49, 0xcf, 0x4a, 0xf8, 0x2d, 0x35, 0x57, 0x13, 0xde, 0x7d, 0xf0,
	0xdb, 0x19, 0x79, 0x80, 0x6c, 0xf3, 0x5a, 0x83, 0xdf, 0x51, 0x32, 0x5a, 0xbd, 0x26, 0xc7, 0xef,
	0xb6, 0xa6, 0x7b, 0xa1, 0x6e, 0x2e, 0xcd, 0x79, 0x4b, 0xc4, 0xc5, 0xc7, 0xb3, 0x72, 0xfc, 0x24,
	0xde, 0xd1, 0xe3, 0xab, 0xb2, 0x72, 0xf1, 0xe9, 0xf0, 0x24, 0x81, 0xaf, 0xce, 0xca, 0x57, 0x89,
	0x5d, 0x3c, 0x5e, 0xe0, 0xff, 0xcb, 0xca, 0xf1, 0xbe, 0xee, 0x45, 0x3e, 0xfe, 0xff, 0xac, 0x9c,
	0x52, 0xdd, 0xdc, 0xd4, 0xe3, 0x6b, 0xb2, 0x72, 0x1d, 0x96, 0x0f, 0x86, 0x2c, 0x9b, 0xd8, 0x09,
	0xa1, 0x02, 0xde, 0xb8, 0x36, 0x2b, 0xcf, 0x4a, 0xc9, 0x17, 0xfb, 0xf8, 0xba, 0x56, 0xa4, 0x96,
	0x6b, 0x7c, 0x7c, 0x7d, 0x56, 0xf6, 0x6b, 0xd2, 0xcd, 0x3c, 0xbe, 0x21, 0xdb, 0x7a, 0x25, 0xc9,
	0x0f, 0xc3, 0x63, 0x0d, 0x7c, 0x63, 0xb6, 0xf5, 0x4e, 0x27, 0x5e, 0x14, 0x6a, 0xbd, 0x27, 0x3b,
	0x7c, 0x73, 0x2f, 0xda, 0x3c, 0x3e, 0xc9, 0x7f, 0xde, 0x21, 0x7e, 0xbb, 0xa1, 0xc3, 0x3e, 0x05,
	0x36, 0x73, 0x18, 0x9f, 0xa0, 0x0f, 0x31, 0x66, 0x0a, 0xbc, 0x40, 0x5c, 0x1b, 0xc2, 0xa3, 0x07,
	0xc6, 0xa1, 0x9d, 0xcd, 0x6b, 0x3c, 0xfe, 0xc7, 0x7d, 0xdf, 0xf3, 0x71, 0x2f, 0x48, 0xba, 0xbd,
	0x19, 0x81, 0xfe, 0x4c, 0xc0, 0xab, 0x87, 0xb8, 0x2f, 0x69, 0x71, 0xca, 0x5d, 0x86, 0xda, 0x69,
	0xe1, 0x0d, 0x49, 0x8b, 0x47, 0xbd, 0x69, 0x23, 0x34, 0x17, 0x71, 0x3f, 0x4c, 0x08, 0x27, 0x37,
	0x2f, 0x1e, 0x73, 0xe9, 0x4d, 0x8f, 0xcb, 0x19, 0x6f, 0x4c, 0x92, 0x0c, 0x66, 0xb9, 0x23, 0xde,
	0x02, 0xb4, 0xa0, 0x19, 0x17, 0xa7, 0x64, 0xb5, 0x26, 0x0c, 0xdb, 0x21, 0xd6, 0x9c, 0x97, 0x87,
	0x03, 0x58, 0x48, 0xb0, 0x36, 0x7c, 0x53, 0x2f, 0x1a, 0x1c, 0xe7, 0x17, 0xfe, 0xec, 0xb6, 0x93,
	0x0b, 0x23, 0x01, 0xca, 0xa5, 0xba, 0x69, 0x12, 0x62, 0x81, 0x11, 0x4e, 0xe0, 0xac, 0xe4, 0x45,
	0x4e, 0x0f, 0x72, 0x8c, 0xce, 0xf2, 0x60, 0xa5, 0xdd, 0x34, 0x0d, 0x13, 0x10, 0x60, 0x5a, 0x09,
	0x47, 0x2b, 0x15, 0xcf, 0xb7, 0xc0, 0x52, 0x9d, 0x90, 0x68, 0x87, 0xb6, 0xa9, 0xc5, 0xf6, 0xd0,
	0xe9, 0xb2, 0x0d, 0xd2, 0x11, 0xfa, 0x3c, 0xc1, 0xc6, 0x82, 0x0d, 0xd0, 0x66, 0xce, 0x5c, 0x87,
	0x23, 0x3f, 0x17, 0x82, 0x29, 0x3b, 0x91, 0xe4, 0xa8, 0x93, 0xa4, 0x8a, 0x37, 0x0e, 0xbf, 0xd1,
	0x8b, 0x4e, 0x1d, 0x57, 0x1a, 0x91, 0x98, 0x06, 0xe3, 0x86, 0x07, 0xf9, 0x08, 0xe7, 0xbc, 0xce,
	0x38, 0x8a, 0xe5, 0x2e, 0x40, 0x07, 0xd7, 0xc5, 0x8f, 0xc4, 0x81, 0x93, 0x6d, 0x54, 0x5c, 0xc0,
	0xa0, 0x97, 0xa0, 0xff, 0xec, 0x7a, 0x1f, 0xcd, 0x7d, 0xf0, 0xfc, 0x94, 0x2b, 0x70, 0xc1, 0xd8,
	0x17, 0xa3, 0xff, 0xe8, 0x96, 0x00, 0x64, 0xba, 0x63, 0x01, 0x01, 0x80, 0x47, 0xb7, 0x4d, 0x7d,
	0xfa, 0xf9, 0xe8, 0x40, 0xb7, 0xdb, 0x8f, 0x7a, 0xa5, 0x99, 0xd8, 0x2b, 0x07, 0x68, 0x7b, 0x5c,
	0x67, 0x5b, 0x7c, 0x2f, 0x3a, 0x51, 0x77, 0x1c, 0xdc, 0x3f, 0xfc, 0x5c, 0x2f, 0xda, 0xd5, 0xc6,
	0xea, 0x7c, 0x0c, 0xd0, 0xf7, 0xd1, 0x2e, 0xd4, 0x09, 0x43, 0xb1, 0xf8, 0x7f, 0xa1, 0x0b, 0xd7,
	0xc1, 0x96, 0xec, 0xd6, 0x64, 0xb6, 0x1e, 0xfd, 0x22, 0x74, 0x41, 0x77, 0xbb, 0x9b, 0x8d, 0x06,
	0x26, 0x3f, 0x0f, 0xed, 0xef, 0x6e, 0xef, 0x9a, 0xc5, 0xfa, 0x60, 0xa0, 0x18, 0xe9, 0x76, 0x53,
	0x81, 0x84, 0xf0, 0x27, 0x58, 0xb9, 0x83, 0x73, 0x9a, 0xf6, 0x90, 0x55, 0xcf, 0xe5, 0x23, 0x2a,
	0xee, 0x1f, 0xeb, 0x3f, 0xd4, 0x73, 0xbc, 0xe7, 0x84, 0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0xec,
	0x9a, 0x5e, 0xd5, 0x94, 0x29, 0x00, 0x00,
}
