// Code generated by protoc-gen-go.
// source: steammessages_base.proto
// DO NOT EDIT!

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package protobuf is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package protobuf to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CMsgProtoBufHeader struct {
	Steamid           *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	ClientSessionid   *int32  `protobuf:"varint,2,opt,name=client_sessionid,json=clientSessionid" json:"client_sessionid,omitempty"`
	RoutingAppid      *uint32 `protobuf:"varint,3,opt,name=routing_appid,json=routingAppid" json:"routing_appid,omitempty"`
	JobidSource       *uint64 `protobuf:"fixed64,10,opt,name=jobid_source,json=jobidSource,def=18446744073709551615" json:"jobid_source,omitempty"`
	JobidTarget       *uint64 `protobuf:"fixed64,11,opt,name=jobid_target,json=jobidTarget,def=18446744073709551615" json:"jobid_target,omitempty"`
	TargetJobName     *string `protobuf:"bytes,12,opt,name=target_job_name,json=targetJobName" json:"target_job_name,omitempty"`
	SeqNum            *int32  `protobuf:"varint,24,opt,name=seq_num,json=seqNum" json:"seq_num,omitempty"`
	Eresult           *int32  `protobuf:"varint,13,opt,name=eresult,def=2" json:"eresult,omitempty"`
	ErrorMessage      *string `protobuf:"bytes,14,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	Ip                *uint32 `protobuf:"varint,15,opt,name=ip" json:"ip,omitempty"`
	AuthAccountFlags  *uint32 `protobuf:"varint,16,opt,name=auth_account_flags,json=authAccountFlags" json:"auth_account_flags,omitempty"`
	TokenSource       *uint32 `protobuf:"varint,22,opt,name=token_source,json=tokenSource" json:"token_source,omitempty"`
	AdminSpoofingUser *bool   `protobuf:"varint,23,opt,name=admin_spoofing_user,json=adminSpoofingUser" json:"admin_spoofing_user,omitempty"`
	TransportError    *int32  `protobuf:"varint,17,opt,name=transport_error,json=transportError,def=1" json:"transport_error,omitempty"`
	Messageid         *uint64 `protobuf:"varint,18,opt,name=messageid,def=18446744073709551615" json:"messageid,omitempty"`
	PublisherGroupId  *uint32 `protobuf:"varint,19,opt,name=publisher_group_id,json=publisherGroupId" json:"publisher_group_id,omitempty"`
	Sysid             *uint32 `protobuf:"varint,20,opt,name=sysid" json:"sysid,omitempty"`
	TraceTag          *uint64 `protobuf:"varint,21,opt,name=trace_tag,json=traceTag" json:"trace_tag,omitempty"`
	WebapiKeyId       *uint32 `protobuf:"varint,25,opt,name=webapi_key_id,json=webapiKeyId" json:"webapi_key_id,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *CMsgProtoBufHeader) Reset()                    { *m = CMsgProtoBufHeader{} }
func (m *CMsgProtoBufHeader) String() string            { return proto.CompactTextString(m) }
func (*CMsgProtoBufHeader) ProtoMessage()               {}
func (*CMsgProtoBufHeader) Descriptor() ([]byte, []int) { return base_fileDescriptor0, []int{0} }

const Default_CMsgProtoBufHeader_JobidSource uint64 = 18446744073709551615
const Default_CMsgProtoBufHeader_JobidTarget uint64 = 18446744073709551615
const Default_CMsgProtoBufHeader_Eresult int32 = 2
const Default_CMsgProtoBufHeader_TransportError int32 = 1
const Default_CMsgProtoBufHeader_Messageid uint64 = 18446744073709551615

func (m *CMsgProtoBufHeader) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetClientSessionid() int32 {
	if m != nil && m.ClientSessionid != nil {
		return *m.ClientSessionid
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetRoutingAppid() uint32 {
	if m != nil && m.RoutingAppid != nil {
		return *m.RoutingAppid
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetJobidSource() uint64 {
	if m != nil && m.JobidSource != nil {
		return *m.JobidSource
	}
	return Default_CMsgProtoBufHeader_JobidSource
}

func (m *CMsgProtoBufHeader) GetJobidTarget() uint64 {
	if m != nil && m.JobidTarget != nil {
		return *m.JobidTarget
	}
	return Default_CMsgProtoBufHeader_JobidTarget
}

func (m *CMsgProtoBufHeader) GetTargetJobName() string {
	if m != nil && m.TargetJobName != nil {
		return *m.TargetJobName
	}
	return ""
}

func (m *CMsgProtoBufHeader) GetSeqNum() int32 {
	if m != nil && m.SeqNum != nil {
		return *m.SeqNum
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetEresult() int32 {
	if m != nil && m.Eresult != nil {
		return *m.Eresult
	}
	return Default_CMsgProtoBufHeader_Eresult
}

func (m *CMsgProtoBufHeader) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}

func (m *CMsgProtoBufHeader) GetIp() uint32 {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetAuthAccountFlags() uint32 {
	if m != nil && m.AuthAccountFlags != nil {
		return *m.AuthAccountFlags
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetTokenSource() uint32 {
	if m != nil && m.TokenSource != nil {
		return *m.TokenSource
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetAdminSpoofingUser() bool {
	if m != nil && m.AdminSpoofingUser != nil {
		return *m.AdminSpoofingUser
	}
	return false
}

func (m *CMsgProtoBufHeader) GetTransportError() int32 {
	if m != nil && m.TransportError != nil {
		return *m.TransportError
	}
	return Default_CMsgProtoBufHeader_TransportError
}

func (m *CMsgProtoBufHeader) GetMessageid() uint64 {
	if m != nil && m.Messageid != nil {
		return *m.Messageid
	}
	return Default_CMsgProtoBufHeader_Messageid
}

func (m *CMsgProtoBufHeader) GetPublisherGroupId() uint32 {
	if m != nil && m.PublisherGroupId != nil {
		return *m.PublisherGroupId
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetSysid() uint32 {
	if m != nil && m.Sysid != nil {
		return *m.Sysid
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetTraceTag() uint64 {
	if m != nil && m.TraceTag != nil {
		return *m.TraceTag
	}
	return 0
}

func (m *CMsgProtoBufHeader) GetWebapiKeyId() uint32 {
	if m != nil && m.WebapiKeyId != nil {
		return *m.WebapiKeyId
	}
	return 0
}

type CMsgMulti struct {
	SizeUnzipped     *uint32 `protobuf:"varint,1,opt,name=size_unzipped,json=sizeUnzipped" json:"size_unzipped,omitempty"`
	MessageBody      []byte  `protobuf:"bytes,2,opt,name=message_body,json=messageBody" json:"message_body,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgMulti) Reset()                    { *m = CMsgMulti{} }
func (m *CMsgMulti) String() string            { return proto.CompactTextString(m) }
func (*CMsgMulti) ProtoMessage()               {}
func (*CMsgMulti) Descriptor() ([]byte, []int) { return base_fileDescriptor0, []int{1} }

func (m *CMsgMulti) GetSizeUnzipped() uint32 {
	if m != nil && m.SizeUnzipped != nil {
		return *m.SizeUnzipped
	}
	return 0
}

func (m *CMsgMulti) GetMessageBody() []byte {
	if m != nil {
		return m.MessageBody
	}
	return nil
}

type CMsgProtobufWrapped struct {
	MessageBody      []byte `protobuf:"bytes,1,opt,name=message_body,json=messageBody" json:"message_body,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMsgProtobufWrapped) Reset()                    { *m = CMsgProtobufWrapped{} }
func (m *CMsgProtobufWrapped) String() string            { return proto.CompactTextString(m) }
func (*CMsgProtobufWrapped) ProtoMessage()               {}
func (*CMsgProtobufWrapped) Descriptor() ([]byte, []int) { return base_fileDescriptor0, []int{2} }

func (m *CMsgProtobufWrapped) GetMessageBody() []byte {
	if m != nil {
		return m.MessageBody
	}
	return nil
}

type CMsgAuthTicket struct {
	Estate           *uint32 `protobuf:"varint,1,opt,name=estate" json:"estate,omitempty"`
	Eresult          *uint32 `protobuf:"varint,2,opt,name=eresult,def=2" json:"eresult,omitempty"`
	Steamid          *uint64 `protobuf:"fixed64,3,opt,name=steamid" json:"steamid,omitempty"`
	Gameid           *uint64 `protobuf:"fixed64,4,opt,name=gameid" json:"gameid,omitempty"`
	HSteamPipe       *uint32 `protobuf:"varint,5,opt,name=h_steam_pipe,json=hSteamPipe" json:"h_steam_pipe,omitempty"`
	TicketCrc        *uint32 `protobuf:"varint,6,opt,name=ticket_crc,json=ticketCrc" json:"ticket_crc,omitempty"`
	Ticket           []byte  `protobuf:"bytes,7,opt,name=ticket" json:"ticket,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgAuthTicket) Reset()                    { *m = CMsgAuthTicket{} }
func (m *CMsgAuthTicket) String() string            { return proto.CompactTextString(m) }
func (*CMsgAuthTicket) ProtoMessage()               {}
func (*CMsgAuthTicket) Descriptor() ([]byte, []int) { return base_fileDescriptor0, []int{3} }

const Default_CMsgAuthTicket_Eresult uint32 = 2

func (m *CMsgAuthTicket) GetEstate() uint32 {
	if m != nil && m.Estate != nil {
		return *m.Estate
	}
	return 0
}

func (m *CMsgAuthTicket) GetEresult() uint32 {
	if m != nil && m.Eresult != nil {
		return *m.Eresult
	}
	return Default_CMsgAuthTicket_Eresult
}

func (m *CMsgAuthTicket) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CMsgAuthTicket) GetGameid() uint64 {
	if m != nil && m.Gameid != nil {
		return *m.Gameid
	}
	return 0
}

func (m *CMsgAuthTicket) GetHSteamPipe() uint32 {
	if m != nil && m.HSteamPipe != nil {
		return *m.HSteamPipe
	}
	return 0
}

func (m *CMsgAuthTicket) GetTicketCrc() uint32 {
	if m != nil && m.TicketCrc != nil {
		return *m.TicketCrc
	}
	return 0
}

func (m *CMsgAuthTicket) GetTicket() []byte {
	if m != nil {
		return m.Ticket
	}
	return nil
}

type CCDDBAppDetailCommon struct {
	Appid                 *uint32 `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	Name                  *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Icon                  *string `protobuf:"bytes,3,opt,name=icon" json:"icon,omitempty"`
	Logo                  *string `protobuf:"bytes,4,opt,name=logo" json:"logo,omitempty"`
	LogoSmall             *string `protobuf:"bytes,5,opt,name=logo_small,json=logoSmall" json:"logo_small,omitempty"`
	Tool                  *bool   `protobuf:"varint,6,opt,name=tool" json:"tool,omitempty"`
	Demo                  *bool   `protobuf:"varint,7,opt,name=demo" json:"demo,omitempty"`
	Media                 *bool   `protobuf:"varint,8,opt,name=media" json:"media,omitempty"`
	CommunityVisibleStats *bool   `protobuf:"varint,9,opt,name=community_visible_stats,json=communityVisibleStats" json:"community_visible_stats,omitempty"`
	FriendlyName          *string `protobuf:"bytes,10,opt,name=friendly_name,json=friendlyName" json:"friendly_name,omitempty"`
	Propagation           *string `protobuf:"bytes,11,opt,name=propagation" json:"propagation,omitempty"`
	HasAdultContent       *bool   `protobuf:"varint,12,opt,name=has_adult_content,json=hasAdultContent" json:"has_adult_content,omitempty"`
	XXX_unrecognized      []byte  `json:"-"`
}

func (m *CCDDBAppDetailCommon) Reset()                    { *m = CCDDBAppDetailCommon{} }
func (m *CCDDBAppDetailCommon) String() string            { return proto.CompactTextString(m) }
func (*CCDDBAppDetailCommon) ProtoMessage()               {}
func (*CCDDBAppDetailCommon) Descriptor() ([]byte, []int) { return base_fileDescriptor0, []int{4} }

func (m *CCDDBAppDetailCommon) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CCDDBAppDetailCommon) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CCDDBAppDetailCommon) GetIcon() string {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return ""
}

func (m *CCDDBAppDetailCommon) GetLogo() string {
	if m != nil && m.Logo != nil {
		return *m.Logo
	}
	return ""
}

func (m *CCDDBAppDetailCommon) GetLogoSmall() string {
	if m != nil && m.LogoSmall != nil {
		return *m.LogoSmall
	}
	return ""
}

func (m *CCDDBAppDetailCommon) GetTool() bool {
	if m != nil && m.Tool != nil {
		return *m.Tool
	}
	return false
}

func (m *CCDDBAppDetailCommon) GetDemo() bool {
	if m != nil && m.Demo != nil {
		return *m.Demo
	}
	return false
}

func (m *CCDDBAppDetailCommon) GetMedia() bool {
	if m != nil && m.Media != nil {
		return *m.Media
	}
	return false
}

func (m *CCDDBAppDetailCommon) GetCommunityVisibleStats() bool {
	if m != nil && m.CommunityVisibleStats != nil {
		return *m.CommunityVisibleStats
	}
	return false
}

func (m *CCDDBAppDetailCommon) GetFriendlyName() string {
	if m != nil && m.FriendlyName != nil {
		return *m.FriendlyName
	}
	return ""
}

func (m *CCDDBAppDetailCommon) GetPropagation() string {
	if m != nil && m.Propagation != nil {
		return *m.Propagation
	}
	return ""
}

func (m *CCDDBAppDetailCommon) GetHasAdultContent() bool {
	if m != nil && m.HasAdultContent != nil {
		return *m.HasAdultContent
	}
	return false
}

type CMsgAppRights struct {
	EditInfo                 *bool  `protobuf:"varint,1,opt,name=edit_info,json=editInfo" json:"edit_info,omitempty"`
	Publish                  *bool  `protobuf:"varint,2,opt,name=publish" json:"publish,omitempty"`
	ViewErrorData            *bool  `protobuf:"varint,3,opt,name=view_error_data,json=viewErrorData" json:"view_error_data,omitempty"`
	Download                 *bool  `protobuf:"varint,4,opt,name=download" json:"download,omitempty"`
	UploadCdkeys             *bool  `protobuf:"varint,5,opt,name=upload_cdkeys,json=uploadCdkeys" json:"upload_cdkeys,omitempty"`
	GenerateCdkeys           *bool  `protobuf:"varint,6,opt,name=generate_cdkeys,json=generateCdkeys" json:"generate_cdkeys,omitempty"`
	ViewFinancials           *bool  `protobuf:"varint,7,opt,name=view_financials,json=viewFinancials" json:"view_financials,omitempty"`
	ManageCeg                *bool  `protobuf:"varint,8,opt,name=manage_ceg,json=manageCeg" json:"manage_ceg,omitempty"`
	ManageSigning            *bool  `protobuf:"varint,9,opt,name=manage_signing,json=manageSigning" json:"manage_signing,omitempty"`
	ManageCdkeys             *bool  `protobuf:"varint,10,opt,name=manage_cdkeys,json=manageCdkeys" json:"manage_cdkeys,omitempty"`
	EditMarketing            *bool  `protobuf:"varint,11,opt,name=edit_marketing,json=editMarketing" json:"edit_marketing,omitempty"`
	EconomySupport           *bool  `protobuf:"varint,12,opt,name=economy_support,json=economySupport" json:"economy_support,omitempty"`
	EconomySupportSupervisor *bool  `protobuf:"varint,13,opt,name=economy_support_supervisor,json=economySupportSupervisor" json:"economy_support_supervisor,omitempty"`
	ManagePricing            *bool  `protobuf:"varint,14,opt,name=manage_pricing,json=managePricing" json:"manage_pricing,omitempty"`
	BroadcastLive            *bool  `protobuf:"varint,15,opt,name=broadcast_live,json=broadcastLive" json:"broadcast_live,omitempty"`
	XXX_unrecognized         []byte `json:"-"`
}

func (m *CMsgAppRights) Reset()                    { *m = CMsgAppRights{} }
func (m *CMsgAppRights) String() string            { return proto.CompactTextString(m) }
func (*CMsgAppRights) ProtoMessage()               {}
func (*CMsgAppRights) Descriptor() ([]byte, []int) { return base_fileDescriptor0, []int{5} }

func (m *CMsgAppRights) GetEditInfo() bool {
	if m != nil && m.EditInfo != nil {
		return *m.EditInfo
	}
	return false
}

func (m *CMsgAppRights) GetPublish() bool {
	if m != nil && m.Publish != nil {
		return *m.Publish
	}
	return false
}

func (m *CMsgAppRights) GetViewErrorData() bool {
	if m != nil && m.ViewErrorData != nil {
		return *m.ViewErrorData
	}
	return false
}

func (m *CMsgAppRights) GetDownload() bool {
	if m != nil && m.Download != nil {
		return *m.Download
	}
	return false
}

func (m *CMsgAppRights) GetUploadCdkeys() bool {
	if m != nil && m.UploadCdkeys != nil {
		return *m.UploadCdkeys
	}
	return false
}

func (m *CMsgAppRights) GetGenerateCdkeys() bool {
	if m != nil && m.GenerateCdkeys != nil {
		return *m.GenerateCdkeys
	}
	return false
}

func (m *CMsgAppRights) GetViewFinancials() bool {
	if m != nil && m.ViewFinancials != nil {
		return *m.ViewFinancials
	}
	return false
}

func (m *CMsgAppRights) GetManageCeg() bool {
	if m != nil && m.ManageCeg != nil {
		return *m.ManageCeg
	}
	return false
}

func (m *CMsgAppRights) GetManageSigning() bool {
	if m != nil && m.ManageSigning != nil {
		return *m.ManageSigning
	}
	return false
}

func (m *CMsgAppRights) GetManageCdkeys() bool {
	if m != nil && m.ManageCdkeys != nil {
		return *m.ManageCdkeys
	}
	return false
}

func (m *CMsgAppRights) GetEditMarketing() bool {
	if m != nil && m.EditMarketing != nil {
		return *m.EditMarketing
	}
	return false
}

func (m *CMsgAppRights) GetEconomySupport() bool {
	if m != nil && m.EconomySupport != nil {
		return *m.EconomySupport
	}
	return false
}

func (m *CMsgAppRights) GetEconomySupportSupervisor() bool {
	if m != nil && m.EconomySupportSupervisor != nil {
		return *m.EconomySupportSupervisor
	}
	return false
}

func (m *CMsgAppRights) GetManagePricing() bool {
	if m != nil && m.ManagePricing != nil {
		return *m.ManagePricing
	}
	return false
}

func (m *CMsgAppRights) GetBroadcastLive() bool {
	if m != nil && m.BroadcastLive != nil {
		return *m.BroadcastLive
	}
	return false
}

var E_MsgpoolSoftLimit = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         50000,
	Name:          "msgpool_soft_limit",
	Tag:           "varint,50000,opt,name=msgpool_soft_limit,json=msgpoolSoftLimit,def=32",
}

var E_MsgpoolHardLimit = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         50001,
	Name:          "msgpool_hard_limit",
	Tag:           "varint,50001,opt,name=msgpool_hard_limit,json=msgpoolHardLimit,def=384",
}

func init() {
	proto.RegisterType((*CMsgProtoBufHeader)(nil), "CMsgProtoBufHeader")
	proto.RegisterType((*CMsgMulti)(nil), "CMsgMulti")
	proto.RegisterType((*CMsgProtobufWrapped)(nil), "CMsgProtobufWrapped")
	proto.RegisterType((*CMsgAuthTicket)(nil), "CMsgAuthTicket")
	proto.RegisterType((*CCDDBAppDetailCommon)(nil), "CCDDBAppDetailCommon")
	proto.RegisterType((*CMsgAppRights)(nil), "CMsgAppRights")
	proto.RegisterExtension(E_MsgpoolSoftLimit)
	proto.RegisterExtension(E_MsgpoolHardLimit)
}

func init() { proto.RegisterFile("steammessages_base.proto", base_fileDescriptor0) }

var base_fileDescriptor0 = []byte{
	// 1195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x96, 0x4b, 0x73, 0xdc, 0x44,
	0x10, 0x80, 0x59, 0xbf, 0xb2, 0x3b, 0xfb, 0xb0, 0x33, 0x71, 0x12, 0x11, 0x8a, 0xc2, 0x2c, 0xc5,
	0xb3, 0x28, 0x27, 0x4e, 0x9c, 0x38, 0xb8, 0xb8, 0xd8, 0x6b, 0x42, 0x02, 0x71, 0x48, 0x49, 0x0e,
	0x1c, 0xa7, 0x66, 0xa5, 0x59, 0xed, 0x10, 0x49, 0x23, 0x66, 0xa4, 0xa4, 0x36, 0x27, 0x4e, 0xfc,
	0x36, 0x8e, 0xe1, 0x67, 0x70, 0xe3, 0x27, 0xd0, 0xdd, 0x23, 0xad, 0x1d, 0x1e, 0x05, 0xa7, 0xd5,
	0x7c, 0xdd, 0xd3, 0xea, 0xb7, 0x96, 0x05, 0xae, 0x52, 0x32, 0xcf, 0x95, 0x73, 0x32, 0x55, 0x4e,
	0x4c, 0xa5, 0x53, 0xbb, 0xa5, 0x35, 0x95, 0xb9, 0xb1, 0x93, 0x1a, 0x93, 0x66, 0xea, 0x26, 0x9d,
	0xa6, 0xf5, 0xec, 0x66, 0xa2, 0x5c, 0x6c, 0x75, 0x59, 0x19, 0xeb, 0x35, 0xc6, 0xbf, 0xaf, 0x33,
	0x3e, 0x39, 0x75, 0xe9, 0x53, 0x3c, 0x1d, 0xd7, 0xb3, 0x87, 0x4a, 0x26, 0xca, 0xf2, 0x80, 0x5d,
	0x22, 0xa3, 0x3a, 0x09, 0x3a, 0x3b, 0x9d, 0x4f, 0x36, 0xc2, 0xf6, 0xc8, 0x3f, 0x65, 0x5b, 0x71,
	0xa6, 0x55, 0x51, 0x09, 0x07, 0x2f, 0xd4, 0xa6, 0x00, 0x95, 0x15, 0x50, 0x59, 0x0f, 0x37, 0x3d,
	0x8f, 0x5a, 0xcc, 0x3f, 0x60, 0x43, 0x6b, 0xea, 0x4a, 0x17, 0xa9, 0x90, 0x65, 0x09, 0x7a, 0xab,
	0xa0, 0x37, 0x0c, 0x07, 0x0d, 0x3c, 0x42, 0xc6, 0x0f, 0xd8, 0xe0, 0x47, 0x33, 0xd5, 0x89, 0x70,
	0xa6, 0xb6, 0xb1, 0x0a, 0x18, 0xbe, 0xee, 0x70, 0x7b, 0xef, 0xfe, 0xfe, 0xfe, 0xbd, 0x83, 0xfd,
	0xfd, 0x5b, 0x07, 0x77, 0x0e, 0x6e, 0x7d, 0x71, 0xf7, 0xee, 0xde, 0xbd, 0xbd, 0xbb, 0x61, 0x9f,
	0x34, 0x23, 0x52, 0x3c, 0xbf, 0x58, 0x49, 0x9b, 0xaa, 0x2a, 0xe8, 0xff, 0xe7, 0xc5, 0x33, 0x52,
	0xe4, 0x1f, 0xb1, 0x4d, 0x7f, 0x45, 0x00, 0x15, 0x85, 0xcc, 0x55, 0x30, 0x80, 0xbb, 0xbd, 0x70,
	0xe8, 0xf1, 0x37, 0x66, 0xfa, 0x04, 0x20, 0xbf, 0x0e, 0x39, 0x50, 0x3f, 0x89, 0xa2, 0xce, 0x83,
	0x80, 0x02, 0xdc, 0x80, 0xe3, 0x93, 0x3a, 0xe7, 0xef, 0xb0, 0x4b, 0xca, 0x2a, 0x57, 0x67, 0x55,
	0x30, 0x44, 0xc1, 0x61, 0xe7, 0x76, 0xd8, 0x12, 0x0c, 0x5a, 0x59, 0x6b, 0xac, 0x68, 0xea, 0x11,
	0x8c, 0xc8, 0xf6, 0x80, 0xe0, 0xa9, 0x67, 0x7c, 0xc4, 0x56, 0x74, 0x19, 0x6c, 0x52, 0x3a, 0xe0,
	0x89, 0x7f, 0xce, 0xb8, 0xac, 0xab, 0xb9, 0x90, 0x71, 0x6c, 0x6a, 0x48, 0xed, 0x2c, 0x93, 0xa9,
	0x0b, 0xb6, 0x48, 0xbe, 0x85, 0x92, 0x23, 0x2f, 0x78, 0x80, 0x9c, 0xbf, 0xcf, 0x06, 0x95, 0x79,
	0xae, 0x8a, 0x36, 0x65, 0xd7, 0x48, 0xaf, 0x4f, 0xac, 0x49, 0xce, 0x2e, 0xbb, 0x22, 0x93, 0x5c,
	0x83, 0x4a, 0x69, 0xcc, 0x0c, 0x2b, 0x50, 0x3b, 0x65, 0x83, 0xeb, 0xa0, 0xd9, 0x0d, 0x2f, 0x93,
	0x28, 0x6a, 0x24, 0xcf, 0x40, 0xc0, 0x3f, 0x83, 0x9c, 0x58, 0x59, 0x80, 0xb6, 0xad, 0x04, 0xb9,
	0x1a, 0x5c, 0xf6, 0xa1, 0xed, 0x85, 0xa3, 0xa5, 0xe4, 0x2b, 0x14, 0xf0, 0xdb, 0xac, 0xd7, 0xc4,
	0x06, 0x25, 0xe5, 0xa0, 0xb5, 0xf6, 0x2f, 0x59, 0x3f, 0x57, 0xc3, 0x00, 0xcb, 0x7a, 0x9a, 0x69,
	0x37, 0x57, 0x56, 0xa4, 0xd0, 0x00, 0xa5, 0x80, 0xcb, 0x57, 0x7c, 0x80, 0x4b, 0xc9, 0xd7, 0x28,
	0x78, 0x94, 0xf0, 0x6d, 0xb6, 0xee, 0x16, 0x0e, 0x14, 0xb6, 0x49, 0xc1, 0x1f, 0x20, 0xed, 0x3d,
	0xf0, 0x24, 0x56, 0x50, 0xf0, 0x34, 0xb8, 0x8a, 0xef, 0x0d, 0xbb, 0x04, 0xce, 0x64, 0xca, 0xc7,
	0x6c, 0xf8, 0x52, 0x4d, 0x65, 0xa9, 0xc5, 0x73, 0xb5, 0x40, 0xdb, 0x6f, 0xfb, 0xa4, 0x78, 0xf8,
	0xad, 0x5a, 0x3c, 0x4a, 0xc6, 0x11, 0xeb, 0x61, 0xab, 0x9f, 0x42, 0x99, 0x34, 0xd6, 0xc9, 0xe9,
	0x57, 0x4a, 0xd4, 0xc5, 0x2b, 0x5d, 0x96, 0xca, 0xf7, 0x39, 0x34, 0x27, 0xc2, 0x67, 0x0d, 0xc3,
	0x4c, 0x37, 0x31, 0x88, 0xa9, 0x49, 0x16, 0xd4, 0xe8, 0x83, 0xb0, 0xdf, 0xb0, 0x63, 0x40, 0xe3,
	0xfb, 0xec, 0xca, 0x72, 0x7e, 0x60, 0xc2, 0x7e, 0xb0, 0xf2, 0x1f, 0x6f, 0x76, 0xfe, 0x7e, 0xf3,
	0x75, 0x87, 0x8d, 0xf0, 0xea, 0x11, 0xd4, 0xf7, 0x4c, 0xc7, 0xcf, 0xa1, 0x35, 0xaf, 0xb1, 0x0d,
	0xe5, 0x2a, 0x59, 0xa9, 0xc6, 0x9b, 0xe6, 0x74, 0xb1, 0xe3, 0xd0, 0x85, 0xe1, 0x1b, 0x1d, 0x77,
	0x61, 0x56, 0x57, 0xdf, 0x9c, 0x55, 0x30, 0x97, 0x42, 0x27, 0x83, 0x60, 0x8d, 0x04, 0xcd, 0x89,
	0xef, 0xb0, 0xc1, 0x5c, 0x90, 0x92, 0x28, 0x75, 0xa9, 0x82, 0x75, 0x7a, 0x19, 0x9b, 0x47, 0x88,
	0x9e, 0x02, 0xe1, 0xef, 0x32, 0x56, 0x91, 0x4b, 0x22, 0xb6, 0x71, 0xb0, 0x41, 0xf2, 0x9e, 0x27,
	0x13, 0x1b, 0xa3, 0x61, 0x7f, 0x08, 0x2e, 0x51, 0x5c, 0xcd, 0x69, 0xfc, 0xc7, 0x0a, 0xdb, 0x9e,
	0x4c, 0x4e, 0x4e, 0x8e, 0x61, 0xb6, 0x4f, 0x54, 0x25, 0x75, 0x36, 0x31, 0x79, 0x6e, 0x0a, 0xac,
	0xa8, 0x5f, 0x01, 0x3e, 0x2e, 0x7f, 0xe0, 0x9c, 0xad, 0xd1, 0xf8, 0xad, 0xd0, 0x88, 0xd0, 0x33,
	0x32, 0x1d, 0x9b, 0x82, 0x42, 0x01, 0x86, 0xcf, 0xc8, 0x32, 0x93, 0x1a, 0x8a, 0x02, 0x18, 0x3e,
	0xa3, 0x87, 0xf8, 0x2b, 0x5c, 0x2e, 0xb3, 0x8c, 0x22, 0xe8, 0x85, 0x3d, 0x24, 0x11, 0x02, 0xbc,
	0x52, 0x19, 0x93, 0x91, 0xeb, 0xdd, 0x90, 0x9e, 0x91, 0x25, 0x2a, 0x37, 0xe4, 0x33, 0x30, 0x7c,
	0x46, 0xc7, 0x72, 0x95, 0x68, 0x19, 0x74, 0x09, 0xfa, 0x03, 0xbf, 0xc7, 0xae, 0xc7, 0xe0, 0x78,
	0x5d, 0xe8, 0x6a, 0x21, 0x5e, 0x68, 0xa7, 0xa7, 0x99, 0x12, 0x58, 0x0a, 0x17, 0xf4, 0x48, 0xef,
	0xea, 0x52, 0xfc, 0xbd, 0x97, 0x46, 0x28, 0xc4, 0xa6, 0x9a, 0x59, 0x58, 0x82, 0x49, 0xb6, 0xf0,
	0x8b, 0x85, 0xf9, 0xe1, 0x6f, 0x21, 0xed, 0x95, 0x1d, 0xd6, 0x87, 0xdd, 0x5b, 0xca, 0x54, 0x56,
	0xb0, 0x27, 0x69, 0x6f, 0xf5, 0xc2, 0x8b, 0x08, 0xa6, 0xf1, 0xf2, 0x5c, 0x3a, 0x21, 0x13, 0x28,
	0xaf, 0x80, 0x04, 0x54, 0xb0, 0x56, 0x69, 0x47, 0x75, 0xc3, 0x4d, 0x10, 0x1c, 0x21, 0x9f, 0x78,
	0x3c, 0xfe, 0x75, 0x8d, 0x0d, 0xa9, 0x8b, 0xca, 0x32, 0xd4, 0xe9, 0x1c, 0x9c, 0x80, 0x39, 0x81,
	0x20, 0x2a, 0xa1, 0x8b, 0x99, 0xa1, 0x7c, 0x77, 0xc3, 0x2e, 0x82, 0x47, 0x70, 0xc6, 0x66, 0x69,
	0xc6, 0x8d, 0xb2, 0xde, 0x0d, 0xdb, 0x23, 0xae, 0xc5, 0x17, 0x5a, 0xbd, 0xf4, 0xd3, 0x2f, 0x12,
	0x59, 0x49, 0xaa, 0x41, 0x37, 0x1c, 0x22, 0xa6, 0xd1, 0x3f, 0x01, 0xc8, 0x6f, 0xb0, 0x6e, 0x62,
	0x5e, 0x16, 0x99, 0x91, 0xbe, 0xad, 0xc0, 0x7a, 0x7b, 0xc6, 0xf8, 0xeb, 0x12, 0x9f, 0x44, 0x9c,
	0xc0, 0x1c, 0x3a, 0xaa, 0x4b, 0x37, 0x1c, 0x78, 0x38, 0x21, 0xc6, 0x3f, 0x66, 0x9b, 0xa9, 0x2a,
	0x94, 0x85, 0xc6, 0x6e, 0xd5, 0x7c, 0x95, 0x46, 0x2d, 0x3e, 0x57, 0x24, 0x8f, 0x60, 0x4b, 0xc9,
	0x22, 0xd6, 0x32, 0x73, 0x4d, 0xe9, 0x46, 0x88, 0x1f, 0x2c, 0x29, 0xf6, 0x42, 0x2e, 0x0b, 0x9c,
	0xb5, 0x58, 0xa5, 0x4d, 0x25, 0x7b, 0x9e, 0x4c, 0x54, 0xca, 0x3f, 0x64, 0xa3, 0x46, 0xec, 0x74,
	0x5a, 0xc0, 0xca, 0x6b, 0x8a, 0x38, 0xf4, 0x34, 0xf2, 0x10, 0x9d, 0x6f, 0xad, 0x78, 0xaf, 0x98,
	0x77, 0xbe, 0x31, 0xe4, 0x7d, 0x02, 0x5b, 0x94, 0xdc, 0x5c, 0x5a, 0x68, 0x78, 0xb4, 0xd5, 0xf7,
	0xb6, 0x90, 0x9e, 0xb6, 0x10, 0x5d, 0x57, 0x50, 0x38, 0x93, 0x2f, 0x84, 0xab, 0x4b, 0xdc, 0x9d,
	0x4d, 0xfd, 0x46, 0x0d, 0x8e, 0x3c, 0xe5, 0x5f, 0xb2, 0x1b, 0x7f, 0x51, 0xc4, 0x5f, 0x65, 0xa1,
	0xe9, 0x60, 0x07, 0x0f, 0xe9, 0x4e, 0xf0, 0xe6, 0x9d, 0x68, 0x29, 0xbf, 0x10, 0x59, 0x69, 0x75,
	0x8c, 0xde, 0x8c, 0x2e, 0x46, 0xf6, 0xd4, 0x43, 0x54, 0x9b, 0x5a, 0x28, 0x40, 0x2c, 0x5d, 0x25,
	0x32, 0xfd, 0x42, 0xd1, 0xa7, 0x07, 0xd4, 0x96, 0xf4, 0x31, 0xc0, 0xc3, 0x88, 0xf1, 0xdc, 0xa5,
	0xf0, 0x59, 0xc8, 0xe0, 0xcb, 0x32, 0x43, 0xcd, 0x5c, 0x57, 0xfc, 0xbd, 0x5d, 0xff, 0x27, 0x62,
	0xb7, 0xfd, 0x13, 0xb1, 0xdb, 0x7c, 0xc5, 0xbe, 0x2b, 0xb1, 0x59, 0x5d, 0xf0, 0xfa, 0x97, 0x55,
	0xfa, 0x54, 0xac, 0xdc, 0xb9, 0x1d, 0x6e, 0x35, 0x06, 0x22, 0xb8, 0xff, 0x18, 0xaf, 0x1f, 0x9e,
	0x9d, 0x1b, 0x9d, 0x4b, 0x9b, 0xfc, 0x5f, 0xa3, 0xbf, 0x35, 0x46, 0x57, 0xef, 0xdc, 0xdf, 0x5f,
	0x5a, 0x7d, 0x08, 0x06, 0xc8, 0xea, 0xf1, 0xfa, 0xc3, 0xce, 0xcf, 0x9d, 0xb7, 0xfe, 0x0c, 0x00,
	0x00, 0xff, 0xff, 0x54, 0xfa, 0x64, 0xb5, 0xfa, 0x08, 0x00, 0x00,
}
