// Code generated by protoc-gen-go. DO NOT EDIT.
// source: steammessages_clientserver_friends.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package protobuf is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package protobuf to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CMsgClientFriendMsg struct {
	Steamid                *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	ChatEntryType          *int32  `protobuf:"varint,2,opt,name=chat_entry_type,json=chatEntryType" json:"chat_entry_type,omitempty"`
	Message                []byte  `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Rtime32ServerTimestamp *uint32 `protobuf:"fixed32,4,opt,name=rtime32_server_timestamp,json=rtime32ServerTimestamp" json:"rtime32_server_timestamp,omitempty"`
	XXX_unrecognized       []byte  `json:"-"`
}

func (m *CMsgClientFriendMsg) Reset()                    { *m = CMsgClientFriendMsg{} }
func (m *CMsgClientFriendMsg) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientFriendMsg) ProtoMessage()               {}
func (*CMsgClientFriendMsg) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{0} }

func (m *CMsgClientFriendMsg) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CMsgClientFriendMsg) GetChatEntryType() int32 {
	if m != nil && m.ChatEntryType != nil {
		return *m.ChatEntryType
	}
	return 0
}

func (m *CMsgClientFriendMsg) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *CMsgClientFriendMsg) GetRtime32ServerTimestamp() uint32 {
	if m != nil && m.Rtime32ServerTimestamp != nil {
		return *m.Rtime32ServerTimestamp
	}
	return 0
}

type CMsgClientFriendMsgIncoming struct {
	SteamidFrom            *uint64 `protobuf:"fixed64,1,opt,name=steamid_from,json=steamidFrom" json:"steamid_from,omitempty"`
	ChatEntryType          *int32  `protobuf:"varint,2,opt,name=chat_entry_type,json=chatEntryType" json:"chat_entry_type,omitempty"`
	FromLimitedAccount     *bool   `protobuf:"varint,3,opt,name=from_limited_account,json=fromLimitedAccount" json:"from_limited_account,omitempty"`
	Message                []byte  `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	Rtime32ServerTimestamp *uint32 `protobuf:"fixed32,5,opt,name=rtime32_server_timestamp,json=rtime32ServerTimestamp" json:"rtime32_server_timestamp,omitempty"`
	XXX_unrecognized       []byte  `json:"-"`
}

func (m *CMsgClientFriendMsgIncoming) Reset()                    { *m = CMsgClientFriendMsgIncoming{} }
func (m *CMsgClientFriendMsgIncoming) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientFriendMsgIncoming) ProtoMessage()               {}
func (*CMsgClientFriendMsgIncoming) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{1} }

func (m *CMsgClientFriendMsgIncoming) GetSteamidFrom() uint64 {
	if m != nil && m.SteamidFrom != nil {
		return *m.SteamidFrom
	}
	return 0
}

func (m *CMsgClientFriendMsgIncoming) GetChatEntryType() int32 {
	if m != nil && m.ChatEntryType != nil {
		return *m.ChatEntryType
	}
	return 0
}

func (m *CMsgClientFriendMsgIncoming) GetFromLimitedAccount() bool {
	if m != nil && m.FromLimitedAccount != nil {
		return *m.FromLimitedAccount
	}
	return false
}

func (m *CMsgClientFriendMsgIncoming) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *CMsgClientFriendMsgIncoming) GetRtime32ServerTimestamp() uint32 {
	if m != nil && m.Rtime32ServerTimestamp != nil {
		return *m.Rtime32ServerTimestamp
	}
	return 0
}

type CMsgClientAddFriend struct {
	SteamidToAdd            *uint64 `protobuf:"fixed64,1,opt,name=steamid_to_add,json=steamidToAdd" json:"steamid_to_add,omitempty"`
	AccountnameOrEmailToAdd *string `protobuf:"bytes,2,opt,name=accountname_or_email_to_add,json=accountnameOrEmailToAdd" json:"accountname_or_email_to_add,omitempty"`
	XXX_unrecognized        []byte  `json:"-"`
}

func (m *CMsgClientAddFriend) Reset()                    { *m = CMsgClientAddFriend{} }
func (m *CMsgClientAddFriend) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientAddFriend) ProtoMessage()               {}
func (*CMsgClientAddFriend) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{2} }

func (m *CMsgClientAddFriend) GetSteamidToAdd() uint64 {
	if m != nil && m.SteamidToAdd != nil {
		return *m.SteamidToAdd
	}
	return 0
}

func (m *CMsgClientAddFriend) GetAccountnameOrEmailToAdd() string {
	if m != nil && m.AccountnameOrEmailToAdd != nil {
		return *m.AccountnameOrEmailToAdd
	}
	return ""
}

type CMsgClientAddFriendResponse struct {
	Eresult          *int32  `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	SteamIdAdded     *uint64 `protobuf:"fixed64,2,opt,name=steam_id_added,json=steamIdAdded" json:"steam_id_added,omitempty"`
	PersonaNameAdded *string `protobuf:"bytes,3,opt,name=persona_name_added,json=personaNameAdded" json:"persona_name_added,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientAddFriendResponse) Reset()                    { *m = CMsgClientAddFriendResponse{} }
func (m *CMsgClientAddFriendResponse) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientAddFriendResponse) ProtoMessage()               {}
func (*CMsgClientAddFriendResponse) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{3} }

const Default_CMsgClientAddFriendResponse_Eresult int32 = 2

func (m *CMsgClientAddFriendResponse) GetEresult() int32 {
	if m != nil && m.Eresult != nil {
		return *m.Eresult
	}
	return Default_CMsgClientAddFriendResponse_Eresult
}

func (m *CMsgClientAddFriendResponse) GetSteamIdAdded() uint64 {
	if m != nil && m.SteamIdAdded != nil {
		return *m.SteamIdAdded
	}
	return 0
}

func (m *CMsgClientAddFriendResponse) GetPersonaNameAdded() string {
	if m != nil && m.PersonaNameAdded != nil {
		return *m.PersonaNameAdded
	}
	return ""
}

type CMsgClientRemoveFriend struct {
	Friendid         *uint64 `protobuf:"fixed64,1,opt,name=friendid" json:"friendid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientRemoveFriend) Reset()                    { *m = CMsgClientRemoveFriend{} }
func (m *CMsgClientRemoveFriend) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientRemoveFriend) ProtoMessage()               {}
func (*CMsgClientRemoveFriend) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{4} }

func (m *CMsgClientRemoveFriend) GetFriendid() uint64 {
	if m != nil && m.Friendid != nil {
		return *m.Friendid
	}
	return 0
}

type CMsgClientHideFriend struct {
	Friendid         *uint64 `protobuf:"fixed64,1,opt,name=friendid" json:"friendid,omitempty"`
	Hide             *bool   `protobuf:"varint,2,opt,name=hide" json:"hide,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientHideFriend) Reset()                    { *m = CMsgClientHideFriend{} }
func (m *CMsgClientHideFriend) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientHideFriend) ProtoMessage()               {}
func (*CMsgClientHideFriend) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{5} }

func (m *CMsgClientHideFriend) GetFriendid() uint64 {
	if m != nil && m.Friendid != nil {
		return *m.Friendid
	}
	return 0
}

func (m *CMsgClientHideFriend) GetHide() bool {
	if m != nil && m.Hide != nil {
		return *m.Hide
	}
	return false
}

type CMsgClientFriendsList struct {
	Bincremental      *bool                           `protobuf:"varint,1,opt,name=bincremental" json:"bincremental,omitempty"`
	Friends           []*CMsgClientFriendsList_Friend `protobuf:"bytes,2,rep,name=friends" json:"friends,omitempty"`
	MaxFriendCount    *uint32                         `protobuf:"varint,3,opt,name=max_friend_count,json=maxFriendCount" json:"max_friend_count,omitempty"`
	ActiveFriendCount *uint32                         `protobuf:"varint,4,opt,name=active_friend_count,json=activeFriendCount" json:"active_friend_count,omitempty"`
	FriendsLimitHit   *bool                           `protobuf:"varint,5,opt,name=friends_limit_hit,json=friendsLimitHit" json:"friends_limit_hit,omitempty"`
	XXX_unrecognized  []byte                          `json:"-"`
}

func (m *CMsgClientFriendsList) Reset()                    { *m = CMsgClientFriendsList{} }
func (m *CMsgClientFriendsList) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientFriendsList) ProtoMessage()               {}
func (*CMsgClientFriendsList) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{6} }

func (m *CMsgClientFriendsList) GetBincremental() bool {
	if m != nil && m.Bincremental != nil {
		return *m.Bincremental
	}
	return false
}

func (m *CMsgClientFriendsList) GetFriends() []*CMsgClientFriendsList_Friend {
	if m != nil {
		return m.Friends
	}
	return nil
}

func (m *CMsgClientFriendsList) GetMaxFriendCount() uint32 {
	if m != nil && m.MaxFriendCount != nil {
		return *m.MaxFriendCount
	}
	return 0
}

func (m *CMsgClientFriendsList) GetActiveFriendCount() uint32 {
	if m != nil && m.ActiveFriendCount != nil {
		return *m.ActiveFriendCount
	}
	return 0
}

func (m *CMsgClientFriendsList) GetFriendsLimitHit() bool {
	if m != nil && m.FriendsLimitHit != nil {
		return *m.FriendsLimitHit
	}
	return false
}

type CMsgClientFriendsList_Friend struct {
	Ulfriendid          *uint64 `protobuf:"fixed64,1,opt,name=ulfriendid" json:"ulfriendid,omitempty"`
	Efriendrelationship *uint32 `protobuf:"varint,2,opt,name=efriendrelationship" json:"efriendrelationship,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *CMsgClientFriendsList_Friend) Reset()                    { *m = CMsgClientFriendsList_Friend{} }
func (m *CMsgClientFriendsList_Friend) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientFriendsList_Friend) ProtoMessage()               {}
func (*CMsgClientFriendsList_Friend) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{6, 0} }

func (m *CMsgClientFriendsList_Friend) GetUlfriendid() uint64 {
	if m != nil && m.Ulfriendid != nil {
		return *m.Ulfriendid
	}
	return 0
}

func (m *CMsgClientFriendsList_Friend) GetEfriendrelationship() uint32 {
	if m != nil && m.Efriendrelationship != nil {
		return *m.Efriendrelationship
	}
	return 0
}

type CMsgClientFriendsGroupsList struct {
	Bremoval         *bool                                                 `protobuf:"varint,1,opt,name=bremoval" json:"bremoval,omitempty"`
	Bincremental     *bool                                                 `protobuf:"varint,2,opt,name=bincremental" json:"bincremental,omitempty"`
	FriendGroups     []*CMsgClientFriendsGroupsList_FriendGroup            `protobuf:"bytes,3,rep,name=friendGroups" json:"friendGroups,omitempty"`
	Memberships      []*CMsgClientFriendsGroupsList_FriendGroupsMembership `protobuf:"bytes,4,rep,name=memberships" json:"memberships,omitempty"`
	XXX_unrecognized []byte                                                `json:"-"`
}

func (m *CMsgClientFriendsGroupsList) Reset()                    { *m = CMsgClientFriendsGroupsList{} }
func (m *CMsgClientFriendsGroupsList) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientFriendsGroupsList) ProtoMessage()               {}
func (*CMsgClientFriendsGroupsList) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{7} }

func (m *CMsgClientFriendsGroupsList) GetBremoval() bool {
	if m != nil && m.Bremoval != nil {
		return *m.Bremoval
	}
	return false
}

func (m *CMsgClientFriendsGroupsList) GetBincremental() bool {
	if m != nil && m.Bincremental != nil {
		return *m.Bincremental
	}
	return false
}

func (m *CMsgClientFriendsGroupsList) GetFriendGroups() []*CMsgClientFriendsGroupsList_FriendGroup {
	if m != nil {
		return m.FriendGroups
	}
	return nil
}

func (m *CMsgClientFriendsGroupsList) GetMemberships() []*CMsgClientFriendsGroupsList_FriendGroupsMembership {
	if m != nil {
		return m.Memberships
	}
	return nil
}

type CMsgClientFriendsGroupsList_FriendGroup struct {
	NGroupID         *int32  `protobuf:"varint,1,opt,name=nGroupID" json:"nGroupID,omitempty"`
	StrGroupName     *string `protobuf:"bytes,2,opt,name=strGroupName" json:"strGroupName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientFriendsGroupsList_FriendGroup) Reset() {
	*m = CMsgClientFriendsGroupsList_FriendGroup{}
}
func (m *CMsgClientFriendsGroupsList_FriendGroup) String() string { return proto.CompactTextString(m) }
func (*CMsgClientFriendsGroupsList_FriendGroup) ProtoMessage()    {}
func (*CMsgClientFriendsGroupsList_FriendGroup) Descriptor() ([]byte, []int) {
	return client_server_friends_fileDescriptor0, []int{7, 0}
}

func (m *CMsgClientFriendsGroupsList_FriendGroup) GetNGroupID() int32 {
	if m != nil && m.NGroupID != nil {
		return *m.NGroupID
	}
	return 0
}

func (m *CMsgClientFriendsGroupsList_FriendGroup) GetStrGroupName() string {
	if m != nil && m.StrGroupName != nil {
		return *m.StrGroupName
	}
	return ""
}

type CMsgClientFriendsGroupsList_FriendGroupsMembership struct {
	UlSteamID        *uint64 `protobuf:"fixed64,1,opt,name=ulSteamID" json:"ulSteamID,omitempty"`
	NGroupID         *int32  `protobuf:"varint,2,opt,name=nGroupID" json:"nGroupID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientFriendsGroupsList_FriendGroupsMembership) Reset() {
	*m = CMsgClientFriendsGroupsList_FriendGroupsMembership{}
}
func (m *CMsgClientFriendsGroupsList_FriendGroupsMembership) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgClientFriendsGroupsList_FriendGroupsMembership) ProtoMessage() {}
func (*CMsgClientFriendsGroupsList_FriendGroupsMembership) Descriptor() ([]byte, []int) {
	return client_server_friends_fileDescriptor0, []int{7, 1}
}

func (m *CMsgClientFriendsGroupsList_FriendGroupsMembership) GetUlSteamID() uint64 {
	if m != nil && m.UlSteamID != nil {
		return *m.UlSteamID
	}
	return 0
}

func (m *CMsgClientFriendsGroupsList_FriendGroupsMembership) GetNGroupID() int32 {
	if m != nil && m.NGroupID != nil {
		return *m.NGroupID
	}
	return 0
}

type CMsgClientPlayerNicknameList struct {
	Removal          *bool                                          `protobuf:"varint,1,opt,name=removal" json:"removal,omitempty"`
	Incremental      *bool                                          `protobuf:"varint,2,opt,name=incremental" json:"incremental,omitempty"`
	Nicknames        []*CMsgClientPlayerNicknameList_PlayerNickname `protobuf:"bytes,3,rep,name=nicknames" json:"nicknames,omitempty"`
	XXX_unrecognized []byte                                         `json:"-"`
}

func (m *CMsgClientPlayerNicknameList) Reset()                    { *m = CMsgClientPlayerNicknameList{} }
func (m *CMsgClientPlayerNicknameList) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientPlayerNicknameList) ProtoMessage()               {}
func (*CMsgClientPlayerNicknameList) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{8} }

func (m *CMsgClientPlayerNicknameList) GetRemoval() bool {
	if m != nil && m.Removal != nil {
		return *m.Removal
	}
	return false
}

func (m *CMsgClientPlayerNicknameList) GetIncremental() bool {
	if m != nil && m.Incremental != nil {
		return *m.Incremental
	}
	return false
}

func (m *CMsgClientPlayerNicknameList) GetNicknames() []*CMsgClientPlayerNicknameList_PlayerNickname {
	if m != nil {
		return m.Nicknames
	}
	return nil
}

type CMsgClientPlayerNicknameList_PlayerNickname struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	Nickname         *string `protobuf:"bytes,3,opt,name=nickname" json:"nickname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientPlayerNicknameList_PlayerNickname) Reset() {
	*m = CMsgClientPlayerNicknameList_PlayerNickname{}
}
func (m *CMsgClientPlayerNicknameList_PlayerNickname) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgClientPlayerNicknameList_PlayerNickname) ProtoMessage() {}
func (*CMsgClientPlayerNicknameList_PlayerNickname) Descriptor() ([]byte, []int) {
	return client_server_friends_fileDescriptor0, []int{8, 0}
}

func (m *CMsgClientPlayerNicknameList_PlayerNickname) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CMsgClientPlayerNicknameList_PlayerNickname) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

type CMsgClientSetPlayerNickname struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	Nickname         *string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientSetPlayerNickname) Reset()                    { *m = CMsgClientSetPlayerNickname{} }
func (m *CMsgClientSetPlayerNickname) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientSetPlayerNickname) ProtoMessage()               {}
func (*CMsgClientSetPlayerNickname) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{9} }

func (m *CMsgClientSetPlayerNickname) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CMsgClientSetPlayerNickname) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

type CMsgClientSetPlayerNicknameResponse struct {
	Eresult          *uint32 `protobuf:"varint,1,opt,name=eresult" json:"eresult,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientSetPlayerNicknameResponse) Reset()         { *m = CMsgClientSetPlayerNicknameResponse{} }
func (m *CMsgClientSetPlayerNicknameResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgClientSetPlayerNicknameResponse) ProtoMessage()    {}
func (*CMsgClientSetPlayerNicknameResponse) Descriptor() ([]byte, []int) {
	return client_server_friends_fileDescriptor0, []int{10}
}

func (m *CMsgClientSetPlayerNicknameResponse) GetEresult() uint32 {
	if m != nil && m.Eresult != nil {
		return *m.Eresult
	}
	return 0
}

type CMsgClientRequestFriendData struct {
	PersonaStateRequested *uint32  `protobuf:"varint,1,opt,name=persona_state_requested,json=personaStateRequested" json:"persona_state_requested,omitempty"`
	Friends               []uint64 `protobuf:"fixed64,2,rep,name=friends" json:"friends,omitempty"`
	XXX_unrecognized      []byte   `json:"-"`
}

func (m *CMsgClientRequestFriendData) Reset()                    { *m = CMsgClientRequestFriendData{} }
func (m *CMsgClientRequestFriendData) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientRequestFriendData) ProtoMessage()               {}
func (*CMsgClientRequestFriendData) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{11} }

func (m *CMsgClientRequestFriendData) GetPersonaStateRequested() uint32 {
	if m != nil && m.PersonaStateRequested != nil {
		return *m.PersonaStateRequested
	}
	return 0
}

func (m *CMsgClientRequestFriendData) GetFriends() []uint64 {
	if m != nil {
		return m.Friends
	}
	return nil
}

type CMsgClientChangeStatus struct {
	PersonaState        *uint32 `protobuf:"varint,1,opt,name=persona_state,json=personaState" json:"persona_state,omitempty"`
	PlayerName          *string `protobuf:"bytes,2,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
	IsAutoGeneratedName *bool   `protobuf:"varint,3,opt,name=is_auto_generated_name,json=isAutoGeneratedName" json:"is_auto_generated_name,omitempty"`
	HighPriority        *bool   `protobuf:"varint,4,opt,name=high_priority,json=highPriority" json:"high_priority,omitempty"`
	PersonaSetByUser    *bool   `protobuf:"varint,5,opt,name=persona_set_by_user,json=personaSetByUser" json:"persona_set_by_user,omitempty"`
	PersonaStateFlags   *uint32 `protobuf:"varint,6,opt,name=persona_state_flags,json=personaStateFlags,def=0" json:"persona_state_flags,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *CMsgClientChangeStatus) Reset()                    { *m = CMsgClientChangeStatus{} }
func (m *CMsgClientChangeStatus) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientChangeStatus) ProtoMessage()               {}
func (*CMsgClientChangeStatus) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{12} }

const Default_CMsgClientChangeStatus_PersonaStateFlags uint32 = 0

func (m *CMsgClientChangeStatus) GetPersonaState() uint32 {
	if m != nil && m.PersonaState != nil {
		return *m.PersonaState
	}
	return 0
}

func (m *CMsgClientChangeStatus) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func (m *CMsgClientChangeStatus) GetIsAutoGeneratedName() bool {
	if m != nil && m.IsAutoGeneratedName != nil {
		return *m.IsAutoGeneratedName
	}
	return false
}

func (m *CMsgClientChangeStatus) GetHighPriority() bool {
	if m != nil && m.HighPriority != nil {
		return *m.HighPriority
	}
	return false
}

func (m *CMsgClientChangeStatus) GetPersonaSetByUser() bool {
	if m != nil && m.PersonaSetByUser != nil {
		return *m.PersonaSetByUser
	}
	return false
}

func (m *CMsgClientChangeStatus) GetPersonaStateFlags() uint32 {
	if m != nil && m.PersonaStateFlags != nil {
		return *m.PersonaStateFlags
	}
	return Default_CMsgClientChangeStatus_PersonaStateFlags
}

type CMsgPersonaChangeResponse struct {
	Result           *uint32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	PlayerName       *string `protobuf:"bytes,2,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgPersonaChangeResponse) Reset()                    { *m = CMsgPersonaChangeResponse{} }
func (m *CMsgPersonaChangeResponse) String() string            { return proto.CompactTextString(m) }
func (*CMsgPersonaChangeResponse) ProtoMessage()               {}
func (*CMsgPersonaChangeResponse) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{13} }

func (m *CMsgPersonaChangeResponse) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *CMsgPersonaChangeResponse) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

type CMsgClientPersonaState struct {
	StatusFlags      *uint32                          `protobuf:"varint,1,opt,name=status_flags,json=statusFlags" json:"status_flags,omitempty"`
	Friends          []*CMsgClientPersonaState_Friend `protobuf:"bytes,2,rep,name=friends" json:"friends,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *CMsgClientPersonaState) Reset()                    { *m = CMsgClientPersonaState{} }
func (m *CMsgClientPersonaState) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientPersonaState) ProtoMessage()               {}
func (*CMsgClientPersonaState) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{14} }

func (m *CMsgClientPersonaState) GetStatusFlags() uint32 {
	if m != nil && m.StatusFlags != nil {
		return *m.StatusFlags
	}
	return 0
}

func (m *CMsgClientPersonaState) GetFriends() []*CMsgClientPersonaState_Friend {
	if m != nil {
		return m.Friends
	}
	return nil
}

type CMsgClientPersonaState_Friend struct {
	Friendid               *uint64 `protobuf:"fixed64,1,opt,name=friendid" json:"friendid,omitempty"`
	PersonaState           *uint32 `protobuf:"varint,2,opt,name=persona_state,json=personaState" json:"persona_state,omitempty"`
	GamePlayedAppId        *uint32 `protobuf:"varint,3,opt,name=game_played_app_id,json=gamePlayedAppId" json:"game_played_app_id,omitempty"`
	GameServerIp           *uint32 `protobuf:"varint,4,opt,name=game_server_ip,json=gameServerIp" json:"game_server_ip,omitempty"`
	GameServerPort         *uint32 `protobuf:"varint,5,opt,name=game_server_port,json=gameServerPort" json:"game_server_port,omitempty"`
	PersonaStateFlags      *uint32 `protobuf:"varint,6,opt,name=persona_state_flags,json=personaStateFlags" json:"persona_state_flags,omitempty"`
	OnlineSessionInstances *uint32 `protobuf:"varint,7,opt,name=online_session_instances,json=onlineSessionInstances" json:"online_session_instances,omitempty"`
	PublishedInstanceId    *uint32 `protobuf:"varint,8,opt,name=published_instance_id,json=publishedInstanceId" json:"published_instance_id,omitempty"`
	PersonaSetByUser       *bool   `protobuf:"varint,10,opt,name=persona_set_by_user,json=personaSetByUser" json:"persona_set_by_user,omitempty"`
	PlayerName             *string `protobuf:"bytes,15,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
	QueryPort              *uint32 `protobuf:"varint,20,opt,name=query_port,json=queryPort" json:"query_port,omitempty"`
	SteamidSource          *uint64 `protobuf:"fixed64,25,opt,name=steamid_source,json=steamidSource" json:"steamid_source,omitempty"`
	AvatarHash             []byte  `protobuf:"bytes,31,opt,name=avatar_hash,json=avatarHash" json:"avatar_hash,omitempty"`
	LastLogoff             *uint32 `protobuf:"varint,45,opt,name=last_logoff,json=lastLogoff" json:"last_logoff,omitempty"`
	LastLogon              *uint32 `protobuf:"varint,46,opt,name=last_logon,json=lastLogon" json:"last_logon,omitempty"`
	ClanRank               *uint32 `protobuf:"varint,50,opt,name=clan_rank,json=clanRank" json:"clan_rank,omitempty"`
	GameName               *string `protobuf:"bytes,55,opt,name=game_name,json=gameName" json:"game_name,omitempty"`
	Gameid                 *uint64 `protobuf:"fixed64,56,opt,name=gameid" json:"gameid,omitempty"`
	GameDataBlob           []byte  `protobuf:"bytes,60,opt,name=game_data_blob,json=gameDataBlob" json:"game_data_blob,omitempty"`
	ClanTag                *string `protobuf:"bytes,65,opt,name=clan_tag,json=clanTag" json:"clan_tag,omitempty"`
	FacebookName           *string `protobuf:"bytes,66,opt,name=facebook_name,json=facebookName" json:"facebook_name,omitempty"`
	FacebookId             *uint64 `protobuf:"varint,67,opt,name=facebook_id,json=facebookId" json:"facebook_id,omitempty"`
	XXX_unrecognized       []byte  `json:"-"`
}

func (m *CMsgClientPersonaState_Friend) Reset()         { *m = CMsgClientPersonaState_Friend{} }
func (m *CMsgClientPersonaState_Friend) String() string { return proto.CompactTextString(m) }
func (*CMsgClientPersonaState_Friend) ProtoMessage()    {}
func (*CMsgClientPersonaState_Friend) Descriptor() ([]byte, []int) {
	return client_server_friends_fileDescriptor0, []int{14, 0}
}

func (m *CMsgClientPersonaState_Friend) GetFriendid() uint64 {
	if m != nil && m.Friendid != nil {
		return *m.Friendid
	}
	return 0
}

func (m *CMsgClientPersonaState_Friend) GetPersonaState() uint32 {
	if m != nil && m.PersonaState != nil {
		return *m.PersonaState
	}
	return 0
}

func (m *CMsgClientPersonaState_Friend) GetGamePlayedAppId() uint32 {
	if m != nil && m.GamePlayedAppId != nil {
		return *m.GamePlayedAppId
	}
	return 0
}

func (m *CMsgClientPersonaState_Friend) GetGameServerIp() uint32 {
	if m != nil && m.GameServerIp != nil {
		return *m.GameServerIp
	}
	return 0
}

func (m *CMsgClientPersonaState_Friend) GetGameServerPort() uint32 {
	if m != nil && m.GameServerPort != nil {
		return *m.GameServerPort
	}
	return 0
}

func (m *CMsgClientPersonaState_Friend) GetPersonaStateFlags() uint32 {
	if m != nil && m.PersonaStateFlags != nil {
		return *m.PersonaStateFlags
	}
	return 0
}

func (m *CMsgClientPersonaState_Friend) GetOnlineSessionInstances() uint32 {
	if m != nil && m.OnlineSessionInstances != nil {
		return *m.OnlineSessionInstances
	}
	return 0
}

func (m *CMsgClientPersonaState_Friend) GetPublishedInstanceId() uint32 {
	if m != nil && m.PublishedInstanceId != nil {
		return *m.PublishedInstanceId
	}
	return 0
}

func (m *CMsgClientPersonaState_Friend) GetPersonaSetByUser() bool {
	if m != nil && m.PersonaSetByUser != nil {
		return *m.PersonaSetByUser
	}
	return false
}

func (m *CMsgClientPersonaState_Friend) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func (m *CMsgClientPersonaState_Friend) GetQueryPort() uint32 {
	if m != nil && m.QueryPort != nil {
		return *m.QueryPort
	}
	return 0
}

func (m *CMsgClientPersonaState_Friend) GetSteamidSource() uint64 {
	if m != nil && m.SteamidSource != nil {
		return *m.SteamidSource
	}
	return 0
}

func (m *CMsgClientPersonaState_Friend) GetAvatarHash() []byte {
	if m != nil {
		return m.AvatarHash
	}
	return nil
}

func (m *CMsgClientPersonaState_Friend) GetLastLogoff() uint32 {
	if m != nil && m.LastLogoff != nil {
		return *m.LastLogoff
	}
	return 0
}

func (m *CMsgClientPersonaState_Friend) GetLastLogon() uint32 {
	if m != nil && m.LastLogon != nil {
		return *m.LastLogon
	}
	return 0
}

func (m *CMsgClientPersonaState_Friend) GetClanRank() uint32 {
	if m != nil && m.ClanRank != nil {
		return *m.ClanRank
	}
	return 0
}

func (m *CMsgClientPersonaState_Friend) GetGameName() string {
	if m != nil && m.GameName != nil {
		return *m.GameName
	}
	return ""
}

func (m *CMsgClientPersonaState_Friend) GetGameid() uint64 {
	if m != nil && m.Gameid != nil {
		return *m.Gameid
	}
	return 0
}

func (m *CMsgClientPersonaState_Friend) GetGameDataBlob() []byte {
	if m != nil {
		return m.GameDataBlob
	}
	return nil
}

func (m *CMsgClientPersonaState_Friend) GetClanTag() string {
	if m != nil && m.ClanTag != nil {
		return *m.ClanTag
	}
	return ""
}

func (m *CMsgClientPersonaState_Friend) GetFacebookName() string {
	if m != nil && m.FacebookName != nil {
		return *m.FacebookName
	}
	return ""
}

func (m *CMsgClientPersonaState_Friend) GetFacebookId() uint64 {
	if m != nil && m.FacebookId != nil {
		return *m.FacebookId
	}
	return 0
}

type CMsgClientFriendProfileInfo struct {
	SteamidFriend    *uint64 `protobuf:"fixed64,1,opt,name=steamid_friend,json=steamidFriend" json:"steamid_friend,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientFriendProfileInfo) Reset()                    { *m = CMsgClientFriendProfileInfo{} }
func (m *CMsgClientFriendProfileInfo) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientFriendProfileInfo) ProtoMessage()               {}
func (*CMsgClientFriendProfileInfo) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{15} }

func (m *CMsgClientFriendProfileInfo) GetSteamidFriend() uint64 {
	if m != nil && m.SteamidFriend != nil {
		return *m.SteamidFriend
	}
	return 0
}

type CMsgClientFriendProfileInfoResponse struct {
	Eresult          *int32  `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	SteamidFriend    *uint64 `protobuf:"fixed64,2,opt,name=steamid_friend,json=steamidFriend" json:"steamid_friend,omitempty"`
	TimeCreated      *uint32 `protobuf:"varint,3,opt,name=time_created,json=timeCreated" json:"time_created,omitempty"`
	RealName         *string `protobuf:"bytes,4,opt,name=real_name,json=realName" json:"real_name,omitempty"`
	CityName         *string `protobuf:"bytes,5,opt,name=city_name,json=cityName" json:"city_name,omitempty"`
	StateName        *string `protobuf:"bytes,6,opt,name=state_name,json=stateName" json:"state_name,omitempty"`
	CountryName      *string `protobuf:"bytes,7,opt,name=country_name,json=countryName" json:"country_name,omitempty"`
	Headline         *string `protobuf:"bytes,8,opt,name=headline" json:"headline,omitempty"`
	Summary          *string `protobuf:"bytes,9,opt,name=summary" json:"summary,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientFriendProfileInfoResponse) Reset()         { *m = CMsgClientFriendProfileInfoResponse{} }
func (m *CMsgClientFriendProfileInfoResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgClientFriendProfileInfoResponse) ProtoMessage()    {}
func (*CMsgClientFriendProfileInfoResponse) Descriptor() ([]byte, []int) {
	return client_server_friends_fileDescriptor0, []int{16}
}

const Default_CMsgClientFriendProfileInfoResponse_Eresult int32 = 2

func (m *CMsgClientFriendProfileInfoResponse) GetEresult() int32 {
	if m != nil && m.Eresult != nil {
		return *m.Eresult
	}
	return Default_CMsgClientFriendProfileInfoResponse_Eresult
}

func (m *CMsgClientFriendProfileInfoResponse) GetSteamidFriend() uint64 {
	if m != nil && m.SteamidFriend != nil {
		return *m.SteamidFriend
	}
	return 0
}

func (m *CMsgClientFriendProfileInfoResponse) GetTimeCreated() uint32 {
	if m != nil && m.TimeCreated != nil {
		return *m.TimeCreated
	}
	return 0
}

func (m *CMsgClientFriendProfileInfoResponse) GetRealName() string {
	if m != nil && m.RealName != nil {
		return *m.RealName
	}
	return ""
}

func (m *CMsgClientFriendProfileInfoResponse) GetCityName() string {
	if m != nil && m.CityName != nil {
		return *m.CityName
	}
	return ""
}

func (m *CMsgClientFriendProfileInfoResponse) GetStateName() string {
	if m != nil && m.StateName != nil {
		return *m.StateName
	}
	return ""
}

func (m *CMsgClientFriendProfileInfoResponse) GetCountryName() string {
	if m != nil && m.CountryName != nil {
		return *m.CountryName
	}
	return ""
}

func (m *CMsgClientFriendProfileInfoResponse) GetHeadline() string {
	if m != nil && m.Headline != nil {
		return *m.Headline
	}
	return ""
}

func (m *CMsgClientFriendProfileInfoResponse) GetSummary() string {
	if m != nil && m.Summary != nil {
		return *m.Summary
	}
	return ""
}

type CMsgClientCreateFriendsGroup struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	Groupname        *string `protobuf:"bytes,2,opt,name=groupname" json:"groupname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientCreateFriendsGroup) Reset()                    { *m = CMsgClientCreateFriendsGroup{} }
func (m *CMsgClientCreateFriendsGroup) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientCreateFriendsGroup) ProtoMessage()               {}
func (*CMsgClientCreateFriendsGroup) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{17} }

func (m *CMsgClientCreateFriendsGroup) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CMsgClientCreateFriendsGroup) GetGroupname() string {
	if m != nil && m.Groupname != nil {
		return *m.Groupname
	}
	return ""
}

type CMsgClientCreateFriendsGroupResponse struct {
	Eresult          *uint32 `protobuf:"varint,1,opt,name=eresult" json:"eresult,omitempty"`
	Groupid          *int32  `protobuf:"varint,2,opt,name=groupid" json:"groupid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientCreateFriendsGroupResponse) Reset()         { *m = CMsgClientCreateFriendsGroupResponse{} }
func (m *CMsgClientCreateFriendsGroupResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgClientCreateFriendsGroupResponse) ProtoMessage()    {}
func (*CMsgClientCreateFriendsGroupResponse) Descriptor() ([]byte, []int) {
	return client_server_friends_fileDescriptor0, []int{18}
}

func (m *CMsgClientCreateFriendsGroupResponse) GetEresult() uint32 {
	if m != nil && m.Eresult != nil {
		return *m.Eresult
	}
	return 0
}

func (m *CMsgClientCreateFriendsGroupResponse) GetGroupid() int32 {
	if m != nil && m.Groupid != nil {
		return *m.Groupid
	}
	return 0
}

type CMsgClientDeleteFriendsGroup struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	Groupid          *int32  `protobuf:"varint,2,opt,name=groupid" json:"groupid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientDeleteFriendsGroup) Reset()                    { *m = CMsgClientDeleteFriendsGroup{} }
func (m *CMsgClientDeleteFriendsGroup) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientDeleteFriendsGroup) ProtoMessage()               {}
func (*CMsgClientDeleteFriendsGroup) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{19} }

func (m *CMsgClientDeleteFriendsGroup) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CMsgClientDeleteFriendsGroup) GetGroupid() int32 {
	if m != nil && m.Groupid != nil {
		return *m.Groupid
	}
	return 0
}

type CMsgClientDeleteFriendsGroupResponse struct {
	Eresult          *uint32 `protobuf:"varint,1,opt,name=eresult" json:"eresult,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientDeleteFriendsGroupResponse) Reset()         { *m = CMsgClientDeleteFriendsGroupResponse{} }
func (m *CMsgClientDeleteFriendsGroupResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgClientDeleteFriendsGroupResponse) ProtoMessage()    {}
func (*CMsgClientDeleteFriendsGroupResponse) Descriptor() ([]byte, []int) {
	return client_server_friends_fileDescriptor0, []int{20}
}

func (m *CMsgClientDeleteFriendsGroupResponse) GetEresult() uint32 {
	if m != nil && m.Eresult != nil {
		return *m.Eresult
	}
	return 0
}

type CMsgClientRenameFriendsGroup struct {
	Groupid          *int32  `protobuf:"varint,1,opt,name=groupid" json:"groupid,omitempty"`
	Groupname        *string `protobuf:"bytes,2,opt,name=groupname" json:"groupname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientRenameFriendsGroup) Reset()                    { *m = CMsgClientRenameFriendsGroup{} }
func (m *CMsgClientRenameFriendsGroup) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientRenameFriendsGroup) ProtoMessage()               {}
func (*CMsgClientRenameFriendsGroup) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{21} }

func (m *CMsgClientRenameFriendsGroup) GetGroupid() int32 {
	if m != nil && m.Groupid != nil {
		return *m.Groupid
	}
	return 0
}

func (m *CMsgClientRenameFriendsGroup) GetGroupname() string {
	if m != nil && m.Groupname != nil {
		return *m.Groupname
	}
	return ""
}

type CMsgClientRenameFriendsGroupResponse struct {
	Eresult          *uint32 `protobuf:"varint,1,opt,name=eresult" json:"eresult,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientRenameFriendsGroupResponse) Reset()         { *m = CMsgClientRenameFriendsGroupResponse{} }
func (m *CMsgClientRenameFriendsGroupResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgClientRenameFriendsGroupResponse) ProtoMessage()    {}
func (*CMsgClientRenameFriendsGroupResponse) Descriptor() ([]byte, []int) {
	return client_server_friends_fileDescriptor0, []int{22}
}

func (m *CMsgClientRenameFriendsGroupResponse) GetEresult() uint32 {
	if m != nil && m.Eresult != nil {
		return *m.Eresult
	}
	return 0
}

type CMsgClientAddFriendToGroup struct {
	Groupid          *int32  `protobuf:"varint,1,opt,name=groupid" json:"groupid,omitempty"`
	Steamiduser      *uint64 `protobuf:"fixed64,2,opt,name=steamiduser" json:"steamiduser,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientAddFriendToGroup) Reset()                    { *m = CMsgClientAddFriendToGroup{} }
func (m *CMsgClientAddFriendToGroup) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientAddFriendToGroup) ProtoMessage()               {}
func (*CMsgClientAddFriendToGroup) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{23} }

func (m *CMsgClientAddFriendToGroup) GetGroupid() int32 {
	if m != nil && m.Groupid != nil {
		return *m.Groupid
	}
	return 0
}

func (m *CMsgClientAddFriendToGroup) GetSteamiduser() uint64 {
	if m != nil && m.Steamiduser != nil {
		return *m.Steamiduser
	}
	return 0
}

type CMsgClientAddFriendToGroupResponse struct {
	Eresult          *uint32 `protobuf:"varint,1,opt,name=eresult" json:"eresult,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientAddFriendToGroupResponse) Reset()         { *m = CMsgClientAddFriendToGroupResponse{} }
func (m *CMsgClientAddFriendToGroupResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgClientAddFriendToGroupResponse) ProtoMessage()    {}
func (*CMsgClientAddFriendToGroupResponse) Descriptor() ([]byte, []int) {
	return client_server_friends_fileDescriptor0, []int{24}
}

func (m *CMsgClientAddFriendToGroupResponse) GetEresult() uint32 {
	if m != nil && m.Eresult != nil {
		return *m.Eresult
	}
	return 0
}

type CMsgClientRemoveFriendFromGroup struct {
	Groupid          *int32  `protobuf:"varint,1,opt,name=groupid" json:"groupid,omitempty"`
	Steamiduser      *uint64 `protobuf:"fixed64,2,opt,name=steamiduser" json:"steamiduser,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientRemoveFriendFromGroup) Reset()         { *m = CMsgClientRemoveFriendFromGroup{} }
func (m *CMsgClientRemoveFriendFromGroup) String() string { return proto.CompactTextString(m) }
func (*CMsgClientRemoveFriendFromGroup) ProtoMessage()    {}
func (*CMsgClientRemoveFriendFromGroup) Descriptor() ([]byte, []int) {
	return client_server_friends_fileDescriptor0, []int{25}
}

func (m *CMsgClientRemoveFriendFromGroup) GetGroupid() int32 {
	if m != nil && m.Groupid != nil {
		return *m.Groupid
	}
	return 0
}

func (m *CMsgClientRemoveFriendFromGroup) GetSteamiduser() uint64 {
	if m != nil && m.Steamiduser != nil {
		return *m.Steamiduser
	}
	return 0
}

type CMsgClientRemoveFriendFromGroupResponse struct {
	Eresult          *uint32 `protobuf:"varint,1,opt,name=eresult" json:"eresult,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientRemoveFriendFromGroupResponse) Reset() {
	*m = CMsgClientRemoveFriendFromGroupResponse{}
}
func (m *CMsgClientRemoveFriendFromGroupResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgClientRemoveFriendFromGroupResponse) ProtoMessage()    {}
func (*CMsgClientRemoveFriendFromGroupResponse) Descriptor() ([]byte, []int) {
	return client_server_friends_fileDescriptor0, []int{26}
}

func (m *CMsgClientRemoveFriendFromGroupResponse) GetEresult() uint32 {
	if m != nil && m.Eresult != nil {
		return *m.Eresult
	}
	return 0
}

type CMsgClientGetEmoticonList struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMsgClientGetEmoticonList) Reset()                    { *m = CMsgClientGetEmoticonList{} }
func (m *CMsgClientGetEmoticonList) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientGetEmoticonList) ProtoMessage()               {}
func (*CMsgClientGetEmoticonList) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{27} }

type CMsgClientEmoticonList struct {
	Emoticons        []*CMsgClientEmoticonList_Emoticon `protobuf:"bytes,1,rep,name=emoticons" json:"emoticons,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *CMsgClientEmoticonList) Reset()                    { *m = CMsgClientEmoticonList{} }
func (m *CMsgClientEmoticonList) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientEmoticonList) ProtoMessage()               {}
func (*CMsgClientEmoticonList) Descriptor() ([]byte, []int) { return client_server_friends_fileDescriptor0, []int{28} }

func (m *CMsgClientEmoticonList) GetEmoticons() []*CMsgClientEmoticonList_Emoticon {
	if m != nil {
		return m.Emoticons
	}
	return nil
}

type CMsgClientEmoticonList_Emoticon struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Count            *int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgClientEmoticonList_Emoticon) Reset()         { *m = CMsgClientEmoticonList_Emoticon{} }
func (m *CMsgClientEmoticonList_Emoticon) String() string { return proto.CompactTextString(m) }
func (*CMsgClientEmoticonList_Emoticon) ProtoMessage()    {}
func (*CMsgClientEmoticonList_Emoticon) Descriptor() ([]byte, []int) {
	return client_server_friends_fileDescriptor0, []int{28, 0}
}

func (m *CMsgClientEmoticonList_Emoticon) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CMsgClientEmoticonList_Emoticon) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*CMsgClientFriendMsg)(nil), "CMsgClientFriendMsg")
	proto.RegisterType((*CMsgClientFriendMsgIncoming)(nil), "CMsgClientFriendMsgIncoming")
	proto.RegisterType((*CMsgClientAddFriend)(nil), "CMsgClientAddFriend")
	proto.RegisterType((*CMsgClientAddFriendResponse)(nil), "CMsgClientAddFriendResponse")
	proto.RegisterType((*CMsgClientRemoveFriend)(nil), "CMsgClientRemoveFriend")
	proto.RegisterType((*CMsgClientHideFriend)(nil), "CMsgClientHideFriend")
	proto.RegisterType((*CMsgClientFriendsList)(nil), "CMsgClientFriendsList")
	proto.RegisterType((*CMsgClientFriendsList_Friend)(nil), "CMsgClientFriendsList.Friend")
	proto.RegisterType((*CMsgClientFriendsGroupsList)(nil), "CMsgClientFriendsGroupsList")
	proto.RegisterType((*CMsgClientFriendsGroupsList_FriendGroup)(nil), "CMsgClientFriendsGroupsList.FriendGroup")
	proto.RegisterType((*CMsgClientFriendsGroupsList_FriendGroupsMembership)(nil), "CMsgClientFriendsGroupsList.FriendGroupsMembership")
	proto.RegisterType((*CMsgClientPlayerNicknameList)(nil), "CMsgClientPlayerNicknameList")
	proto.RegisterType((*CMsgClientPlayerNicknameList_PlayerNickname)(nil), "CMsgClientPlayerNicknameList.PlayerNickname")
	proto.RegisterType((*CMsgClientSetPlayerNickname)(nil), "CMsgClientSetPlayerNickname")
	proto.RegisterType((*CMsgClientSetPlayerNicknameResponse)(nil), "CMsgClientSetPlayerNicknameResponse")
	proto.RegisterType((*CMsgClientRequestFriendData)(nil), "CMsgClientRequestFriendData")
	proto.RegisterType((*CMsgClientChangeStatus)(nil), "CMsgClientChangeStatus")
	proto.RegisterType((*CMsgPersonaChangeResponse)(nil), "CMsgPersonaChangeResponse")
	proto.RegisterType((*CMsgClientPersonaState)(nil), "CMsgClientPersonaState")
	proto.RegisterType((*CMsgClientPersonaState_Friend)(nil), "CMsgClientPersonaState.Friend")
	proto.RegisterType((*CMsgClientFriendProfileInfo)(nil), "CMsgClientFriendProfileInfo")
	proto.RegisterType((*CMsgClientFriendProfileInfoResponse)(nil), "CMsgClientFriendProfileInfoResponse")
	proto.RegisterType((*CMsgClientCreateFriendsGroup)(nil), "CMsgClientCreateFriendsGroup")
	proto.RegisterType((*CMsgClientCreateFriendsGroupResponse)(nil), "CMsgClientCreateFriendsGroupResponse")
	proto.RegisterType((*CMsgClientDeleteFriendsGroup)(nil), "CMsgClientDeleteFriendsGroup")
	proto.RegisterType((*CMsgClientDeleteFriendsGroupResponse)(nil), "CMsgClientDeleteFriendsGroupResponse")
	proto.RegisterType((*CMsgClientRenameFriendsGroup)(nil), "CMsgClientRenameFriendsGroup")
	proto.RegisterType((*CMsgClientRenameFriendsGroupResponse)(nil), "CMsgClientRenameFriendsGroupResponse")
	proto.RegisterType((*CMsgClientAddFriendToGroup)(nil), "CMsgClientAddFriendToGroup")
	proto.RegisterType((*CMsgClientAddFriendToGroupResponse)(nil), "CMsgClientAddFriendToGroupResponse")
	proto.RegisterType((*CMsgClientRemoveFriendFromGroup)(nil), "CMsgClientRemoveFriendFromGroup")
	proto.RegisterType((*CMsgClientRemoveFriendFromGroupResponse)(nil), "CMsgClientRemoveFriendFromGroupResponse")
	proto.RegisterType((*CMsgClientGetEmoticonList)(nil), "CMsgClientGetEmoticonList")
	proto.RegisterType((*CMsgClientEmoticonList)(nil), "CMsgClientEmoticonList")
	proto.RegisterType((*CMsgClientEmoticonList_Emoticon)(nil), "CMsgClientEmoticonList.Emoticon")
}

func init() { proto.RegisterFile("steammessages_clientserver_friends.proto", client_server_friends_fileDescriptor0) }

var client_server_friends_fileDescriptor0 = []byte{
	// 1715 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0x5f, 0x6f, 0x1b, 0xc7,
	0x11, 0x2f, 0xa9, 0x3f, 0x24, 0x87, 0xa2, 0x1d, 0xaf, 0x6c, 0xe5, 0x4c, 0x39, 0x31, 0x73, 0x4e,
	0x5b, 0xa2, 0x4d, 0x08, 0x57, 0x0e, 0x1a, 0x23, 0x08, 0xd2, 0xca, 0x92, 0x65, 0xb3, 0xb0, 0x53,
	0xe1, 0xa4, 0x14, 0x45, 0x80, 0xe2, 0xb0, 0xe4, 0x2d, 0xc9, 0x85, 0xef, 0x6e, 0x2f, 0xbb, 0x4b,
	0x23, 0x7c, 0xeb, 0x27, 0xe8, 0x07, 0xe8, 0x7b, 0x9f, 0xda, 0xc7, 0x3e, 0xf7, 0x63, 0xf4, 0x63,
	0xf4, 0x33, 0x14, 0x3b, 0xbb, 0x77, 0xbc, 0x13, 0x29, 0x89, 0x68, 0xdf, 0x38, 0xbf, 0x99, 0x9d,
	0xff, 0xbb, 0x33, 0x47, 0xe8, 0x2b, 0xcd, 0x68, 0x92, 0x30, 0xa5, 0xe8, 0x94, 0xa9, 0x70, 0x1c,
	0x73, 0x96, 0x6a, 0xc5, 0xe4, 0x7b, 0x26, 0xc3, 0x89, 0xe4, 0x2c, 0x8d, 0xd4, 0x20, 0x93, 0x42,
	0x8b, 0xae, 0x57, 0x95, 0x1c, 0x51, 0xc5, 0x2c, 0xc7, 0xff, 0x7b, 0x0d, 0xf6, 0x4f, 0xde, 0xaa,
	0xe9, 0x09, 0x1e, 0x3e, 0xc3, 0x53, 0x6f, 0xd5, 0x94, 0x78, 0xd0, 0xc0, 0x33, 0x3c, 0xf2, 0x6a,
	0xbd, 0x5a, 0x7f, 0x37, 0xc8, 0x49, 0xf2, 0x33, 0xb8, 0x3b, 0x9e, 0x51, 0x1d, 0xb2, 0x54, 0xcb,
	0x45, 0xa8, 0x17, 0x19, 0xf3, 0xea, 0xbd, 0x5a, 0x7f, 0x27, 0xe8, 0x18, 0xf8, 0xa5, 0x41, 0x2f,
	0x17, 0x19, 0x33, 0x1a, 0x9c, 0x41, 0x6f, 0xab, 0x57, 0xeb, 0xef, 0x05, 0x39, 0x49, 0x9e, 0x83,
	0x27, 0x35, 0x4f, 0xd8, 0xb3, 0xa3, 0xd0, 0x79, 0x6b, 0x28, 0xa5, 0x69, 0x92, 0x79, 0xdb, 0xbd,
	0x5a, 0xbf, 0x11, 0x1c, 0x38, 0xfe, 0x05, 0xb2, 0x2f, 0x73, 0xae, 0xff, 0x9f, 0x1a, 0x1c, 0xae,
	0xf1, 0x76, 0x98, 0x8e, 0x45, 0xc2, 0xd3, 0x29, 0xf9, 0x04, 0xf6, 0x9c, 0x9b, 0xe1, 0x44, 0x8a,
	0xc4, 0xb9, 0xde, 0x76, 0xd8, 0x99, 0x14, 0xc9, 0xc6, 0xee, 0x3f, 0x85, 0xfb, 0x46, 0x45, 0x18,
	0xf3, 0x84, 0x6b, 0x16, 0x85, 0x74, 0x3c, 0x16, 0xf3, 0x54, 0x63, 0x2c, 0xcd, 0x80, 0x18, 0xde,
	0x1b, 0xcb, 0x3a, 0xb6, 0x9c, 0x72, 0xc0, 0xdb, 0x9b, 0x07, 0xbc, 0x73, 0x63, 0xc0, 0x8b, 0x72,
	0x75, 0x8e, 0xa3, 0xc8, 0x86, 0x4c, 0x3e, 0x85, 0x3b, 0x79, 0x9c, 0x5a, 0x84, 0x34, 0xca, 0x8b,
	0x94, 0x47, 0x7f, 0x29, 0x8e, 0xa3, 0x88, 0x7c, 0x0d, 0x87, 0xce, 0xeb, 0x94, 0x26, 0x2c, 0x14,
	0x32, 0x64, 0x09, 0xe5, 0x71, 0x7e, 0xc4, 0x84, 0xdd, 0x0a, 0x3e, 0x2c, 0x89, 0xfc, 0x5e, 0xbe,
	0x34, 0x02, 0x78, 0xda, 0xff, 0x4b, 0x25, 0xd7, 0x85, 0xed, 0x80, 0xa9, 0x4c, 0xa4, 0x8a, 0x91,
	0x43, 0x68, 0x30, 0xc9, 0xd4, 0x3c, 0xd6, 0x68, 0x7c, 0xe7, 0xab, 0xda, 0x51, 0x90, 0x23, 0x85,
	0x83, 0x21, 0x8f, 0x8c, 0x2d, 0x66, 0xad, 0xe5, 0x0e, 0x0e, 0xa3, 0x63, 0x83, 0x91, 0xcf, 0x80,
	0x64, 0x4c, 0x2a, 0x91, 0xd2, 0x10, 0x3d, 0xb4, 0x92, 0x5b, 0xe8, 0xd7, 0x07, 0x8e, 0xf3, 0x2d,
	0x4d, 0x18, 0x4a, 0xfb, 0x5f, 0xc0, 0xc1, 0xd2, 0x9f, 0x80, 0x25, 0xe2, 0x3d, 0x73, 0xe9, 0xe8,
	0x42, 0xd3, 0xf6, 0x7b, 0xd1, 0xad, 0x05, 0xed, 0x9f, 0xc1, 0xfd, 0xe5, 0xa9, 0xd7, 0x3c, 0xda,
	0xe0, 0x0c, 0x21, 0xb0, 0x3d, 0xe3, 0x91, 0x6d, 0x8c, 0x66, 0x80, 0xbf, 0xfd, 0x7f, 0xd7, 0xe1,
	0xc1, 0xd5, 0xd6, 0x53, 0x6f, 0xb8, 0xd2, 0xc4, 0x87, 0xbd, 0x11, 0x4f, 0xc7, 0x92, 0x25, 0x2c,
	0xd5, 0x34, 0x46, 0x6d, 0xcd, 0xa0, 0x82, 0x91, 0x2f, 0xa1, 0xe1, 0x6e, 0xa4, 0x57, 0xef, 0x6d,
	0xf5, 0xdb, 0x47, 0x1f, 0x0d, 0xd6, 0x2a, 0x1b, 0xb8, 0x24, 0xe7, 0xd2, 0xa4, 0x0f, 0x1f, 0x24,
	0xf4, 0x47, 0x77, 0x9d, 0xc3, 0x65, 0x0b, 0x76, 0x82, 0x3b, 0x09, 0xfd, 0xd1, 0x4a, 0x9f, 0x60,
	0xfb, 0x0d, 0x60, 0x9f, 0x8e, 0x35, 0x7f, 0xcf, 0xaa, 0xc2, 0xdb, 0x28, 0x7c, 0xcf, 0xb2, 0xca,
	0xf2, 0xbf, 0x80, 0x7b, 0xce, 0x88, 0xed, 0xf1, 0x70, 0xc6, 0x35, 0x76, 0x63, 0x33, 0xb8, 0x3b,
	0xc9, 0x3d, 0x4a, 0xb8, 0x7e, 0xcd, 0x75, 0xf7, 0x7b, 0xd8, 0x75, 0x69, 0xfb, 0x18, 0x60, 0x1e,
	0x5f, 0x49, 0x5c, 0x09, 0x21, 0x4f, 0x61, 0x9f, 0x59, 0x42, 0xb2, 0x98, 0x6a, 0x2e, 0x52, 0x35,
	0xe3, 0x19, 0x66, 0xb2, 0x13, 0xac, 0x63, 0xf9, 0x7f, 0xdb, 0x5a, 0xbd, 0xd3, 0xea, 0x95, 0x14,
	0xf3, 0xcc, 0xa6, 0xb7, 0x0b, 0xcd, 0x91, 0x34, 0xd5, 0x2e, 0x52, 0x5b, 0xd0, 0x2b, 0xa9, 0xaf,
	0xaf, 0x49, 0xfd, 0x1b, 0xd8, 0xb3, 0x56, 0xad, 0x4e, 0x6f, 0x0b, 0xf3, 0xdf, 0x1f, 0xdc, 0x60,
	0xd3, 0x55, 0x01, 0x81, 0xa0, 0x72, 0x9a, 0x7c, 0x07, 0xed, 0x84, 0x25, 0x23, 0x26, 0x8d, 0xef,
	0xca, 0xdb, 0x46, 0x65, 0xcf, 0x36, 0x55, 0xa6, 0xde, 0x16, 0x67, 0x83, 0xb2, 0x9e, 0xee, 0x5b,
	0x68, 0x97, 0xc4, 0x4c, 0xcc, 0x29, 0xfe, 0x1a, 0x9e, 0xda, 0xcb, 0x15, 0x14, 0xb4, 0x89, 0x59,
	0x69, 0x89, 0x94, 0xb9, 0x1b, 0xee, 0x1a, 0x57, 0xb0, 0x6e, 0x00, 0x07, 0xeb, 0xad, 0x92, 0x47,
	0xd0, 0x9a, 0xc7, 0x17, 0x78, 0x09, 0x4f, 0x5d, 0xf9, 0x96, 0x40, 0xc5, 0x6e, 0xbd, 0x6a, 0xd7,
	0xbc, 0xbd, 0x8f, 0x96, 0x61, 0x9e, 0xc7, 0x74, 0xc1, 0xe4, 0xb7, 0x7c, 0xfc, 0xce, 0xdc, 0x5c,
	0x2c, 0x94, 0x07, 0x8d, 0x6a, 0x9d, 0x72, 0x92, 0xf4, 0xa0, 0xbd, 0x5a, 0xa5, 0x32, 0x44, 0x7e,
	0x07, 0xad, 0xd4, 0xe9, 0xca, 0x2b, 0xf4, 0xd9, 0xe0, 0x26, 0x6b, 0x83, 0x2a, 0x14, 0x2c, 0x8f,
	0x77, 0xcf, 0xe0, 0x4e, 0x95, 0x79, 0xc3, 0x30, 0x33, 0x01, 0x3b, 0x29, 0xf7, 0xee, 0x14, 0xb4,
	0x7f, 0x51, 0xee, 0xcb, 0x0b, 0xa6, 0xff, 0x27, 0xa5, 0xf5, 0x2b, 0x4a, 0x7f, 0x03, 0x4f, 0x6e,
	0x50, 0x5a, 0x3c, 0xae, 0x5e, 0xf5, 0x71, 0xed, 0x14, 0x2f, 0xab, 0x2f, 0xca, 0x5e, 0x05, 0xec,
	0x87, 0x39, 0x53, 0xae, 0xe7, 0x4e, 0xa9, 0xa6, 0xe4, 0xd7, 0xf0, 0x61, 0xfe, 0xa4, 0x2a, 0x4d,
	0x35, 0x0b, 0xa5, 0x15, 0x61, 0x91, 0x53, 0xf4, 0xc0, 0xb1, 0x2f, 0x0c, 0x37, 0xc8, 0x99, 0xc6,
	0x60, 0xf9, 0x81, 0xda, 0x2d, 0x5e, 0x20, 0xff, 0xaf, 0xf5, 0xf2, 0xbb, 0x7b, 0x32, 0xa3, 0xe9,
	0x94, 0x99, 0xc3, 0x73, 0x45, 0x9e, 0x40, 0xa7, 0x62, 0xcc, 0x99, 0xd8, 0x2b, 0x9b, 0x20, 0x8f,
	0xa1, 0x9d, 0x61, 0x90, 0x61, 0x29, 0x21, 0x60, 0x21, 0xd3, 0xac, 0xe4, 0x19, 0x1c, 0x70, 0x15,
	0xd2, 0xb9, 0x16, 0xe1, 0x94, 0xa5, 0x4c, 0x52, 0x33, 0x6e, 0x8b, 0x8a, 0x34, 0x83, 0x7d, 0xae,
	0x8e, 0xe7, 0x5a, 0xbc, 0xca, 0x79, 0x78, 0xe8, 0x09, 0x74, 0x66, 0x7c, 0x3a, 0x0b, 0x33, 0xc9,
	0x85, 0xe4, 0x7a, 0x81, 0xef, 0x5c, 0x33, 0xd8, 0x33, 0xe0, 0xb9, 0xc3, 0xc8, 0xe7, 0xb0, 0x5f,
	0xf8, 0xc7, 0x74, 0x38, 0x5a, 0x84, 0x73, 0xc5, 0xa4, 0x7b, 0xe4, 0xf2, 0x01, 0x73, 0xc1, 0xf4,
	0x8b, 0xc5, 0x77, 0x8a, 0x49, 0xf2, 0xab, 0x92, 0x38, 0xe6, 0x6e, 0x12, 0xd3, 0xa9, 0xf2, 0x76,
	0x4d, 0x50, 0x5f, 0xd5, 0x9e, 0x06, 0xf7, 0xca, 0x71, 0x9d, 0x19, 0x9e, 0x7f, 0x09, 0x0f, 0x4d,
	0x6e, 0xce, 0x2d, 0xc3, 0x26, 0xa7, 0x28, 0xe2, 0x01, 0xec, 0x56, 0x6a, 0xe8, 0xa8, 0x5b, 0x33,
	0xe2, 0xff, 0xa3, 0x51, 0x4e, 0xf9, 0x79, 0x39, 0x9b, 0xb8, 0xe1, 0x98, 0xe4, 0x3b, 0xe7, 0xac,
	0xe6, 0xb6, 0xc5, 0xd0, 0x27, 0xf2, 0xfc, 0xea, 0xac, 0xf9, 0x78, 0xb0, 0x5e, 0xd9, 0xd5, 0x61,
	0xd3, 0xfd, 0xe7, 0x6e, 0xf1, 0xce, 0xdf, 0x34, 0x1e, 0x57, 0xca, 0x5e, 0x5f, 0x53, 0xf6, 0x5f,
	0x02, 0x99, 0x9a, 0x99, 0x8e, 0x61, 0x45, 0x21, 0xcd, 0xb2, 0x90, 0x47, 0x6e, 0x74, 0xdd, 0x35,
	0x1c, 0xec, 0xfc, 0xe8, 0x38, 0xcb, 0x86, 0xb8, 0xcf, 0xa0, 0xb0, 0xdb, 0x8e, 0x78, 0xe6, 0xc6,
	0xd6, 0x9e, 0x41, 0xed, 0x4e, 0x34, 0xcc, 0xcc, 0x2c, 0x2c, 0x4b, 0x65, 0x42, 0xda, 0x81, 0xd5,
	0x09, 0xee, 0x2c, 0xe5, 0xce, 0x85, 0xc4, 0x59, 0x78, 0x6d, 0x25, 0xd7, 0x94, 0xd1, 0x2c, 0x68,
	0x22, 0x8d, 0x79, 0x6a, 0x74, 0x2b, 0xc5, 0x45, 0x1a, 0xf2, 0x54, 0x69, 0x9a, 0x8e, 0x99, 0xf2,
	0x1a, 0x78, 0xe8, 0xc0, 0xf2, 0x2f, 0x2c, 0x7b, 0x98, 0x73, 0xc9, 0x11, 0x3c, 0xc8, 0xe6, 0xa3,
	0x98, 0xab, 0x19, 0x8b, 0x8a, 0x43, 0x26, 0xd2, 0xa6, 0x9d, 0x78, 0x05, 0x33, 0x3f, 0x32, 0x8c,
	0xae, 0x6b, 0x4b, 0xb8, 0xa6, 0x2d, 0xaf, 0xb4, 0xcb, 0xdd, 0x95, 0x0b, 0xf4, 0x11, 0xc0, 0x0f,
	0x73, 0x26, 0x17, 0x36, 0x23, 0xf7, 0xd1, 0x70, 0x0b, 0x11, 0x4c, 0xc6, 0x4f, 0x97, 0xcb, 0xa2,
	0x12, 0x73, 0x39, 0x66, 0xde, 0x43, 0x2c, 0x68, 0xc7, 0xa1, 0x17, 0x08, 0x1a, 0x33, 0xf4, 0x3d,
	0xd5, 0x54, 0x86, 0x33, 0xaa, 0x66, 0xde, 0x63, 0x5c, 0x61, 0xc1, 0x42, 0xaf, 0xa9, 0x9a, 0x19,
	0x81, 0x98, 0x2a, 0x1d, 0xc6, 0x62, 0x2a, 0x26, 0x13, 0xef, 0x73, 0xb4, 0x03, 0x06, 0x7a, 0x83,
	0x88, 0xf1, 0xa3, 0x10, 0x48, 0xbd, 0x81, 0xf5, 0x23, 0xe7, 0xa7, 0xe4, 0x10, 0x5a, 0xe3, 0x98,
	0xa6, 0xa1, 0xa4, 0xe9, 0x3b, 0xef, 0x08, 0xb9, 0x4d, 0x03, 0x04, 0x34, 0x7d, 0x67, 0x98, 0x58,
	0x5b, 0x0c, 0xf1, 0x4b, 0xfb, 0x68, 0x1a, 0x00, 0x03, 0x3c, 0x80, 0x5d, 0xf3, 0x9b, 0x47, 0xde,
	0x73, 0xf4, 0xdc, 0x51, 0x45, 0xdb, 0x44, 0x54, 0xd3, 0x70, 0x14, 0x8b, 0x91, 0xf7, 0x35, 0x7a,
	0x8d, 0x6d, 0x63, 0x9e, 0xc3, 0x17, 0xb1, 0x18, 0x91, 0x87, 0x80, 0x66, 0x42, 0x4d, 0xa7, 0xde,
	0x31, 0x6a, 0x6e, 0x18, 0xfa, 0x92, 0x4e, 0x4d, 0x27, 0x4f, 0xe8, 0x98, 0x8d, 0x84, 0x78, 0x67,
	0x2d, 0xbf, 0xb0, 0xc3, 0x34, 0x07, 0xd1, 0xfa, 0x63, 0x68, 0x17, 0x42, 0x3c, 0xf2, 0x4e, 0x7a,
	0xb5, 0xfe, 0x76, 0x00, 0x39, 0x34, 0x8c, 0xfc, 0xd3, 0xd5, 0x05, 0xe6, 0x5c, 0x8a, 0x09, 0x8f,
	0xd9, 0x30, 0x9d, 0x88, 0x72, 0xfe, 0xed, 0x15, 0x72, 0x17, 0xaa, 0x53, 0x7c, 0x96, 0x18, 0xd0,
	0xff, 0x57, 0xbd, 0x3c, 0x1a, 0x56, 0xd4, 0x6c, 0xb6, 0x77, 0xaf, 0xda, 0xaa, 0xaf, 0xb1, 0x65,
	0x5e, 0x11, 0xf3, 0xbd, 0x11, 0x8e, 0x25, 0x33, 0x2f, 0xaa, 0xbb, 0x96, 0x6d, 0x83, 0x9d, 0x58,
	0xc8, 0x14, 0x44, 0x32, 0x1a, 0xdb, 0xb4, 0x6c, 0xdb, 0x82, 0x18, 0x00, 0x53, 0x62, 0x4a, 0xc9,
	0xf5, 0xc2, 0x32, 0x77, 0x2c, 0xd3, 0x00, 0x79, 0x3b, 0xda, 0x4b, 0x87, 0xdc, 0x5d, 0xe4, 0xb6,
	0x10, 0x41, 0xf6, 0x27, 0xb0, 0x87, 0x9b, 0xa9, 0x74, 0xc7, 0x1b, 0x28, 0xd0, 0x76, 0x18, 0x8a,
	0x74, 0xa1, 0x39, 0x63, 0x34, 0x32, 0x17, 0x0e, 0xef, 0x51, 0x2b, 0x28, 0x68, 0x1c, 0xbb, 0xf3,
	0x24, 0xa1, 0x72, 0xe1, 0xb5, 0x6c, 0x31, 0x1d, 0xe9, 0xff, 0xa1, 0xbc, 0x9f, 0xd8, 0x30, 0xca,
	0xcb, 0xd8, 0x0d, 0x03, 0xfb, 0x11, 0xb4, 0xa6, 0x46, 0xa4, 0xf4, 0x1c, 0x2f, 0x01, 0xff, 0x7b,
	0xf8, 0xf4, 0x26, 0xbd, 0xb7, 0xcf, 0x6c, 0xc3, 0x41, 0x75, 0x3c, 0x72, 0x5b, 0x55, 0x4e, 0xfa,
	0x41, 0xd9, 0xe7, 0x53, 0x16, 0xb3, 0x8d, 0x7d, 0xbe, 0x5e, 0xe7, 0x6f, 0xcb, 0xfe, 0xae, 0xea,
	0xdc, 0x60, 0xc7, 0xa8, 0x64, 0x32, 0x60, 0x26, 0x0b, 0x57, 0xbd, 0xca, 0x6d, 0xd7, 0x2a, 0xb6,
	0x6f, 0xc9, 0x64, 0xc5, 0xb3, 0x55, 0xbd, 0x1b, 0x78, 0xf6, 0x47, 0xe8, 0xae, 0xf9, 0x26, 0xbd,
	0x14, 0xb7, 0xf9, 0xd5, 0x83, 0xfc, 0x4f, 0x00, 0x7c, 0x6a, 0xeb, 0x95, 0xff, 0x05, 0x0c, 0xe4,
	0x7f, 0x03, 0xfe, 0xf5, 0x9a, 0x37, 0xf0, 0xec, 0x4f, 0xf0, 0x78, 0xfd, 0xd7, 0xe9, 0x99, 0x14,
	0xc9, 0xff, 0xef, 0xde, 0x09, 0xfc, 0xfc, 0x16, 0xf5, 0x1b, 0xf8, 0x78, 0x68, 0xb7, 0x15, 0xab,
	0xe4, 0x15, 0xd3, 0x2f, 0x13, 0xa1, 0xf9, 0x58, 0xa4, 0x66, 0xa1, 0x36, 0xdf, 0xfb, 0xa5, 0xa5,
	0xa3, 0xcc, 0x22, 0xdf, 0x40, 0x8b, 0x39, 0xda, 0x6c, 0x1c, 0x66, 0xa7, 0xe8, 0x0d, 0xd6, 0xcb,
	0x0e, 0x72, 0x22, 0x58, 0x1e, 0xe9, 0x7e, 0x01, 0xcd, 0x1c, 0x36, 0xdf, 0xd6, 0xd8, 0x1c, 0x35,
	0x6c, 0x0e, 0xfc, 0x4d, 0xee, 0xc3, 0x8e, 0xfd, 0x58, 0xb5, 0x9d, 0x6c, 0x89, 0x17, 0x3b, 0xaf,
	0x6b, 0x7f, 0xae, 0xfd, 0xe4, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x39, 0x83, 0x85, 0x8f, 0xe6,
	0x12, 0x00, 0x00,
}
