// Code generated by protoc-gen-go.
// source: content_manifest.proto
// DO NOT EDIT!

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package protobuf is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package protobuf to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ContentManifestPayload struct {
	Mappings         []*ContentManifestPayload_FileMapping `protobuf:"bytes,1,rep,name=mappings" json:"mappings,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *ContentManifestPayload) Reset()                    { *m = ContentManifestPayload{} }
func (m *ContentManifestPayload) String() string            { return proto.CompactTextString(m) }
func (*ContentManifestPayload) ProtoMessage()               {}
func (*ContentManifestPayload) Descriptor() ([]byte, []int) { return content_manifest_fileDescriptor0, []int{0} }

func (m *ContentManifestPayload) GetMappings() []*ContentManifestPayload_FileMapping {
	if m != nil {
		return m.Mappings
	}
	return nil
}

type ContentManifestPayload_FileMapping struct {
	Filename         *string                                         `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Size             *uint64                                         `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Flags            *uint32                                         `protobuf:"varint,3,opt,name=flags" json:"flags,omitempty"`
	ShaFilename      []byte                                          `protobuf:"bytes,4,opt,name=sha_filename,json=shaFilename" json:"sha_filename,omitempty"`
	ShaContent       []byte                                          `protobuf:"bytes,5,opt,name=sha_content,json=shaContent" json:"sha_content,omitempty"`
	Chunks           []*ContentManifestPayload_FileMapping_ChunkData `protobuf:"bytes,6,rep,name=chunks" json:"chunks,omitempty"`
	Linktarget       *string                                         `protobuf:"bytes,7,opt,name=linktarget" json:"linktarget,omitempty"`
	XXX_unrecognized []byte                                          `json:"-"`
}

func (m *ContentManifestPayload_FileMapping) Reset()         { *m = ContentManifestPayload_FileMapping{} }
func (m *ContentManifestPayload_FileMapping) String() string { return proto.CompactTextString(m) }
func (*ContentManifestPayload_FileMapping) ProtoMessage()    {}
func (*ContentManifestPayload_FileMapping) Descriptor() ([]byte, []int) {
	return content_manifest_fileDescriptor0, []int{0, 0}
}

func (m *ContentManifestPayload_FileMapping) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *ContentManifestPayload_FileMapping) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *ContentManifestPayload_FileMapping) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *ContentManifestPayload_FileMapping) GetShaFilename() []byte {
	if m != nil {
		return m.ShaFilename
	}
	return nil
}

func (m *ContentManifestPayload_FileMapping) GetShaContent() []byte {
	if m != nil {
		return m.ShaContent
	}
	return nil
}

func (m *ContentManifestPayload_FileMapping) GetChunks() []*ContentManifestPayload_FileMapping_ChunkData {
	if m != nil {
		return m.Chunks
	}
	return nil
}

func (m *ContentManifestPayload_FileMapping) GetLinktarget() string {
	if m != nil && m.Linktarget != nil {
		return *m.Linktarget
	}
	return ""
}

type ContentManifestPayload_FileMapping_ChunkData struct {
	Sha              []byte  `protobuf:"bytes,1,opt,name=sha" json:"sha,omitempty"`
	Crc              *uint32 `protobuf:"fixed32,2,opt,name=crc" json:"crc,omitempty"`
	Offset           *uint64 `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	CbOriginal       *uint32 `protobuf:"varint,4,opt,name=cb_original,json=cbOriginal" json:"cb_original,omitempty"`
	CbCompressed     *uint32 `protobuf:"varint,5,opt,name=cb_compressed,json=cbCompressed" json:"cb_compressed,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ContentManifestPayload_FileMapping_ChunkData) Reset() {
	*m = ContentManifestPayload_FileMapping_ChunkData{}
}
func (m *ContentManifestPayload_FileMapping_ChunkData) String() string {
	return proto.CompactTextString(m)
}
func (*ContentManifestPayload_FileMapping_ChunkData) ProtoMessage() {}
func (*ContentManifestPayload_FileMapping_ChunkData) Descriptor() ([]byte, []int) {
	return content_manifest_fileDescriptor0, []int{0, 0, 0}
}

func (m *ContentManifestPayload_FileMapping_ChunkData) GetSha() []byte {
	if m != nil {
		return m.Sha
	}
	return nil
}

func (m *ContentManifestPayload_FileMapping_ChunkData) GetCrc() uint32 {
	if m != nil && m.Crc != nil {
		return *m.Crc
	}
	return 0
}

func (m *ContentManifestPayload_FileMapping_ChunkData) GetOffset() uint64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ContentManifestPayload_FileMapping_ChunkData) GetCbOriginal() uint32 {
	if m != nil && m.CbOriginal != nil {
		return *m.CbOriginal
	}
	return 0
}

func (m *ContentManifestPayload_FileMapping_ChunkData) GetCbCompressed() uint32 {
	if m != nil && m.CbCompressed != nil {
		return *m.CbCompressed
	}
	return 0
}

type ContentManifestMetadata struct {
	DepotId            *uint32 `protobuf:"varint,1,opt,name=depot_id,json=depotId" json:"depot_id,omitempty"`
	GidManifest        *uint64 `protobuf:"varint,2,opt,name=gid_manifest,json=gidManifest" json:"gid_manifest,omitempty"`
	CreationTime       *uint32 `protobuf:"varint,3,opt,name=creation_time,json=creationTime" json:"creation_time,omitempty"`
	FilenamesEncrypted *bool   `protobuf:"varint,4,opt,name=filenames_encrypted,json=filenamesEncrypted" json:"filenames_encrypted,omitempty"`
	CbDiskOriginal     *uint64 `protobuf:"varint,5,opt,name=cb_disk_original,json=cbDiskOriginal" json:"cb_disk_original,omitempty"`
	CbDiskCompressed   *uint64 `protobuf:"varint,6,opt,name=cb_disk_compressed,json=cbDiskCompressed" json:"cb_disk_compressed,omitempty"`
	UniqueChunks       *uint32 `protobuf:"varint,7,opt,name=unique_chunks,json=uniqueChunks" json:"unique_chunks,omitempty"`
	CrcEncrypted       *uint32 `protobuf:"varint,8,opt,name=crc_encrypted,json=crcEncrypted" json:"crc_encrypted,omitempty"`
	CrcClear           *uint32 `protobuf:"varint,9,opt,name=crc_clear,json=crcClear" json:"crc_clear,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *ContentManifestMetadata) Reset()                    { *m = ContentManifestMetadata{} }
func (m *ContentManifestMetadata) String() string            { return proto.CompactTextString(m) }
func (*ContentManifestMetadata) ProtoMessage()               {}
func (*ContentManifestMetadata) Descriptor() ([]byte, []int) { return content_manifest_fileDescriptor0, []int{1} }

func (m *ContentManifestMetadata) GetDepotId() uint32 {
	if m != nil && m.DepotId != nil {
		return *m.DepotId
	}
	return 0
}

func (m *ContentManifestMetadata) GetGidManifest() uint64 {
	if m != nil && m.GidManifest != nil {
		return *m.GidManifest
	}
	return 0
}

func (m *ContentManifestMetadata) GetCreationTime() uint32 {
	if m != nil && m.CreationTime != nil {
		return *m.CreationTime
	}
	return 0
}

func (m *ContentManifestMetadata) GetFilenamesEncrypted() bool {
	if m != nil && m.FilenamesEncrypted != nil {
		return *m.FilenamesEncrypted
	}
	return false
}

func (m *ContentManifestMetadata) GetCbDiskOriginal() uint64 {
	if m != nil && m.CbDiskOriginal != nil {
		return *m.CbDiskOriginal
	}
	return 0
}

func (m *ContentManifestMetadata) GetCbDiskCompressed() uint64 {
	if m != nil && m.CbDiskCompressed != nil {
		return *m.CbDiskCompressed
	}
	return 0
}

func (m *ContentManifestMetadata) GetUniqueChunks() uint32 {
	if m != nil && m.UniqueChunks != nil {
		return *m.UniqueChunks
	}
	return 0
}

func (m *ContentManifestMetadata) GetCrcEncrypted() uint32 {
	if m != nil && m.CrcEncrypted != nil {
		return *m.CrcEncrypted
	}
	return 0
}

func (m *ContentManifestMetadata) GetCrcClear() uint32 {
	if m != nil && m.CrcClear != nil {
		return *m.CrcClear
	}
	return 0
}

type ContentManifestSignature struct {
	Signature        []byte `protobuf:"bytes,1,opt,name=signature" json:"signature,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ContentManifestSignature) Reset()                    { *m = ContentManifestSignature{} }
func (m *ContentManifestSignature) String() string            { return proto.CompactTextString(m) }
func (*ContentManifestSignature) ProtoMessage()               {}
func (*ContentManifestSignature) Descriptor() ([]byte, []int) { return content_manifest_fileDescriptor0, []int{2} }

func (m *ContentManifestSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*ContentManifestPayload)(nil), "ContentManifestPayload")
	proto.RegisterType((*ContentManifestPayload_FileMapping)(nil), "ContentManifestPayload.FileMapping")
	proto.RegisterType((*ContentManifestPayload_FileMapping_ChunkData)(nil), "ContentManifestPayload.FileMapping.ChunkData")
	proto.RegisterType((*ContentManifestMetadata)(nil), "ContentManifestMetadata")
	proto.RegisterType((*ContentManifestSignature)(nil), "ContentManifestSignature")
}

func init() { proto.RegisterFile("content_manifest.proto", content_manifest_fileDescriptor0) }

var content_manifest_fileDescriptor0 = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x25, 0x9b, 0x7e, 0x24, 0xd3, 0x06, 0x55, 0x06, 0x95, 0x50, 0x10, 0x1f, 0xdd, 0x4b, 0x0f,
	0x50, 0x24, 0x4e, 0xdc, 0x90, 0xc8, 0xee, 0x0a, 0x0e, 0x15, 0xc8, 0x70, 0x8f, 0x5c, 0xc7, 0xc9,
	0x5a, 0x4d, 0x9d, 0x10, 0xbb, 0x87, 0xe5, 0xc4, 0x1f, 0x80, 0x1f, 0x8a, 0xf8, 0x11, 0xd8, 0x8e,
	0x93, 0x56, 0x2b, 0x0e, 0x7b, 0xf3, 0x7b, 0xf3, 0x3c, 0x7e, 0x6f, 0xc6, 0x30, 0xa7, 0x95, 0x50,
	0x4c, 0xa8, 0x74, 0x4f, 0x04, 0xcf, 0x99, 0x54, 0xeb, 0xba, 0xa9, 0x54, 0xb5, 0xfc, 0xe3, 0xc3,
	0x3c, 0x69, 0x4b, 0x1b, 0x57, 0xf9, 0x42, 0x6e, 0xca, 0x8a, 0x64, 0xe8, 0x3d, 0x04, 0x7b, 0x52,
	0xd7, 0x5c, 0x14, 0x32, 0xf6, 0x5e, 0xf8, 0xab, 0xc9, 0xdb, 0xf3, 0xf5, 0xff, 0xa5, 0xeb, 0x2b,
	0x5e, 0xb2, 0x4d, 0xab, 0xc5, 0xfd, 0xa5, 0xc5, 0x6f, 0x1f, 0x26, 0x27, 0x15, 0xb4, 0x80, 0x20,
	0xd7, 0x50, 0x90, 0x3d, 0xd3, 0x0d, 0xbd, 0x55, 0x88, 0x7b, 0x8c, 0x10, 0x0c, 0x24, 0xff, 0xc1,
	0xe2, 0x33, 0xcd, 0x0f, 0xb0, 0x3d, 0xa3, 0x87, 0x30, 0xcc, 0x4b, 0xa2, 0x5f, 0xf7, 0x35, 0x19,
	0xe1, 0x16, 0xa0, 0x97, 0x30, 0x95, 0xd7, 0x24, 0xed, 0x3b, 0x0d, 0x74, 0x71, 0x8a, 0x27, 0x9a,
	0xbb, 0xea, 0x9a, 0x3d, 0x07, 0x03, 0x53, 0x17, 0x39, 0x1e, 0x5a, 0x05, 0x68, 0xca, 0xd9, 0x47,
	0x97, 0x30, 0xa2, 0xd7, 0x07, 0xb1, 0x93, 0xf1, 0xc8, 0x06, 0x7b, 0x7d, 0x87, 0x60, 0xeb, 0xc4,
	0xdc, 0xb8, 0x20, 0x8a, 0x60, 0x77, 0x19, 0x3d, 0x03, 0x28, 0xb9, 0xd8, 0x29, 0xd2, 0x14, 0x4c,
	0xc5, 0x63, 0x1b, 0xe9, 0x84, 0x59, 0xfc, 0xf2, 0x20, 0xec, 0x6f, 0xa1, 0x19, 0xf8, 0xda, 0x82,
	0x4d, 0x3e, 0xc5, 0xe6, 0x68, 0x18, 0xda, 0x50, 0x9b, 0x79, 0x8c, 0xcd, 0x11, 0xcd, 0x61, 0x54,
	0xe5, 0xb9, 0xd4, 0xdd, 0x7c, 0x3b, 0x08, 0x87, 0x4c, 0x22, 0xba, 0x4d, 0xab, 0x86, 0x17, 0x5c,
	0x90, 0xd2, 0x66, 0x8e, 0x30, 0xd0, 0xed, 0x67, 0xc7, 0xa0, 0x73, 0x88, 0xb4, 0x80, 0x56, 0xfb,
	0xba, 0x61, 0x52, 0xb2, 0xcc, 0x86, 0x8e, 0xf0, 0x94, 0x6e, 0x93, 0x9e, 0x5b, 0xfe, 0x3d, 0x83,
	0x47, 0xb7, 0x82, 0x6e, 0x98, 0x22, 0x99, 0x71, 0xf7, 0x18, 0x82, 0x8c, 0xd5, 0x95, 0x4a, 0x79,
	0x66, 0x2d, 0x46, 0x78, 0x6c, 0xf1, 0xa7, 0xcc, 0x4c, 0xbc, 0xe0, 0x59, 0xff, 0x73, 0xdc, 0x8e,
	0x26, 0x9a, 0xeb, 0xba, 0xd8, 0xe7, 0x1b, 0x46, 0x14, 0xaf, 0x44, 0xaa, 0xb8, 0xde, 0x8a, 0xef,
	0x9e, 0x77, 0xe4, 0x37, 0xcd, 0xa1, 0x37, 0xf0, 0xa0, 0xdb, 0x9a, 0x4c, 0x99, 0xa0, 0xcd, 0x4d,
	0xad, 0xb4, 0x53, 0x13, 0x26, 0xc0, 0xa8, 0x2f, 0x5d, 0x76, 0x15, 0xb4, 0x82, 0x99, 0x0e, 0x95,
	0x71, 0xb9, 0x3b, 0x46, 0x1f, 0xda, 0xc7, 0xef, 0xd3, 0xed, 0x85, 0xa6, 0xfb, 0xf8, 0xaf, 0x00,
	0x75, 0xca, 0x93, 0x19, 0x8c, 0xac, 0x76, 0xd6, 0x6a, 0x8f, 0x73, 0x30, 0x6e, 0x0f, 0x82, 0x7f,
	0x3f, 0xb0, 0xd4, 0xfd, 0x82, 0x71, 0xeb, 0xb6, 0x25, 0x93, 0x76, 0xb9, 0x36, 0x12, 0x3d, 0xf1,
	0x19, 0x74, 0x91, 0xe8, 0xd1, 0xe1, 0x13, 0x08, 0x8d, 0x88, 0x96, 0x8c, 0x34, 0x71, 0x68, 0x05,
	0x81, 0x26, 0x12, 0x83, 0x97, 0xef, 0x20, 0xbe, 0x35, 0xed, 0xaf, 0xbc, 0x10, 0x44, 0x1d, 0x1a,
	0x86, 0x9e, 0x42, 0x28, 0x3b, 0xe0, 0xbe, 0xc4, 0x91, 0xf8, 0x30, 0xfc, 0xe8, 0xfd, 0xf4, 0xee,
	0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x37, 0x06, 0x35, 0x96, 0xb5, 0x03, 0x00, 0x00,
}
