// Code generated by protoc-gen-go.
// source: steammessages_credentials.steamclient.proto
// DO NOT EDIT!

package unified

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package unified is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package unified to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CCredentials_TestAvailablePassword_Request struct {
	Password          *string `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	ShaDigestPassword []byte  `protobuf:"bytes,2,opt,name=sha_digest_password,json=shaDigestPassword" json:"sha_digest_password,omitempty"`
	AccountName       *string `protobuf:"bytes,3,opt,name=account_name,json=accountName" json:"account_name,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *CCredentials_TestAvailablePassword_Request) Reset() {
	*m = CCredentials_TestAvailablePassword_Request{}
}
func (m *CCredentials_TestAvailablePassword_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_TestAvailablePassword_Request) ProtoMessage() {}
func (*CCredentials_TestAvailablePassword_Request) Descriptor() ([]byte, []int) {
	return credentials_fileDescriptor0, []int{0}
}

func (m *CCredentials_TestAvailablePassword_Request) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *CCredentials_TestAvailablePassword_Request) GetShaDigestPassword() []byte {
	if m != nil {
		return m.ShaDigestPassword
	}
	return nil
}

func (m *CCredentials_TestAvailablePassword_Request) GetAccountName() string {
	if m != nil && m.AccountName != nil {
		return *m.AccountName
	}
	return ""
}

type CCredentials_TestAvailablePassword_Response struct {
	IsValid          *bool  `protobuf:"varint,3,opt,name=is_valid,json=isValid" json:"is_valid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCredentials_TestAvailablePassword_Response) Reset() {
	*m = CCredentials_TestAvailablePassword_Response{}
}
func (m *CCredentials_TestAvailablePassword_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_TestAvailablePassword_Response) ProtoMessage() {}
func (*CCredentials_TestAvailablePassword_Response) Descriptor() ([]byte, []int) {
	return credentials_fileDescriptor0, []int{1}
}

func (m *CCredentials_TestAvailablePassword_Response) GetIsValid() bool {
	if m != nil && m.IsValid != nil {
		return *m.IsValid
	}
	return false
}

type CCredentials_GetSteamGuardDetails_Request struct {
	IncludeNewAuthentications *bool   `protobuf:"varint,1,opt,name=include_new_authentications,json=includeNewAuthentications,def=1" json:"include_new_authentications,omitempty"`
	Webcookie                 *string `protobuf:"bytes,2,opt,name=webcookie" json:"webcookie,omitempty"`
	TimestampMinimumWanted    *uint32 `protobuf:"fixed32,3,opt,name=timestamp_minimum_wanted,json=timestampMinimumWanted" json:"timestamp_minimum_wanted,omitempty"`
	Ipaddress                 *int32  `protobuf:"varint,4,opt,name=ipaddress" json:"ipaddress,omitempty"`
	XXX_unrecognized          []byte  `json:"-"`
}

func (m *CCredentials_GetSteamGuardDetails_Request) Reset() {
	*m = CCredentials_GetSteamGuardDetails_Request{}
}
func (m *CCredentials_GetSteamGuardDetails_Request) String() string { return proto.CompactTextString(m) }
func (*CCredentials_GetSteamGuardDetails_Request) ProtoMessage()    {}
func (*CCredentials_GetSteamGuardDetails_Request) Descriptor() ([]byte, []int) {
	return credentials_fileDescriptor0, []int{2}
}

const Default_CCredentials_GetSteamGuardDetails_Request_IncludeNewAuthentications bool = true

func (m *CCredentials_GetSteamGuardDetails_Request) GetIncludeNewAuthentications() bool {
	if m != nil && m.IncludeNewAuthentications != nil {
		return *m.IncludeNewAuthentications
	}
	return Default_CCredentials_GetSteamGuardDetails_Request_IncludeNewAuthentications
}

func (m *CCredentials_GetSteamGuardDetails_Request) GetWebcookie() string {
	if m != nil && m.Webcookie != nil {
		return *m.Webcookie
	}
	return ""
}

func (m *CCredentials_GetSteamGuardDetails_Request) GetTimestampMinimumWanted() uint32 {
	if m != nil && m.TimestampMinimumWanted != nil {
		return *m.TimestampMinimumWanted
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Request) GetIpaddress() int32 {
	if m != nil && m.Ipaddress != nil {
		return *m.Ipaddress
	}
	return 0
}

type CCredentials_GetSteamGuardDetails_Response struct {
	IsSteamguardEnabled                                   *bool                                                           `protobuf:"varint,1,opt,name=is_steamguard_enabled,json=isSteamguardEnabled" json:"is_steamguard_enabled,omitempty"`
	TimestampSteamguardEnabled                            *uint32                                                         `protobuf:"fixed32,2,opt,name=timestamp_steamguard_enabled,json=timestampSteamguardEnabled" json:"timestamp_steamguard_enabled,omitempty"`
	DeprecatedNewauthentication                           []*CCredentials_GetSteamGuardDetails_Response_NewAuthentication `protobuf:"bytes,3,rep,name=deprecated_newauthentication,json=deprecatedNewauthentication" json:"deprecated_newauthentication,omitempty"`
	DeprecatedMachineNameUserchosen                       *string                                                         `protobuf:"bytes,4,opt,name=deprecated_machine_name_userchosen,json=deprecatedMachineNameUserchosen" json:"deprecated_machine_name_userchosen,omitempty"`
	DeprecatedTimestampMachineSteamguardEnabled           *uint32                                                         `protobuf:"fixed32,5,opt,name=deprecated_timestamp_machine_steamguard_enabled,json=deprecatedTimestampMachineSteamguardEnabled" json:"deprecated_timestamp_machine_steamguard_enabled,omitempty"`
	DeprecatedAuthenticationExistsFromGeolocBeforeMintime *bool                                                           `protobuf:"varint,6,opt,name=deprecated_authentication_exists_from_geoloc_before_mintime,json=deprecatedAuthenticationExistsFromGeolocBeforeMintime" json:"deprecated_authentication_exists_from_geoloc_before_mintime,omitempty"`
	DeprecatedMachineId                                   *uint64                                                         `protobuf:"varint,7,opt,name=deprecated_machine_id,json=deprecatedMachineId" json:"deprecated_machine_id,omitempty"`
	SessionData                                           []*CCredentials_GetSteamGuardDetails_Response_SessionData       `protobuf:"bytes,8,rep,name=session_data,json=sessionData" json:"session_data,omitempty"`
	IsTwofactorEnabled                                    *bool                                                           `protobuf:"varint,9,opt,name=is_twofactor_enabled,json=isTwofactorEnabled" json:"is_twofactor_enabled,omitempty"`
	TimestampTwofactorEnabled                             *uint32                                                         `protobuf:"fixed32,10,opt,name=timestamp_twofactor_enabled,json=timestampTwofactorEnabled" json:"timestamp_twofactor_enabled,omitempty"`
	IsPhoneVerified                                       *bool                                                           `protobuf:"varint,11,opt,name=is_phone_verified,json=isPhoneVerified" json:"is_phone_verified,omitempty"`
	XXX_unrecognized                                      []byte                                                          `json:"-"`
}

func (m *CCredentials_GetSteamGuardDetails_Response) Reset() {
	*m = CCredentials_GetSteamGuardDetails_Response{}
}
func (m *CCredentials_GetSteamGuardDetails_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_GetSteamGuardDetails_Response) ProtoMessage() {}
func (*CCredentials_GetSteamGuardDetails_Response) Descriptor() ([]byte, []int) {
	return credentials_fileDescriptor0, []int{3}
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetIsSteamguardEnabled() bool {
	if m != nil && m.IsSteamguardEnabled != nil {
		return *m.IsSteamguardEnabled
	}
	return false
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetTimestampSteamguardEnabled() uint32 {
	if m != nil && m.TimestampSteamguardEnabled != nil {
		return *m.TimestampSteamguardEnabled
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetDeprecatedNewauthentication() []*CCredentials_GetSteamGuardDetails_Response_NewAuthentication {
	if m != nil {
		return m.DeprecatedNewauthentication
	}
	return nil
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetDeprecatedMachineNameUserchosen() string {
	if m != nil && m.DeprecatedMachineNameUserchosen != nil {
		return *m.DeprecatedMachineNameUserchosen
	}
	return ""
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetDeprecatedTimestampMachineSteamguardEnabled() uint32 {
	if m != nil && m.DeprecatedTimestampMachineSteamguardEnabled != nil {
		return *m.DeprecatedTimestampMachineSteamguardEnabled
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetDeprecatedAuthenticationExistsFromGeolocBeforeMintime() bool {
	if m != nil && m.DeprecatedAuthenticationExistsFromGeolocBeforeMintime != nil {
		return *m.DeprecatedAuthenticationExistsFromGeolocBeforeMintime
	}
	return false
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetDeprecatedMachineId() uint64 {
	if m != nil && m.DeprecatedMachineId != nil {
		return *m.DeprecatedMachineId
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetSessionData() []*CCredentials_GetSteamGuardDetails_Response_SessionData {
	if m != nil {
		return m.SessionData
	}
	return nil
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetIsTwofactorEnabled() bool {
	if m != nil && m.IsTwofactorEnabled != nil {
		return *m.IsTwofactorEnabled
	}
	return false
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetTimestampTwofactorEnabled() uint32 {
	if m != nil && m.TimestampTwofactorEnabled != nil {
		return *m.TimestampTwofactorEnabled
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Response) GetIsPhoneVerified() bool {
	if m != nil && m.IsPhoneVerified != nil {
		return *m.IsPhoneVerified
	}
	return false
}

type CCredentials_GetSteamGuardDetails_Response_NewAuthentication struct {
	TimestampSteamguardEnabled *uint32 `protobuf:"fixed32,1,opt,name=timestamp_steamguard_enabled,json=timestampSteamguardEnabled" json:"timestamp_steamguard_enabled,omitempty"`
	IsWebCookie                *bool   `protobuf:"varint,2,opt,name=is_web_cookie,json=isWebCookie" json:"is_web_cookie,omitempty"`
	Ipaddress                  *int32  `protobuf:"varint,3,opt,name=ipaddress" json:"ipaddress,omitempty"`
	GeolocInfo                 *string `protobuf:"bytes,4,opt,name=geoloc_info,json=geolocInfo" json:"geoloc_info,omitempty"`
	IsRemembered               *bool   `protobuf:"varint,5,opt,name=is_remembered,json=isRemembered" json:"is_remembered,omitempty"`
	MachineNameUserSupplied    *string `protobuf:"bytes,6,opt,name=machine_name_user_supplied,json=machineNameUserSupplied" json:"machine_name_user_supplied,omitempty"`
	Status                     *int32  `protobuf:"varint,7,opt,name=status" json:"status,omitempty"`
	XXX_unrecognized           []byte  `json:"-"`
}

func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) Reset() {
	*m = CCredentials_GetSteamGuardDetails_Response_NewAuthentication{}
}
func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_GetSteamGuardDetails_Response_NewAuthentication) ProtoMessage() {}
func (*CCredentials_GetSteamGuardDetails_Response_NewAuthentication) Descriptor() ([]byte, []int) {
	return credentials_fileDescriptor0, []int{3, 0}
}

func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) GetTimestampSteamguardEnabled() uint32 {
	if m != nil && m.TimestampSteamguardEnabled != nil {
		return *m.TimestampSteamguardEnabled
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) GetIsWebCookie() bool {
	if m != nil && m.IsWebCookie != nil {
		return *m.IsWebCookie
	}
	return false
}

func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) GetIpaddress() int32 {
	if m != nil && m.Ipaddress != nil {
		return *m.Ipaddress
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) GetGeolocInfo() string {
	if m != nil && m.GeolocInfo != nil {
		return *m.GeolocInfo
	}
	return ""
}

func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) GetIsRemembered() bool {
	if m != nil && m.IsRemembered != nil {
		return *m.IsRemembered
	}
	return false
}

func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) GetMachineNameUserSupplied() string {
	if m != nil && m.MachineNameUserSupplied != nil {
		return *m.MachineNameUserSupplied
	}
	return ""
}

func (m *CCredentials_GetSteamGuardDetails_Response_NewAuthentication) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

type CCredentials_GetSteamGuardDetails_Response_SessionData struct {
	MachineId                                   *uint64                                                         `protobuf:"varint,1,opt,name=machine_id,json=machineId" json:"machine_id,omitempty"`
	MachineNameUserchosen                       *string                                                         `protobuf:"bytes,2,opt,name=machine_name_userchosen,json=machineNameUserchosen" json:"machine_name_userchosen,omitempty"`
	TimestampMachineSteamguardEnabled           *uint32                                                         `protobuf:"fixed32,3,opt,name=timestamp_machine_steamguard_enabled,json=timestampMachineSteamguardEnabled" json:"timestamp_machine_steamguard_enabled,omitempty"`
	AuthenticationExistsFromGeolocBeforeMintime *bool                                                           `protobuf:"varint,4,opt,name=authentication_exists_from_geoloc_before_mintime,json=authenticationExistsFromGeolocBeforeMintime" json:"authentication_exists_from_geoloc_before_mintime,omitempty"`
	Newauthentication                           []*CCredentials_GetSteamGuardDetails_Response_NewAuthentication `protobuf:"bytes,5,rep,name=newauthentication" json:"newauthentication,omitempty"`
	AuthenticationExistsFromSameIpBeforeMintime *bool                                                           `protobuf:"varint,6,opt,name=authentication_exists_from_same_ip_before_mintime,json=authenticationExistsFromSameIpBeforeMintime" json:"authentication_exists_from_same_ip_before_mintime,omitempty"`
	PublicIpv4                                  *uint32                                                         `protobuf:"varint,7,opt,name=public_ipv4,json=publicIpv4" json:"public_ipv4,omitempty"`
	XXX_unrecognized                            []byte                                                          `json:"-"`
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) Reset() {
	*m = CCredentials_GetSteamGuardDetails_Response_SessionData{}
}
func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_GetSteamGuardDetails_Response_SessionData) ProtoMessage() {}
func (*CCredentials_GetSteamGuardDetails_Response_SessionData) Descriptor() ([]byte, []int) {
	return credentials_fileDescriptor0, []int{3, 1}
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) GetMachineId() uint64 {
	if m != nil && m.MachineId != nil {
		return *m.MachineId
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) GetMachineNameUserchosen() string {
	if m != nil && m.MachineNameUserchosen != nil {
		return *m.MachineNameUserchosen
	}
	return ""
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) GetTimestampMachineSteamguardEnabled() uint32 {
	if m != nil && m.TimestampMachineSteamguardEnabled != nil {
		return *m.TimestampMachineSteamguardEnabled
	}
	return 0
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) GetAuthenticationExistsFromGeolocBeforeMintime() bool {
	if m != nil && m.AuthenticationExistsFromGeolocBeforeMintime != nil {
		return *m.AuthenticationExistsFromGeolocBeforeMintime
	}
	return false
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) GetNewauthentication() []*CCredentials_GetSteamGuardDetails_Response_NewAuthentication {
	if m != nil {
		return m.Newauthentication
	}
	return nil
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) GetAuthenticationExistsFromSameIpBeforeMintime() bool {
	if m != nil && m.AuthenticationExistsFromSameIpBeforeMintime != nil {
		return *m.AuthenticationExistsFromSameIpBeforeMintime
	}
	return false
}

func (m *CCredentials_GetSteamGuardDetails_Response_SessionData) GetPublicIpv4() uint32 {
	if m != nil && m.PublicIpv4 != nil {
		return *m.PublicIpv4
	}
	return 0
}

type CCredentials_NewMachineNotificationDialog_Request struct {
	IsApproved       *bool  `protobuf:"varint,1,opt,name=is_approved,json=isApproved" json:"is_approved,omitempty"`
	IsWizardComplete *bool  `protobuf:"varint,2,opt,name=is_wizard_complete,json=isWizardComplete" json:"is_wizard_complete,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCredentials_NewMachineNotificationDialog_Request) Reset() {
	*m = CCredentials_NewMachineNotificationDialog_Request{}
}
func (m *CCredentials_NewMachineNotificationDialog_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_NewMachineNotificationDialog_Request) ProtoMessage() {}
func (*CCredentials_NewMachineNotificationDialog_Request) Descriptor() ([]byte, []int) {
	return credentials_fileDescriptor0, []int{4}
}

func (m *CCredentials_NewMachineNotificationDialog_Request) GetIsApproved() bool {
	if m != nil && m.IsApproved != nil {
		return *m.IsApproved
	}
	return false
}

func (m *CCredentials_NewMachineNotificationDialog_Request) GetIsWizardComplete() bool {
	if m != nil && m.IsWizardComplete != nil {
		return *m.IsWizardComplete
	}
	return false
}

type CCredentials_NewMachineNotificationDialog_Response struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCredentials_NewMachineNotificationDialog_Response) Reset() {
	*m = CCredentials_NewMachineNotificationDialog_Response{}
}
func (m *CCredentials_NewMachineNotificationDialog_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_NewMachineNotificationDialog_Response) ProtoMessage() {}
func (*CCredentials_NewMachineNotificationDialog_Response) Descriptor() ([]byte, []int) {
	return credentials_fileDescriptor0, []int{5}
}

type CCredentials_ValidateEmailAddress_Request struct {
	Stoken           *string `protobuf:"bytes,1,opt,name=stoken" json:"stoken,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCredentials_ValidateEmailAddress_Request) Reset() {
	*m = CCredentials_ValidateEmailAddress_Request{}
}
func (m *CCredentials_ValidateEmailAddress_Request) String() string { return proto.CompactTextString(m) }
func (*CCredentials_ValidateEmailAddress_Request) ProtoMessage()    {}
func (*CCredentials_ValidateEmailAddress_Request) Descriptor() ([]byte, []int) {
	return credentials_fileDescriptor0, []int{6}
}

func (m *CCredentials_ValidateEmailAddress_Request) GetStoken() string {
	if m != nil && m.Stoken != nil {
		return *m.Stoken
	}
	return ""
}

type CCredentials_ValidateEmailAddress_Response struct {
	WasValidated     *bool  `protobuf:"varint,1,opt,name=was_validated,json=wasValidated" json:"was_validated,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCredentials_ValidateEmailAddress_Response) Reset() {
	*m = CCredentials_ValidateEmailAddress_Response{}
}
func (m *CCredentials_ValidateEmailAddress_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_ValidateEmailAddress_Response) ProtoMessage() {}
func (*CCredentials_ValidateEmailAddress_Response) Descriptor() ([]byte, []int) {
	return credentials_fileDescriptor0, []int{7}
}

func (m *CCredentials_ValidateEmailAddress_Response) GetWasValidated() bool {
	if m != nil && m.WasValidated != nil {
		return *m.WasValidated
	}
	return false
}

type CCredentials_SteamGuardPhishingReport_Request struct {
	ParamString      *string `protobuf:"bytes,1,opt,name=param_string,json=paramString" json:"param_string,omitempty"`
	IpaddressActual  *uint32 `protobuf:"varint,2,opt,name=ipaddress_actual,json=ipaddressActual" json:"ipaddress_actual,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCredentials_SteamGuardPhishingReport_Request) Reset() {
	*m = CCredentials_SteamGuardPhishingReport_Request{}
}
func (m *CCredentials_SteamGuardPhishingReport_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_SteamGuardPhishingReport_Request) ProtoMessage() {}
func (*CCredentials_SteamGuardPhishingReport_Request) Descriptor() ([]byte, []int) {
	return credentials_fileDescriptor0, []int{8}
}

func (m *CCredentials_SteamGuardPhishingReport_Request) GetParamString() string {
	if m != nil && m.ParamString != nil {
		return *m.ParamString
	}
	return ""
}

func (m *CCredentials_SteamGuardPhishingReport_Request) GetIpaddressActual() uint32 {
	if m != nil && m.IpaddressActual != nil {
		return *m.IpaddressActual
	}
	return 0
}

type CCredentials_SteamGuardPhishingReport_Response struct {
	IpaddressLoginattempt   *uint32 `protobuf:"varint,1,opt,name=ipaddress_loginattempt,json=ipaddressLoginattempt" json:"ipaddress_loginattempt,omitempty"`
	CountrynameLoginattempt *string `protobuf:"bytes,2,opt,name=countryname_loginattempt,json=countrynameLoginattempt" json:"countryname_loginattempt,omitempty"`
	StatenameLoginattempt   *string `protobuf:"bytes,3,opt,name=statename_loginattempt,json=statenameLoginattempt" json:"statename_loginattempt,omitempty"`
	CitynameLoginattempt    *string `protobuf:"bytes,4,opt,name=cityname_loginattempt,json=citynameLoginattempt" json:"cityname_loginattempt,omitempty"`
	IpaddressActual         *uint32 `protobuf:"varint,5,opt,name=ipaddress_actual,json=ipaddressActual" json:"ipaddress_actual,omitempty"`
	CountrynameActual       *string `protobuf:"bytes,6,opt,name=countryname_actual,json=countrynameActual" json:"countryname_actual,omitempty"`
	StatenameActual         *string `protobuf:"bytes,7,opt,name=statename_actual,json=statenameActual" json:"statename_actual,omitempty"`
	CitynameActual          *string `protobuf:"bytes,8,opt,name=cityname_actual,json=citynameActual" json:"cityname_actual,omitempty"`
	SteamguardCode          *string `protobuf:"bytes,9,opt,name=steamguard_code,json=steamguardCode" json:"steamguard_code,omitempty"`
	XXX_unrecognized        []byte  `json:"-"`
}

func (m *CCredentials_SteamGuardPhishingReport_Response) Reset() {
	*m = CCredentials_SteamGuardPhishingReport_Response{}
}
func (m *CCredentials_SteamGuardPhishingReport_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_SteamGuardPhishingReport_Response) ProtoMessage() {}
func (*CCredentials_SteamGuardPhishingReport_Response) Descriptor() ([]byte, []int) {
	return credentials_fileDescriptor0, []int{9}
}

func (m *CCredentials_SteamGuardPhishingReport_Response) GetIpaddressLoginattempt() uint32 {
	if m != nil && m.IpaddressLoginattempt != nil {
		return *m.IpaddressLoginattempt
	}
	return 0
}

func (m *CCredentials_SteamGuardPhishingReport_Response) GetCountrynameLoginattempt() string {
	if m != nil && m.CountrynameLoginattempt != nil {
		return *m.CountrynameLoginattempt
	}
	return ""
}

func (m *CCredentials_SteamGuardPhishingReport_Response) GetStatenameLoginattempt() string {
	if m != nil && m.StatenameLoginattempt != nil {
		return *m.StatenameLoginattempt
	}
	return ""
}

func (m *CCredentials_SteamGuardPhishingReport_Response) GetCitynameLoginattempt() string {
	if m != nil && m.CitynameLoginattempt != nil {
		return *m.CitynameLoginattempt
	}
	return ""
}

func (m *CCredentials_SteamGuardPhishingReport_Response) GetIpaddressActual() uint32 {
	if m != nil && m.IpaddressActual != nil {
		return *m.IpaddressActual
	}
	return 0
}

func (m *CCredentials_SteamGuardPhishingReport_Response) GetCountrynameActual() string {
	if m != nil && m.CountrynameActual != nil {
		return *m.CountrynameActual
	}
	return ""
}

func (m *CCredentials_SteamGuardPhishingReport_Response) GetStatenameActual() string {
	if m != nil && m.StatenameActual != nil {
		return *m.StatenameActual
	}
	return ""
}

func (m *CCredentials_SteamGuardPhishingReport_Response) GetCitynameActual() string {
	if m != nil && m.CitynameActual != nil {
		return *m.CitynameActual
	}
	return ""
}

func (m *CCredentials_SteamGuardPhishingReport_Response) GetSteamguardCode() string {
	if m != nil && m.SteamguardCode != nil {
		return *m.SteamguardCode
	}
	return ""
}

type CCredentials_AccountLockRequest_Request struct {
	ParamString      *string `protobuf:"bytes,1,opt,name=param_string,json=paramString" json:"param_string,omitempty"`
	IpaddressActual  *uint32 `protobuf:"varint,2,opt,name=ipaddress_actual,json=ipaddressActual" json:"ipaddress_actual,omitempty"`
	QueryOnly        *bool   `protobuf:"varint,3,opt,name=query_only,json=queryOnly" json:"query_only,omitempty"`
	EmailMessageType *int32  `protobuf:"varint,4,opt,name=email_message_type,json=emailMessageType" json:"email_message_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CCredentials_AccountLockRequest_Request) Reset() {
	*m = CCredentials_AccountLockRequest_Request{}
}
func (m *CCredentials_AccountLockRequest_Request) String() string { return proto.CompactTextString(m) }
func (*CCredentials_AccountLockRequest_Request) ProtoMessage()    {}
func (*CCredentials_AccountLockRequest_Request) Descriptor() ([]byte, []int) {
	return credentials_fileDescriptor0, []int{10}
}

func (m *CCredentials_AccountLockRequest_Request) GetParamString() string {
	if m != nil && m.ParamString != nil {
		return *m.ParamString
	}
	return ""
}

func (m *CCredentials_AccountLockRequest_Request) GetIpaddressActual() uint32 {
	if m != nil && m.IpaddressActual != nil {
		return *m.IpaddressActual
	}
	return 0
}

func (m *CCredentials_AccountLockRequest_Request) GetQueryOnly() bool {
	if m != nil && m.QueryOnly != nil {
		return *m.QueryOnly
	}
	return false
}

func (m *CCredentials_AccountLockRequest_Request) GetEmailMessageType() int32 {
	if m != nil && m.EmailMessageType != nil {
		return *m.EmailMessageType
	}
	return 0
}

type CCredentials_AccountLockRequest_Response struct {
	Success              *bool  `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	AccountAlreadyLocked *bool  `protobuf:"varint,2,opt,name=account_already_locked,json=accountAlreadyLocked" json:"account_already_locked,omitempty"`
	ExpiredLink          *bool  `protobuf:"varint,3,opt,name=expired_link,json=expiredLink" json:"expired_link,omitempty"`
	XXX_unrecognized     []byte `json:"-"`
}

func (m *CCredentials_AccountLockRequest_Response) Reset() {
	*m = CCredentials_AccountLockRequest_Response{}
}
func (m *CCredentials_AccountLockRequest_Response) String() string { return proto.CompactTextString(m) }
func (*CCredentials_AccountLockRequest_Response) ProtoMessage()    {}
func (*CCredentials_AccountLockRequest_Response) Descriptor() ([]byte, []int) {
	return credentials_fileDescriptor0, []int{11}
}

func (m *CCredentials_AccountLockRequest_Response) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *CCredentials_AccountLockRequest_Response) GetAccountAlreadyLocked() bool {
	if m != nil && m.AccountAlreadyLocked != nil {
		return *m.AccountAlreadyLocked
	}
	return false
}

func (m *CCredentials_AccountLockRequest_Response) GetExpiredLink() bool {
	if m != nil && m.ExpiredLink != nil {
		return *m.ExpiredLink
	}
	return false
}

type CCredentials_LastCredentialChangeTime_Request struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCredentials_LastCredentialChangeTime_Request) Reset() {
	*m = CCredentials_LastCredentialChangeTime_Request{}
}
func (m *CCredentials_LastCredentialChangeTime_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_LastCredentialChangeTime_Request) ProtoMessage() {}
func (*CCredentials_LastCredentialChangeTime_Request) Descriptor() ([]byte, []int) {
	return credentials_fileDescriptor0, []int{12}
}

type CCredentials_LastCredentialChangeTime_Response struct {
	TimestampLastPasswordChange *uint32 `protobuf:"fixed32,1,opt,name=timestamp_last_password_change,json=timestampLastPasswordChange" json:"timestamp_last_password_change,omitempty"`
	TimestampLastEmailChange    *uint32 `protobuf:"fixed32,2,opt,name=timestamp_last_email_change,json=timestampLastEmailChange" json:"timestamp_last_email_change,omitempty"`
	TimestampLastPasswordReset  *uint32 `protobuf:"fixed32,3,opt,name=timestamp_last_password_reset,json=timestampLastPasswordReset" json:"timestamp_last_password_reset,omitempty"`
	XXX_unrecognized            []byte  `json:"-"`
}

func (m *CCredentials_LastCredentialChangeTime_Response) Reset() {
	*m = CCredentials_LastCredentialChangeTime_Response{}
}
func (m *CCredentials_LastCredentialChangeTime_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_LastCredentialChangeTime_Response) ProtoMessage() {}
func (*CCredentials_LastCredentialChangeTime_Response) Descriptor() ([]byte, []int) {
	return credentials_fileDescriptor0, []int{13}
}

func (m *CCredentials_LastCredentialChangeTime_Response) GetTimestampLastPasswordChange() uint32 {
	if m != nil && m.TimestampLastPasswordChange != nil {
		return *m.TimestampLastPasswordChange
	}
	return 0
}

func (m *CCredentials_LastCredentialChangeTime_Response) GetTimestampLastEmailChange() uint32 {
	if m != nil && m.TimestampLastEmailChange != nil {
		return *m.TimestampLastEmailChange
	}
	return 0
}

func (m *CCredentials_LastCredentialChangeTime_Response) GetTimestampLastPasswordReset() uint32 {
	if m != nil && m.TimestampLastPasswordReset != nil {
		return *m.TimestampLastPasswordReset
	}
	return 0
}

type CCredentials_GetAccountAuthSecret_Request struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCredentials_GetAccountAuthSecret_Request) Reset() {
	*m = CCredentials_GetAccountAuthSecret_Request{}
}
func (m *CCredentials_GetAccountAuthSecret_Request) String() string { return proto.CompactTextString(m) }
func (*CCredentials_GetAccountAuthSecret_Request) ProtoMessage()    {}
func (*CCredentials_GetAccountAuthSecret_Request) Descriptor() ([]byte, []int) {
	return credentials_fileDescriptor0, []int{14}
}

type CCredentials_GetAccountAuthSecret_Response struct {
	SecretId         *int32 `protobuf:"varint,1,opt,name=secret_id,json=secretId" json:"secret_id,omitempty"`
	Secret           []byte `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CCredentials_GetAccountAuthSecret_Response) Reset() {
	*m = CCredentials_GetAccountAuthSecret_Response{}
}
func (m *CCredentials_GetAccountAuthSecret_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCredentials_GetAccountAuthSecret_Response) ProtoMessage() {}
func (*CCredentials_GetAccountAuthSecret_Response) Descriptor() ([]byte, []int) {
	return credentials_fileDescriptor0, []int{15}
}

func (m *CCredentials_GetAccountAuthSecret_Response) GetSecretId() int32 {
	if m != nil && m.SecretId != nil {
		return *m.SecretId
	}
	return 0
}

func (m *CCredentials_GetAccountAuthSecret_Response) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

func init() {
	proto.RegisterType((*CCredentials_TestAvailablePassword_Request)(nil), "CCredentials_TestAvailablePassword_Request")
	proto.RegisterType((*CCredentials_TestAvailablePassword_Response)(nil), "CCredentials_TestAvailablePassword_Response")
	proto.RegisterType((*CCredentials_GetSteamGuardDetails_Request)(nil), "CCredentials_GetSteamGuardDetails_Request")
	proto.RegisterType((*CCredentials_GetSteamGuardDetails_Response)(nil), "CCredentials_GetSteamGuardDetails_Response")
	proto.RegisterType((*CCredentials_GetSteamGuardDetails_Response_NewAuthentication)(nil), "CCredentials_GetSteamGuardDetails_Response.NewAuthentication")
	proto.RegisterType((*CCredentials_GetSteamGuardDetails_Response_SessionData)(nil), "CCredentials_GetSteamGuardDetails_Response.SessionData")
	proto.RegisterType((*CCredentials_NewMachineNotificationDialog_Request)(nil), "CCredentials_NewMachineNotificationDialog_Request")
	proto.RegisterType((*CCredentials_NewMachineNotificationDialog_Response)(nil), "CCredentials_NewMachineNotificationDialog_Response")
	proto.RegisterType((*CCredentials_ValidateEmailAddress_Request)(nil), "CCredentials_ValidateEmailAddress_Request")
	proto.RegisterType((*CCredentials_ValidateEmailAddress_Response)(nil), "CCredentials_ValidateEmailAddress_Response")
	proto.RegisterType((*CCredentials_SteamGuardPhishingReport_Request)(nil), "CCredentials_SteamGuardPhishingReport_Request")
	proto.RegisterType((*CCredentials_SteamGuardPhishingReport_Response)(nil), "CCredentials_SteamGuardPhishingReport_Response")
	proto.RegisterType((*CCredentials_AccountLockRequest_Request)(nil), "CCredentials_AccountLockRequest_Request")
	proto.RegisterType((*CCredentials_AccountLockRequest_Response)(nil), "CCredentials_AccountLockRequest_Response")
	proto.RegisterType((*CCredentials_LastCredentialChangeTime_Request)(nil), "CCredentials_LastCredentialChangeTime_Request")
	proto.RegisterType((*CCredentials_LastCredentialChangeTime_Response)(nil), "CCredentials_LastCredentialChangeTime_Response")
	proto.RegisterType((*CCredentials_GetAccountAuthSecret_Request)(nil), "CCredentials_GetAccountAuthSecret_Request")
	proto.RegisterType((*CCredentials_GetAccountAuthSecret_Response)(nil), "CCredentials_GetAccountAuthSecret_Response")
}

func init() { proto.RegisterFile("steammessages_credentials.steamclient.proto", credentials_fileDescriptor0) }

var credentials_fileDescriptor0 = []byte{
	// 1852 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x18, 0x4d, 0x6f, 0x1c, 0x49,
	0x55, 0x1d, 0xdb, 0xf1, 0xcc, 0x1b, 0x9b, 0xc4, 0x95, 0xd8, 0x99, 0x4c, 0xb2, 0x9b, 0xde, 0x0e,
	0x92, 0x93, 0x38, 0xdb, 0xd9, 0xf5, 0x66, 0xf9, 0x5a, 0x2d, 0x62, 0x62, 0x67, 0x83, 0xc1, 0xce,
	0x86, 0xb6, 0xd9, 0x48, 0x5c, 0x5a, 0xe5, 0xee, 0xb2, 0x5d, 0x72, 0x7f, 0xd1, 0x55, 0x63, 0xaf,
	0x57, 0x5a, 0x69, 0x37, 0x37, 0x38, 0x20, 0xc4, 0x0d, 0x01, 0x12, 0x27, 0x7e, 0x00, 0x12, 0x48,
	0xdc, 0x39, 0xf2, 0x37, 0xf8, 0x01, 0x9c, 0xb8, 0xf2, 0xba, 0xba, 0xa6, 0x7b, 0x7a, 0xba, 0xc7,
	0xf6, 0x20, 0xb8, 0x4d, 0xbf, 0xef, 0xef, 0xf7, 0x6a, 0x60, 0x4d, 0x48, 0x46, 0xc3, 0x90, 0x09,
	0x41, 0x0f, 0x99, 0x70, 0xbd, 0x94, 0xf9, 0x2c, 0x92, 0x9c, 0x06, 0xc2, 0x56, 0x18, 0x2f, 0xe0,
	0xf8, 0x6d, 0x27, 0x69, 0x2c, 0xe3, 0xde, 0xe3, 0x2a, 0xf1, 0x20, 0xe2, 0x07, 0x9c, 0xf9, 0xee,
	0x3e, 0x15, 0xac, 0x4e, 0x6d, 0xfd, 0xce, 0x80, 0x47, 0x1b, 0x1b, 0xa5, 0x40, 0x77, 0x8f, 0x09,
	0xd9, 0x3f, 0xa1, 0x3c, 0xa0, 0xfb, 0x01, 0x7b, 0x45, 0x85, 0x38, 0x8d, 0x53, 0xdf, 0x75, 0xd8,
	0xcf, 0x07, 0x88, 0x20, 0x3d, 0x68, 0x25, 0x1a, 0xd6, 0x35, 0x4c, 0xe3, 0x41, 0xdb, 0x29, 0xbe,
	0x89, 0x0d, 0x37, 0xc4, 0x11, 0x75, 0x7d, 0x8e, 0x6a, 0xa5, 0x5b, 0x90, 0x5d, 0x41, 0xb2, 0x05,
	0x67, 0x09, 0x51, 0x9b, 0x0a, 0x33, 0x94, 0x49, 0xde, 0x81, 0x05, 0xea, 0x79, 0xf1, 0x20, 0x92,
	0x6e, 0x44, 0x43, 0xd6, 0x9d, 0x51, 0xf2, 0x3a, 0x1a, 0xf6, 0x12, 0x41, 0xd6, 0x0f, 0x61, 0xed,
	0x52, 0xc6, 0x89, 0x24, 0x8e, 0x04, 0x23, 0xb7, 0xa1, 0xc5, 0x85, 0x7b, 0x42, 0x03, 0xee, 0x2b,
	0x69, 0x2d, 0x67, 0x9e, 0x8b, 0xcf, 0xb2, 0x4f, 0xeb, 0x6f, 0x33, 0xf0, 0xb0, 0x22, 0xea, 0x05,
	0x93, 0xbb, 0x59, 0x34, 0x5e, 0x0c, 0x68, 0xea, 0x6f, 0x32, 0x89, 0x42, 0x45, 0xe1, 0xe6, 0xaf,
	0x0d, 0xb8, 0xc3, 0x23, 0x2f, 0x18, 0xf8, 0xcc, 0x8d, 0xd8, 0xa9, 0x4b, 0x07, 0xf2, 0x28, 0x63,
	0xf4, 0xa8, 0xe4, 0xa8, 0x49, 0xb9, 0xde, 0xfa, 0xde, 0xac, 0x4c, 0x07, 0xec, 0xd9, 0x8f, 0xde,
	0xfc, 0xa5, 0xfb, 0xc9, 0xeb, 0x23, 0x86, 0x14, 0xa9, 0x19, 0xa7, 0x66, 0x14, 0x4b, 0x53, 0xc6,
	0x66, 0x12, 0x27, 0x83, 0x80, 0x4a, 0x66, 0x22, 0xdc, 0x44, 0x19, 0x55, 0x11, 0x26, 0xe6, 0x24,
	0xf0, 0x4d, 0x1e, 0x29, 0x74, 0xaa, 0x1d, 0x70, 0x6e, 0x6b, 0xa5, 0x2f, 0xd9, 0x69, 0xbf, 0xaa,
	0x92, 0xfc, 0xd1, 0x80, 0xf6, 0x29, 0xdb, 0xf7, 0xe2, 0xf8, 0x98, 0x33, 0x15, 0xd4, 0xf6, 0xb3,
	0xaf, 0x0d, 0xd4, 0xfd, 0xe5, 0x1e, 0x4a, 0x18, 0x08, 0x96, 0xae, 0x0a, 0x53, 0x79, 0x64, 0x2a,
	0x97, 0xcc, 0x90, 0x7a, 0x47, 0x3c, 0x62, 0x66, 0xa6, 0xd8, 0xcc, 0xd9, 0x6c, 0x73, 0xeb, 0xc0,
	0x4c, 0x50, 0x1b, 0x0a, 0x7e, 0x6c, 0x72, 0xb9, 0x1a, 0x04, 0xe6, 0xbe, 0x62, 0xf6, 0x33, 0x93,
	0x0f, 0x99, 0x54, 0xe6, 0x68, 0x61, 0x43, 0x01, 0x5b, 0x9b, 0x68, 0x67, 0x56, 0x39, 0xbe, 0x19,
	0x1f, 0x28, 0x82, 0xfe, 0x8e, 0x29, 0xb0, 0xbe, 0xd0, 0x2e, 0xdb, 0x29, 0x8d, 0x22, 0xdf, 0x81,
	0xae, 0xe4, 0x58, 0x78, 0x92, 0x86, 0x89, 0x1b, 0xf2, 0x88, 0x87, 0x83, 0xd0, 0x3d, 0xa5, 0x91,
	0x64, 0x79, 0x3a, 0xe6, 0x9d, 0x95, 0x02, 0xbf, 0x93, 0xa3, 0x5f, 0x2b, 0x2c, 0xb9, 0x0b, 0x6d,
	0x9e, 0x50, 0xdf, 0x47, 0xd3, 0x44, 0x77, 0x16, 0x49, 0xe7, 0x9c, 0x12, 0x60, 0xfd, 0x63, 0x71,
	0xac, 0x46, 0x27, 0xe4, 0x4e, 0x57, 0xc1, 0x3a, 0x2c, 0x63, 0x15, 0xa8, 0x52, 0x3f, 0xcc, 0x08,
	0x5c, 0x16, 0x65, 0xe5, 0x92, 0x17, 0x6c, 0xcb, 0xb9, 0xc1, 0xc5, 0x6e, 0x81, 0x7b, 0x9e, 0xa3,
	0xc8, 0x0f, 0xe0, 0x6e, 0x69, 0x7a, 0x03, 0xeb, 0x15, 0x65, 0x7e, 0xaf, 0xa0, 0xa9, 0x4b, 0xf8,
	0xca, 0x80, 0xbb, 0x3e, 0xc3, 0xe0, 0x62, 0xc2, 0xb0, 0xdd, 0x6a, 0x19, 0xc7, 0x08, 0xcc, 0x3c,
	0xe8, 0xac, 0x7f, 0x6c, 0x5f, 0xde, 0x13, 0xbb, 0x56, 0x06, 0xce, 0x9d, 0x52, 0xc5, 0xcb, 0x71,
	0x0d, 0xe4, 0xc7, 0x60, 0x8d, 0x58, 0xa0, 0xd3, 0xa7, 0x7a, 0xcb, 0xcd, 0x52, 0xea, 0x1d, 0xc5,
	0x98, 0x78, 0x15, 0xde, 0xb6, 0x73, 0xaf, 0xa4, 0xdc, 0xc9, 0x09, 0xb3, 0x86, 0xfb, 0x69, 0x41,
	0x46, 0x7c, 0x78, 0x32, 0x22, 0x6c, 0x24, 0xaf, 0x5a, 0x6c, 0x43, 0x90, 0xe6, 0x54, 0x90, 0xd6,
	0x4a, 0xb6, 0xbd, 0x22, 0xdb, 0x39, 0x53, 0x3d, 0x6a, 0x5f, 0xc0, 0x47, 0x23, 0x5a, 0xaa, 0xfe,
	0xb8, 0xec, 0x73, 0x2e, 0xa4, 0x70, 0x0f, 0xd2, 0x38, 0x74, 0x0f, 0x59, 0x1c, 0xc4, 0x9e, 0xbb,
	0xcf, 0x0e, 0xe2, 0x94, 0x65, 0xc5, 0x95, 0x59, 0xd4, 0xbd, 0xaa, 0x32, 0xfa, 0x61, 0x29, 0xa2,
	0x1a, 0xae, 0xe7, 0x4a, 0xc0, 0x27, 0xc8, 0xff, 0x42, 0xb1, 0x3f, 0x53, 0xdc, 0x3b, 0x39, 0x73,
	0x56, 0x27, 0x0d, 0xe1, 0xc2, 0xd1, 0x31, 0x8f, 0x52, 0x67, 0x9d, 0x1b, 0xb5, 0x08, 0x6d, 0xf9,
	0xe4, 0x67, 0xb0, 0xa0, 0x2b, 0xdf, 0xf5, 0xa9, 0xa4, 0xdd, 0x96, 0x4a, 0xea, 0xb7, 0xa7, 0x49,
	0xea, 0x6e, 0xce, 0xbf, 0x89, 0xec, 0x4e, 0x47, 0x94, 0x1f, 0xe4, 0x3d, 0xb8, 0x89, 0x75, 0x2b,
	0x4f, 0xe3, 0x03, 0xea, 0xc9, 0x38, 0x2d, 0xc2, 0xda, 0x56, 0x4e, 0x12, 0x2e, 0xf6, 0x86, 0xa8,
	0x61, 0xf4, 0xbe, 0x0f, 0x77, 0xca, 0xc4, 0xd4, 0x19, 0x41, 0xe5, 0xe3, 0x76, 0x41, 0x52, 0xe3,
	0x7f, 0x04, 0x4b, 0xa8, 0x31, 0x39, 0x8a, 0xd1, 0xef, 0x13, 0x96, 0xaa, 0x45, 0xd1, 0xed, 0x28,
	0x75, 0xd7, 0xb8, 0x78, 0x95, 0xc1, 0x3f, 0xd3, 0xe0, 0xde, 0x9f, 0xaf, 0xc0, 0x52, 0xad, 0x1e,
	0x2f, 0xec, 0x1b, 0xe3, 0xc2, 0xbe, 0xb1, 0x60, 0x11, 0x6d, 0xc0, 0x21, 0xe2, 0x8e, 0x8c, 0xb6,
	0x96, 0xd3, 0xe1, 0xe2, 0x35, 0xdb, 0xdf, 0xc8, 0x07, 0x4b, 0x65, 0x3c, 0xcc, 0x8c, 0x8d, 0x07,
	0x72, 0x0f, 0x3a, 0xba, 0x3a, 0x78, 0x74, 0x10, 0xeb, 0xfa, 0x86, 0x1c, 0xb4, 0x85, 0x10, 0x72,
	0x5f, 0xa9, 0x48, 0x59, 0xc8, 0xc2, 0x7d, 0x96, 0xea, 0x42, 0x6d, 0x39, 0x0b, 0x5c, 0x38, 0x05,
	0x8c, 0x7c, 0x04, 0xbd, 0x5a, 0xc7, 0xb8, 0x62, 0x90, 0x24, 0x41, 0x16, 0x94, 0xab, 0x4a, 0xe8,
	0xad, 0xb0, 0xda, 0x2a, 0xbb, 0x1a, 0x4d, 0x56, 0xe0, 0x2a, 0xba, 0x27, 0x07, 0x42, 0xd5, 0xce,
	0x9c, 0xa3, 0xbf, 0x7a, 0xbf, 0x99, 0x85, 0xce, 0x48, 0xbe, 0xc9, 0x5b, 0x00, 0x23, 0x75, 0x66,
	0xa8, 0x3a, 0x6b, 0x87, 0x45, 0x75, 0x7d, 0x0b, 0x6e, 0x4d, 0xea, 0x5a, 0x35, 0xf0, 0x9d, 0xe5,
	0xb0, 0xb1, 0x57, 0x3f, 0x85, 0x6f, 0x5e, 0xaa, 0x41, 0xf3, 0x21, 0xfc, 0x8e, 0xbc, 0xb0, 0x2d,
	0x19, 0xbc, 0x37, 0x75, 0x2f, 0xce, 0xaa, 0xa0, 0xae, 0xd1, 0x29, 0x3a, 0xf0, 0x18, 0x96, 0xea,
	0x73, 0x72, 0xee, 0x7f, 0x31, 0x27, 0xeb, 0x72, 0xc9, 0x01, 0xbc, 0x7f, 0x8e, 0x4f, 0x22, 0x8b,
	0x37, 0x4f, 0x9a, 0x07, 0xcc, 0x44, 0xa7, 0x76, 0x91, 0x6b, 0x2b, 0xa9, 0x3a, 0x85, 0xe5, 0x98,
	0x0c, 0xf6, 0x03, 0x8e, 0xe5, 0x98, 0x9c, 0x3c, 0x55, 0x05, 0xb1, 0xe8, 0x40, 0x0e, 0xda, 0x42,
	0x88, 0xf5, 0xc6, 0x80, 0xf7, 0x2b, 0xce, 0xa1, 0xf9, 0xc3, 0x19, 0x1c, 0x4b, 0xec, 0xb6, 0x5c,
	0xcb, 0x26, 0xe2, 0xe2, 0xc3, 0xe2, 0x24, 0x41, 0xb1, 0x58, 0xc4, 0x34, 0xc1, 0xb3, 0xed, 0xa4,
	0xd8, 0x65, 0xc0, 0x45, 0x5f, 0x43, 0xc8, 0x63, 0x20, 0x59, 0x23, 0xf1, 0x2f, 0xb2, 0x8c, 0x7b,
	0x71, 0x98, 0x04, 0x4c, 0x0e, 0xbb, 0xe9, 0x3a, 0x76, 0x93, 0x42, 0x6c, 0x68, 0xb8, 0xf5, 0x14,
	0xd6, 0xa7, 0xb1, 0x21, 0x0f, 0xb4, 0xb5, 0x31, 0x76, 0x44, 0xa9, 0xdb, 0x0a, 0x27, 0xe4, 0xf3,
	0x10, 0x13, 0xd2, 0xcf, 0xfb, 0xb1, 0xb0, 0x58, 0x35, 0x45, 0x7c, 0x8c, 0xc5, 0x9b, 0x5f, 0x8a,
	0xfa, 0xcb, 0xfa, 0xc9, 0xd8, 0x36, 0x9f, 0x20, 0x44, 0x6f, 0x73, 0x6c, 0xde, 0x53, 0xaa, 0x8f,
	0xba, 0x6c, 0x16, 0x6b, 0xcf, 0x17, 0x10, 0x38, 0x64, 0xf4, 0xad, 0x2f, 0xe1, 0xdd, 0x8a, 0xc8,
	0xb2, 0x56, 0x5e, 0x1d, 0x71, 0x81, 0x5e, 0x1d, 0x3a, 0x2c, 0x89, 0x53, 0x59, 0xd8, 0x86, 0xb7,
	0x67, 0x42, 0x53, 0x8a, 0x79, 0x97, 0x29, 0x62, 0xb5, 0x85, 0x1d, 0x05, 0xdb, 0x55, 0x20, 0xf2,
	0x10, 0xae, 0x17, 0x33, 0xc6, 0xc5, 0xb1, 0x39, 0xa0, 0x81, 0x8a, 0xe6, 0x22, 0xce, 0xc6, 0x21,
	0xbc, 0xaf, 0xc0, 0xd6, 0x3f, 0x67, 0xc0, 0xbe, 0xac, 0x7e, 0xed, 0xd6, 0x87, 0xb0, 0x52, 0x4a,
	0xc7, 0x18, 0xf3, 0x88, 0x4a, 0xc9, 0xc2, 0x44, 0x2a, 0x53, 0x16, 0x9d, 0xe5, 0x02, 0xbb, 0x3d,
	0x82, 0x24, 0xdf, 0x85, 0xae, 0xba, 0x8e, 0xd3, 0x33, 0x35, 0x20, 0x2a, 0x8c, 0xf9, 0x88, 0xb8,
	0x35, 0x82, 0xaf, 0xb0, 0xa2, 0xc6, 0x6c, 0x2a, 0xb1, 0x3a, 0x63, 0x7e, 0x78, 0x2f, 0x17, 0xd8,
	0x0a, 0xdb, 0x07, 0xb0, 0xec, 0x71, 0xd9, 0xa0, 0x2e, 0x9f, 0xb3, 0x37, 0x87, 0xc8, 0x0a, 0x53,
	0x53, 0xec, 0xe6, 0x1a, 0x63, 0x47, 0xde, 0x05, 0x32, 0xea, 0x91, 0x26, 0xce, 0xe7, 0xed, 0xd2,
	0x08, 0x46, 0x93, 0xa3, 0xe4, 0xd2, 0x0b, 0x4d, 0x3c, 0xaf, 0x88, 0xaf, 0x15, 0x70, 0x4d, 0xba,
	0x0a, 0xd7, 0x0a, 0xcb, 0x35, 0x65, 0x4b, 0x51, 0x7e, 0x63, 0x08, 0x2e, 0x09, 0x47, 0x86, 0xa5,
	0x17, 0xfb, 0x4c, 0xed, 0x5c, 0x24, 0x2c, 0xc1, 0x1b, 0x08, 0xb5, 0xfe, 0x6e, 0xc0, 0x6a, 0x25,
	0xcf, 0xfd, 0xfc, 0xad, 0xb2, 0x1d, 0x7b, 0xc7, 0xba, 0xb2, 0xfe, 0x3f, 0x15, 0x96, 0x2d, 0x0e,
	0x14, 0x9b, 0x9e, 0xb9, 0x71, 0x14, 0x9c, 0xe9, 0xb7, 0x4d, 0x5b, 0x41, 0x3e, 0x45, 0x40, 0xd6,
	0xfb, 0x2c, 0xeb, 0x1e, 0x57, 0x3f, 0xfb, 0x5c, 0x79, 0x96, 0x30, 0x7d, 0x48, 0x5f, 0x57, 0x98,
	0x9d, 0x1c, 0xb1, 0x87, 0x70, 0xeb, 0x0f, 0x06, 0x3c, 0xb8, 0xd8, 0x0d, 0x5d, 0xa8, 0x5d, 0x98,
	0x17, 0x03, 0xcf, 0xcb, 0x36, 0x6f, 0xde, 0x79, 0xc3, 0x4f, 0xf2, 0x14, 0x56, 0x86, 0xef, 0x37,
	0x1a, 0xa4, 0xf8, 0x3c, 0x38, 0xc3, 0x02, 0xf1, 0x8e, 0xf5, 0xb5, 0xdc, 0x72, 0x6e, 0x6a, 0x6c,
	0x3f, 0x47, 0x6e, 0x2b, 0x5c, 0x16, 0x17, 0xf6, 0x79, 0xc2, 0x51, 0xbb, 0x1b, 0xf0, 0xe8, 0x58,
	0xfb, 0xd2, 0xd1, 0xb0, 0x6d, 0x04, 0x59, 0x4f, 0xc6, 0xba, 0x79, 0x9b, 0x0a, 0x59, 0x7e, 0x6f,
	0x1c, 0xd1, 0x08, 0x1d, 0xc1, 0x51, 0x3b, 0x8c, 0xb5, 0xf5, 0x6f, 0x63, 0xac, 0xff, 0xce, 0xe1,
	0xd0, 0x6e, 0x6d, 0xc0, 0xdb, 0xe5, 0xca, 0x0c, 0xe8, 0xc8, 0x83, 0xd5, 0xf5, 0x14, 0xb9, 0x3e,
	0x5d, 0xca, 0x03, 0x2b, 0x93, 0x39, 0x7c, 0x72, 0xe6, 0x12, 0xc9, 0xc7, 0xa3, 0xf7, 0x97, 0x12,
	0x92, 0x67, 0x41, 0x4b, 0xc8, 0x1f, 0x0d, 0xdd, 0x8a, 0x04, 0x35, 0xe4, 0x34, 0x7b, 0x1f, 0xde,
	0x9a, 0x64, 0x43, 0xf6, 0x46, 0x93, 0x7a, 0x5f, 0xf7, 0x1a, 0x4d, 0x70, 0x32, 0x0a, 0x6b, 0xad,
	0xfe, 0xaa, 0xd5, 0xc9, 0xcc, 0x16, 0xe2, 0x2e, 0xf3, 0x52, 0x56, 0x94, 0xa4, 0x45, 0xeb, 0xcf,
	0xa8, 0x26, 0x62, 0x1d, 0xa1, 0x3b, 0xd0, 0x16, 0x39, 0x48, 0x9f, 0x2a, 0x73, 0x4e, 0x2b, 0x07,
	0x6c, 0xe5, 0x07, 0x8f, 0xfa, 0xad, 0x9f, 0xf7, 0xfa, 0x6b, 0xfd, 0x5f, 0x6d, 0xe8, 0x8c, 0xa8,
	0x20, 0xbf, 0x32, 0x60, 0xb9, 0xf1, 0xd1, 0x4e, 0xd6, 0xec, 0xcb, 0xff, 0xed, 0xd0, 0x7b, 0x6c,
	0x4f, 0xf1, 0x37, 0x80, 0xd5, 0xc3, 0x57, 0xf1, 0x4a, 0x23, 0x8d, 0x4d, 0x7e, 0x69, 0xc0, 0xcd,
	0xa6, 0x63, 0x82, 0x3c, 0xb2, 0x2f, 0xfd, 0xf7, 0x40, 0x6f, 0x6d, 0x8a, 0xe3, 0xc4, 0xba, 0x8d,
	0xd6, 0x2c, 0x37, 0x91, 0xd8, 0xe4, 0xaf, 0x06, 0x58, 0xe7, 0x2d, 0x5e, 0x94, 0x31, 0x08, 0x24,
	0x59, 0xb7, 0xa7, 0x3e, 0x17, 0x7a, 0x1f, 0xd8, 0xff, 0xc5, 0x7a, 0x5f, 0x45, 0x53, 0xef, 0x5f,
	0x6c, 0x90, 0x4d, 0x7e, 0x8f, 0x51, 0x6c, 0x5a, 0xdb, 0xe3, 0x51, 0x3c, 0xef, 0x3e, 0x18, 0x8f,
	0xe2, 0xb9, 0x67, 0x80, 0xb5, 0x86, 0xa6, 0xad, 0x0e, 0x49, 0x4c, 0x1a, 0x99, 0xaa, 0xd3, 0x4c,
	0x3d, 0x25, 0xcd, 0x43, 0x7e, 0xc2, 0x22, 0x93, 0x9a, 0xea, 0xc2, 0x20, 0xbf, 0x35, 0xa0, 0x3b,
	0x69, 0x05, 0x13, 0xdb, 0x9e, 0xea, 0x54, 0xe8, 0x3d, 0x99, 0x72, 0xb5, 0x5b, 0x77, 0xd1, 0xd4,
	0xc9, 0xea, 0xbf, 0x36, 0x80, 0xd4, 0xe7, 0x2d, 0x79, 0x60, 0x5f, 0x72, 0xb1, 0xf4, 0x1e, 0xda,
	0x97, 0x9d, 0xdd, 0xd6, 0x0a, 0x5a, 0xd2, 0xa4, 0xec, 0x4f, 0x06, 0xbc, 0x8d, 0x15, 0xd9, 0x34,
	0x21, 0x87, 0xed, 0x60, 0xdb, 0x53, 0x8d, 0xe0, 0xf1, 0x28, 0x5d, 0x38, 0x80, 0xad, 0xfb, 0x68,
	0xdb, 0xbd, 0xf3, 0x8d, 0xb0, 0xc9, 0x2f, 0xf2, 0x6e, 0xad, 0x4d, 0xa9, 0x86, 0x6e, 0x9d, 0x38,
	0xf6, 0x1a, 0xba, 0x75, 0xf2, 0xd4, 0xb3, 0xba, 0x68, 0x56, 0xa3, 0xca, 0xde, 0x2d, 0xc4, 0xdc,
	0x18, 0x11, 0x64, 0xe2, 0xfb, 0xeb, 0x84, 0x7b, 0xec, 0xd9, 0xcc, 0x57, 0x86, 0xf1, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x33, 0xa9, 0x36, 0x0f, 0xa3, 0x15, 0x00, 0x00,
}
