// Code generated by protoc-gen-go. DO NOT EDIT.
// source: steammessages_deviceauth.steamclient.proto

package unified

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package unified is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package unified to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CDeviceAuth_GetOwnAuthorizedDevices_Request struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	IncludeCanceled  *bool   `protobuf:"varint,2,opt,name=include_canceled,json=includeCanceled" json:"include_canceled,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Request) Reset() {
	*m = CDeviceAuth_GetOwnAuthorizedDevices_Request{}
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetOwnAuthorizedDevices_Request) ProtoMessage() {}
func (*CDeviceAuth_GetOwnAuthorizedDevices_Request) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{0}
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Request) GetIncludeCanceled() bool {
	if m != nil && m.IncludeCanceled != nil {
		return *m.IncludeCanceled
	}
	return false
}

type CDeviceAuth_GetOwnAuthorizedDevices_Response struct {
	Devices          []*CDeviceAuth_GetOwnAuthorizedDevices_Response_Device `protobuf:"bytes,1,rep,name=devices" json:"devices,omitempty"`
	XXX_unrecognized []byte                                                 `json:"-"`
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response) Reset() {
	*m = CDeviceAuth_GetOwnAuthorizedDevices_Response{}
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetOwnAuthorizedDevices_Response) ProtoMessage() {}
func (*CDeviceAuth_GetOwnAuthorizedDevices_Response) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{1}
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response) GetDevices() []*CDeviceAuth_GetOwnAuthorizedDevices_Response_Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type CDeviceAuth_GetOwnAuthorizedDevices_Response_Device struct {
	AuthDeviceToken  *uint64 `protobuf:"fixed64,1,opt,name=auth_device_token,json=authDeviceToken" json:"auth_device_token,omitempty"`
	DeviceName       *string `protobuf:"bytes,2,opt,name=device_name,json=deviceName" json:"device_name,omitempty"`
	IsPending        *bool   `protobuf:"varint,3,opt,name=is_pending,json=isPending" json:"is_pending,omitempty"`
	IsCanceled       *bool   `protobuf:"varint,4,opt,name=is_canceled,json=isCanceled" json:"is_canceled,omitempty"`
	LastTimeUsed     *uint32 `protobuf:"varint,5,opt,name=last_time_used,json=lastTimeUsed" json:"last_time_used,omitempty"`
	LastBorrowerId   *uint64 `protobuf:"fixed64,6,opt,name=last_borrower_id,json=lastBorrowerId" json:"last_borrower_id,omitempty"`
	LastAppPlayed    *uint32 `protobuf:"varint,7,opt,name=last_app_played,json=lastAppPlayed" json:"last_app_played,omitempty"`
	IsLimited        *bool   `protobuf:"varint,8,opt,name=is_limited,json=isLimited" json:"is_limited,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) Reset() {
	*m = CDeviceAuth_GetOwnAuthorizedDevices_Response_Device{}
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) ProtoMessage() {}
func (*CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{1, 0}
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetAuthDeviceToken() uint64 {
	if m != nil && m.AuthDeviceToken != nil {
		return *m.AuthDeviceToken
	}
	return 0
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetDeviceName() string {
	if m != nil && m.DeviceName != nil {
		return *m.DeviceName
	}
	return ""
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetIsPending() bool {
	if m != nil && m.IsPending != nil {
		return *m.IsPending
	}
	return false
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetIsCanceled() bool {
	if m != nil && m.IsCanceled != nil {
		return *m.IsCanceled
	}
	return false
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetLastTimeUsed() uint32 {
	if m != nil && m.LastTimeUsed != nil {
		return *m.LastTimeUsed
	}
	return 0
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetLastBorrowerId() uint64 {
	if m != nil && m.LastBorrowerId != nil {
		return *m.LastBorrowerId
	}
	return 0
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetLastAppPlayed() uint32 {
	if m != nil && m.LastAppPlayed != nil {
		return *m.LastAppPlayed
	}
	return 0
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetIsLimited() bool {
	if m != nil && m.IsLimited != nil {
		return *m.IsLimited
	}
	return false
}

type CDeviceAuth_AcceptAuthorizationRequest_Request struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	AuthDeviceToken  *uint64 `protobuf:"fixed64,2,opt,name=auth_device_token,json=authDeviceToken" json:"auth_device_token,omitempty"`
	AuthCode         *uint64 `protobuf:"fixed64,3,opt,name=auth_code,json=authCode" json:"auth_code,omitempty"`
	FromSteamid      *uint64 `protobuf:"fixed64,4,opt,name=from_steamid,json=fromSteamid" json:"from_steamid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) Reset() {
	*m = CDeviceAuth_AcceptAuthorizationRequest_Request{}
}
func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_AcceptAuthorizationRequest_Request) ProtoMessage() {}
func (*CDeviceAuth_AcceptAuthorizationRequest_Request) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{2}
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) GetAuthDeviceToken() uint64 {
	if m != nil && m.AuthDeviceToken != nil {
		return *m.AuthDeviceToken
	}
	return 0
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) GetAuthCode() uint64 {
	if m != nil && m.AuthCode != nil {
		return *m.AuthCode
	}
	return 0
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) GetFromSteamid() uint64 {
	if m != nil && m.FromSteamid != nil {
		return *m.FromSteamid
	}
	return 0
}

type CDeviceAuth_AcceptAuthorizationRequest_Response struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Response) Reset() {
	*m = CDeviceAuth_AcceptAuthorizationRequest_Response{}
}
func (m *CDeviceAuth_AcceptAuthorizationRequest_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_AcceptAuthorizationRequest_Response) ProtoMessage() {}
func (*CDeviceAuth_AcceptAuthorizationRequest_Response) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{3}
}

type CDeviceAuth_AuthorizeRemoteDevice_Request struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	AuthDeviceToken  *uint64 `protobuf:"fixed64,2,opt,name=auth_device_token,json=authDeviceToken" json:"auth_device_token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDeviceAuth_AuthorizeRemoteDevice_Request) Reset() {
	*m = CDeviceAuth_AuthorizeRemoteDevice_Request{}
}
func (m *CDeviceAuth_AuthorizeRemoteDevice_Request) String() string { return proto.CompactTextString(m) }
func (*CDeviceAuth_AuthorizeRemoteDevice_Request) ProtoMessage()    {}
func (*CDeviceAuth_AuthorizeRemoteDevice_Request) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{4}
}

func (m *CDeviceAuth_AuthorizeRemoteDevice_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_AuthorizeRemoteDevice_Request) GetAuthDeviceToken() uint64 {
	if m != nil && m.AuthDeviceToken != nil {
		return *m.AuthDeviceToken
	}
	return 0
}

type CDeviceAuth_AuthorizeRemoteDevice_Response struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDeviceAuth_AuthorizeRemoteDevice_Response) Reset() {
	*m = CDeviceAuth_AuthorizeRemoteDevice_Response{}
}
func (m *CDeviceAuth_AuthorizeRemoteDevice_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_AuthorizeRemoteDevice_Response) ProtoMessage() {}
func (*CDeviceAuth_AuthorizeRemoteDevice_Response) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{5}
}

type CDeviceAuth_DeauthorizeRemoteDevice_Request struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	AuthDeviceToken  *uint64 `protobuf:"fixed64,2,opt,name=auth_device_token,json=authDeviceToken" json:"auth_device_token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDeviceAuth_DeauthorizeRemoteDevice_Request) Reset() {
	*m = CDeviceAuth_DeauthorizeRemoteDevice_Request{}
}
func (m *CDeviceAuth_DeauthorizeRemoteDevice_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_DeauthorizeRemoteDevice_Request) ProtoMessage() {}
func (*CDeviceAuth_DeauthorizeRemoteDevice_Request) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{6}
}

func (m *CDeviceAuth_DeauthorizeRemoteDevice_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_DeauthorizeRemoteDevice_Request) GetAuthDeviceToken() uint64 {
	if m != nil && m.AuthDeviceToken != nil {
		return *m.AuthDeviceToken
	}
	return 0
}

type CDeviceAuth_DeauthorizeRemoteDevice_Response struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDeviceAuth_DeauthorizeRemoteDevice_Response) Reset() {
	*m = CDeviceAuth_DeauthorizeRemoteDevice_Response{}
}
func (m *CDeviceAuth_DeauthorizeRemoteDevice_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_DeauthorizeRemoteDevice_Response) ProtoMessage() {}
func (*CDeviceAuth_DeauthorizeRemoteDevice_Response) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{7}
}

type CDeviceAuth_GetUsedAuthorizedDevices_Request struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Request) Reset() {
	*m = CDeviceAuth_GetUsedAuthorizedDevices_Request{}
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetUsedAuthorizedDevices_Request) ProtoMessage() {}
func (*CDeviceAuth_GetUsedAuthorizedDevices_Request) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{8}
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

type CDeviceAuth_GetUsedAuthorizedDevices_Response struct {
	Devices          []*CDeviceAuth_GetUsedAuthorizedDevices_Response_Device `protobuf:"bytes,1,rep,name=devices" json:"devices,omitempty"`
	XXX_unrecognized []byte                                                  `json:"-"`
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response) Reset() {
	*m = CDeviceAuth_GetUsedAuthorizedDevices_Response{}
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetUsedAuthorizedDevices_Response) ProtoMessage() {}
func (*CDeviceAuth_GetUsedAuthorizedDevices_Response) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{9}
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response) GetDevices() []*CDeviceAuth_GetUsedAuthorizedDevices_Response_Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type CDeviceAuth_GetUsedAuthorizedDevices_Response_Device struct {
	AuthDeviceToken  *uint64 `protobuf:"fixed64,1,opt,name=auth_device_token,json=authDeviceToken" json:"auth_device_token,omitempty"`
	DeviceName       *string `protobuf:"bytes,2,opt,name=device_name,json=deviceName" json:"device_name,omitempty"`
	OwnerSteamid     *uint64 `protobuf:"fixed64,3,opt,name=owner_steamid,json=ownerSteamid" json:"owner_steamid,omitempty"`
	LastTimeUsed     *uint32 `protobuf:"varint,4,opt,name=last_time_used,json=lastTimeUsed" json:"last_time_used,omitempty"`
	LastAppPlayed    *uint32 `protobuf:"varint,5,opt,name=last_app_played,json=lastAppPlayed" json:"last_app_played,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) Reset() {
	*m = CDeviceAuth_GetUsedAuthorizedDevices_Response_Device{}
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) ProtoMessage() {}
func (*CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{9, 0}
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) GetAuthDeviceToken() uint64 {
	if m != nil && m.AuthDeviceToken != nil {
		return *m.AuthDeviceToken
	}
	return 0
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) GetDeviceName() string {
	if m != nil && m.DeviceName != nil {
		return *m.DeviceName
	}
	return ""
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) GetOwnerSteamid() uint64 {
	if m != nil && m.OwnerSteamid != nil {
		return *m.OwnerSteamid
	}
	return 0
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) GetLastTimeUsed() uint32 {
	if m != nil && m.LastTimeUsed != nil {
		return *m.LastTimeUsed
	}
	return 0
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) GetLastAppPlayed() uint32 {
	if m != nil && m.LastAppPlayed != nil {
		return *m.LastAppPlayed
	}
	return 0
}

type CDeviceAuth_GetAuthorizedBorrowers_Request struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	IncludeCanceled  *bool   `protobuf:"varint,2,opt,name=include_canceled,json=includeCanceled" json:"include_canceled,omitempty"`
	IncludePending   *bool   `protobuf:"varint,3,opt,name=include_pending,json=includePending" json:"include_pending,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) Reset() {
	*m = CDeviceAuth_GetAuthorizedBorrowers_Request{}
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetAuthorizedBorrowers_Request) ProtoMessage() {}
func (*CDeviceAuth_GetAuthorizedBorrowers_Request) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{10}
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) GetIncludeCanceled() bool {
	if m != nil && m.IncludeCanceled != nil {
		return *m.IncludeCanceled
	}
	return false
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) GetIncludePending() bool {
	if m != nil && m.IncludePending != nil {
		return *m.IncludePending
	}
	return false
}

type CDeviceAuth_GetAuthorizedBorrowers_Response struct {
	Borrowers        []*CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower `protobuf:"bytes,1,rep,name=borrowers" json:"borrowers,omitempty"`
	XXX_unrecognized []byte                                                  `json:"-"`
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response) Reset() {
	*m = CDeviceAuth_GetAuthorizedBorrowers_Response{}
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetAuthorizedBorrowers_Response) ProtoMessage() {}
func (*CDeviceAuth_GetAuthorizedBorrowers_Response) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{11}
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response) GetBorrowers() []*CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower {
	if m != nil {
		return m.Borrowers
	}
	return nil
}

type CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	IsPending        *bool   `protobuf:"varint,2,opt,name=is_pending,json=isPending" json:"is_pending,omitempty"`
	IsCanceled       *bool   `protobuf:"varint,3,opt,name=is_canceled,json=isCanceled" json:"is_canceled,omitempty"`
	TimeCreated      *uint32 `protobuf:"varint,4,opt,name=time_created,json=timeCreated" json:"time_created,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) Reset() {
	*m = CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower{}
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) ProtoMessage() {}
func (*CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{11, 0}
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) GetIsPending() bool {
	if m != nil && m.IsPending != nil {
		return *m.IsPending
	}
	return false
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) GetIsCanceled() bool {
	if m != nil && m.IsCanceled != nil {
		return *m.IsCanceled
	}
	return false
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) GetTimeCreated() uint32 {
	if m != nil && m.TimeCreated != nil {
		return *m.TimeCreated
	}
	return 0
}

type CDeviceAuth_AddAuthorizedBorrowers_Request struct {
	Steamid          *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	SteamidBorrower  []uint64 `protobuf:"fixed64,2,rep,name=steamid_borrower,json=steamidBorrower" json:"steamid_borrower,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CDeviceAuth_AddAuthorizedBorrowers_Request) Reset() {
	*m = CDeviceAuth_AddAuthorizedBorrowers_Request{}
}
func (m *CDeviceAuth_AddAuthorizedBorrowers_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_AddAuthorizedBorrowers_Request) ProtoMessage() {}
func (*CDeviceAuth_AddAuthorizedBorrowers_Request) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{12}
}

func (m *CDeviceAuth_AddAuthorizedBorrowers_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_AddAuthorizedBorrowers_Request) GetSteamidBorrower() []uint64 {
	if m != nil {
		return m.SteamidBorrower
	}
	return nil
}

type CDeviceAuth_AddAuthorizedBorrowers_Response struct {
	SecondsToWait    *int32 `protobuf:"varint,1,opt,name=seconds_to_wait,json=secondsToWait" json:"seconds_to_wait,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDeviceAuth_AddAuthorizedBorrowers_Response) Reset() {
	*m = CDeviceAuth_AddAuthorizedBorrowers_Response{}
}
func (m *CDeviceAuth_AddAuthorizedBorrowers_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_AddAuthorizedBorrowers_Response) ProtoMessage() {}
func (*CDeviceAuth_AddAuthorizedBorrowers_Response) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{13}
}

func (m *CDeviceAuth_AddAuthorizedBorrowers_Response) GetSecondsToWait() int32 {
	if m != nil && m.SecondsToWait != nil {
		return *m.SecondsToWait
	}
	return 0
}

type CDeviceAuth_RemoveAuthorizedBorrowers_Request struct {
	Steamid          *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	SteamidBorrower  []uint64 `protobuf:"fixed64,2,rep,name=steamid_borrower,json=steamidBorrower" json:"steamid_borrower,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Request) Reset() {
	*m = CDeviceAuth_RemoveAuthorizedBorrowers_Request{}
}
func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_RemoveAuthorizedBorrowers_Request) ProtoMessage() {}
func (*CDeviceAuth_RemoveAuthorizedBorrowers_Request) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{14}
}

func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Request) GetSteamidBorrower() []uint64 {
	if m != nil {
		return m.SteamidBorrower
	}
	return nil
}

type CDeviceAuth_RemoveAuthorizedBorrowers_Response struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Response) Reset() {
	*m = CDeviceAuth_RemoveAuthorizedBorrowers_Response{}
}
func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_RemoveAuthorizedBorrowers_Response) ProtoMessage() {}
func (*CDeviceAuth_RemoveAuthorizedBorrowers_Response) Descriptor() ([]byte, []int) {
	return deviceauth_fileDescriptor0, []int{15}
}

func init() {
	proto.RegisterType((*CDeviceAuth_GetOwnAuthorizedDevices_Request)(nil), "CDeviceAuth_GetOwnAuthorizedDevices_Request")
	proto.RegisterType((*CDeviceAuth_GetOwnAuthorizedDevices_Response)(nil), "CDeviceAuth_GetOwnAuthorizedDevices_Response")
	proto.RegisterType((*CDeviceAuth_GetOwnAuthorizedDevices_Response_Device)(nil), "CDeviceAuth_GetOwnAuthorizedDevices_Response.Device")
	proto.RegisterType((*CDeviceAuth_AcceptAuthorizationRequest_Request)(nil), "CDeviceAuth_AcceptAuthorizationRequest_Request")
	proto.RegisterType((*CDeviceAuth_AcceptAuthorizationRequest_Response)(nil), "CDeviceAuth_AcceptAuthorizationRequest_Response")
	proto.RegisterType((*CDeviceAuth_AuthorizeRemoteDevice_Request)(nil), "CDeviceAuth_AuthorizeRemoteDevice_Request")
	proto.RegisterType((*CDeviceAuth_AuthorizeRemoteDevice_Response)(nil), "CDeviceAuth_AuthorizeRemoteDevice_Response")
	proto.RegisterType((*CDeviceAuth_DeauthorizeRemoteDevice_Request)(nil), "CDeviceAuth_DeauthorizeRemoteDevice_Request")
	proto.RegisterType((*CDeviceAuth_DeauthorizeRemoteDevice_Response)(nil), "CDeviceAuth_DeauthorizeRemoteDevice_Response")
	proto.RegisterType((*CDeviceAuth_GetUsedAuthorizedDevices_Request)(nil), "CDeviceAuth_GetUsedAuthorizedDevices_Request")
	proto.RegisterType((*CDeviceAuth_GetUsedAuthorizedDevices_Response)(nil), "CDeviceAuth_GetUsedAuthorizedDevices_Response")
	proto.RegisterType((*CDeviceAuth_GetUsedAuthorizedDevices_Response_Device)(nil), "CDeviceAuth_GetUsedAuthorizedDevices_Response.Device")
	proto.RegisterType((*CDeviceAuth_GetAuthorizedBorrowers_Request)(nil), "CDeviceAuth_GetAuthorizedBorrowers_Request")
	proto.RegisterType((*CDeviceAuth_GetAuthorizedBorrowers_Response)(nil), "CDeviceAuth_GetAuthorizedBorrowers_Response")
	proto.RegisterType((*CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower)(nil), "CDeviceAuth_GetAuthorizedBorrowers_Response.Borrower")
	proto.RegisterType((*CDeviceAuth_AddAuthorizedBorrowers_Request)(nil), "CDeviceAuth_AddAuthorizedBorrowers_Request")
	proto.RegisterType((*CDeviceAuth_AddAuthorizedBorrowers_Response)(nil), "CDeviceAuth_AddAuthorizedBorrowers_Response")
	proto.RegisterType((*CDeviceAuth_RemoveAuthorizedBorrowers_Request)(nil), "CDeviceAuth_RemoveAuthorizedBorrowers_Request")
	proto.RegisterType((*CDeviceAuth_RemoveAuthorizedBorrowers_Response)(nil), "CDeviceAuth_RemoveAuthorizedBorrowers_Response")
}

func init() { proto.RegisterFile("steammessages_deviceauth.steamclient.proto", deviceauth_fileDescriptor0) }

var deviceauth_fileDescriptor0 = []byte{
	// 1068 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0x96, 0x77, 0x9b, 0xbf, 0x49, 0xd2, 0x94, 0x91, 0x68, 0x8d, 0x11, 0x74, 0xea, 0x56, 0x25,
	0xcd, 0x8f, 0x13, 0xaa, 0x20, 0xfe, 0x11, 0x69, 0x2a, 0x05, 0xa4, 0xaa, 0xad, 0x9c, 0x54, 0x5c,
	0x5a, 0x13, 0xcf, 0x49, 0x76, 0xd4, 0x5d, 0xcf, 0xc6, 0x33, 0x9b, 0x28, 0x5c, 0xa1, 0xbd, 0xe1,
	0x86, 0x27, 0x28, 0x6f, 0x80, 0x40, 0x42, 0x48, 0x86, 0x0b, 0x78, 0x00, 0x24, 0x5e, 0x0a, 0x79,
	0x66, 0xbc, 0xa9, 0x37, 0xde, 0x64, 0x1d, 0x35, 0x77, 0xbb, 0xdf, 0x9c, 0x99, 0xf9, 0xce, 0x99,
	0x73, 0xbe, 0xcf, 0x68, 0x49, 0x2a, 0xa0, 0x9d, 0x0e, 0x48, 0x49, 0x0f, 0x40, 0x46, 0x0c, 0x8e,
	0x78, 0x0c, 0xb4, 0xa7, 0x5a, 0x81, 0x5e, 0x88, 0xdb, 0x1c, 0x12, 0x15, 0x74, 0x53, 0xa1, 0x84,
	0xb7, 0x52, 0x8e, 0xed, 0x25, 0x7c, 0x9f, 0x03, 0x8b, 0xf6, 0xa8, 0x84, 0xb3, 0xd1, 0x7e, 0x8a,
	0x96, 0xb7, 0x1e, 0xeb, 0xe3, 0x36, 0x7b, 0xaa, 0x15, 0x6d, 0x83, 0x7a, 0x76, 0x9c, 0xe4, 0x3f,
	0x45, 0xca, 0xbf, 0x07, 0x66, 0x96, 0x64, 0x14, 0xc2, 0x61, 0x0f, 0xa4, 0xc2, 0x2e, 0x9a, 0xd2,
	0x67, 0x70, 0xe6, 0x3a, 0xc4, 0x59, 0x9c, 0x0c, 0x8b, 0xbf, 0xf8, 0x01, 0xba, 0xc1, 0x93, 0xb8,
	0xdd, 0x63, 0x10, 0xc5, 0x34, 0x89, 0xa1, 0x0d, 0xcc, 0x6d, 0x10, 0x67, 0x71, 0x3a, 0x5c, 0xb0,
	0xf8, 0x96, 0x85, 0xfd, 0xdf, 0x9a, 0x68, 0x65, 0xbc, 0x4b, 0x65, 0x57, 0x24, 0x12, 0xf0, 0x53,
	0x34, 0x65, 0x52, 0x96, 0xae, 0x43, 0x9a, 0x8b, 0xb3, 0x0f, 0x37, 0x82, 0x3a, 0xfb, 0x03, 0x03,
	0x84, 0xc5, 0x21, 0xde, 0xaf, 0x0d, 0x34, 0x69, 0x30, 0xbc, 0x84, 0xde, 0xca, 0xeb, 0x68, 0x4b,
	0x1a, 0x29, 0xf1, 0x12, 0x12, 0x9b, 0xda, 0x42, 0xbe, 0x60, 0xc2, 0x76, 0x73, 0x18, 0xdf, 0x46,
	0xb3, 0x36, 0x2c, 0xa1, 0x1d, 0xd0, 0xd9, 0xcd, 0x84, 0xc8, 0x40, 0x4f, 0x69, 0x07, 0xf0, 0x7b,
	0x08, 0x71, 0x19, 0x75, 0x21, 0x61, 0x3c, 0x39, 0x70, 0x9b, 0x3a, 0xfb, 0x19, 0x2e, 0x9f, 0x1b,
	0x20, 0xdf, 0xcf, 0xe5, 0x69, 0x75, 0xae, 0xe9, 0x75, 0xc4, 0x65, 0x51, 0x18, 0x7c, 0x0f, 0x5d,
	0x6f, 0x53, 0xa9, 0x22, 0xc5, 0x3b, 0x10, 0xf5, 0x24, 0x30, 0x77, 0x82, 0x38, 0x8b, 0xf3, 0xe1,
	0x5c, 0x8e, 0xee, 0xf2, 0x0e, 0xbc, 0x90, 0xc0, 0xf0, 0x22, 0xba, 0xa1, 0xa3, 0xf6, 0x44, 0x9a,
	0x8a, 0x63, 0x48, 0x23, 0xce, 0xdc, 0x49, 0xcd, 0x58, 0xef, 0x7e, 0x64, 0xe1, 0x6f, 0x19, 0xbe,
	0x8f, 0x16, 0x74, 0x24, 0xed, 0x76, 0xa3, 0x6e, 0x9b, 0x9e, 0x00, 0x73, 0xa7, 0xf4, 0x81, 0xf3,
	0x39, 0xbc, 0xd9, 0xed, 0x3e, 0xd7, 0xa0, 0xe5, 0xdd, 0xe6, 0x1d, 0xae, 0x80, 0xb9, 0xd3, 0x05,
	0xef, 0x27, 0x06, 0xf0, 0xff, 0x74, 0x50, 0xa9, 0xde, 0x9b, 0x71, 0x0c, 0x5d, 0x55, 0xd4, 0x9b,
	0x2a, 0x2e, 0x12, 0xdb, 0x1f, 0x63, 0xf4, 0x49, 0x65, 0xc1, 0x1b, 0xd5, 0x05, 0x7f, 0x17, 0xcd,
	0xe8, 0xd8, 0x58, 0x30, 0xd0, 0xe5, 0x9c, 0x0c, 0xa7, 0x73, 0x60, 0x4b, 0x30, 0xc0, 0x77, 0xd0,
	0xdc, 0x7e, 0x2a, 0x3a, 0x51, 0x71, 0xcf, 0x35, 0xbd, 0x3e, 0x9b, 0x63, 0x3b, 0x06, 0xf2, 0x3f,
	0x44, 0x6b, 0x63, 0xf3, 0x36, 0xad, 0xe2, 0x1f, 0xa2, 0x07, 0xa5, 0x2d, 0x45, 0x53, 0x85, 0xd0,
	0x11, 0x0a, 0xcc, 0xca, 0x9b, 0xcd, 0xd2, 0x5f, 0x41, 0x4b, 0xe3, 0x5c, 0x69, 0x09, 0xca, 0xf2,
	0xc0, 0x3e, 0xd6, 0x32, 0x70, 0xd5, 0x14, 0x83, 0xf2, 0xc0, 0x8e, 0xbe, 0xd4, 0x92, 0xfc, 0xe6,
	0xcc, 0x80, 0xe7, 0x9d, 0x7b, 0x09, 0x59, 0xf1, 0xff, 0x6b, 0xa0, 0xd5, 0x31, 0x8f, 0xb2, 0x62,
	0xf1, 0x6c, 0x58, 0x2c, 0x3e, 0x0a, 0x6a, 0x1d, 0x70, 0x46, 0x2d, 0xfe, 0x75, 0xae, 0x46, 0x2d,
	0xee, 0xa2, 0x79, 0x71, 0x9c, 0x40, 0x3a, 0xe8, 0x60, 0xd3, 0xe1, 0x73, 0x1a, 0xb4, 0x2d, 0x5c,
	0x21, 0x09, 0xd7, 0x2a, 0x24, 0xa1, 0x62, 0xd0, 0x27, 0x2a, 0x06, 0xdd, 0x7f, 0xe5, 0x94, 0x7b,
	0x6d, 0x1b, 0xd4, 0x69, 0x21, 0x0a, 0xe1, 0x78, 0xb3, 0x6a, 0x8f, 0x3f, 0x40, 0x05, 0x34, 0xa4,
	0x8c, 0xd7, 0x2d, 0x6c, 0xe5, 0xd1, 0xff, 0xa9, 0x71, 0xc6, 0x8b, 0xaa, 0xc9, 0xd9, 0x87, 0xde,
	0x41, 0x33, 0x85, 0x04, 0x8e, 0x7c, 0xea, 0xf3, 0x0e, 0x08, 0x0a, 0x28, 0x3c, 0x3d, 0xc7, 0xfb,
	0xd1, 0x41, 0xd3, 0x05, 0x7e, 0x4e, 0xfe, 0x65, 0xa5, 0x6f, 0x5c, 0xa0, 0xf4, 0xcd, 0x33, 0x4a,
	0x7f, 0x07, 0xcd, 0xe9, 0x17, 0x8d, 0x53, 0xa0, 0x6a, 0xf0, 0xa8, 0xb3, 0x39, 0xb6, 0x65, 0x20,
	0xff, 0x70, 0x48, 0x16, 0x18, 0xbb, 0xf4, 0x53, 0xd9, 0x9f, 0x03, 0xc7, 0x70, 0x1b, 0xa4, 0x99,
	0xb7, 0xac, 0xc5, 0x8b, 0xd3, 0xfc, 0x17, 0xe5, 0x07, 0x18, 0x79, 0xa5, 0x7d, 0x80, 0xfb, 0x68,
	0x41, 0x42, 0x2c, 0x12, 0x26, 0x23, 0x25, 0xa2, 0x63, 0xca, 0x95, 0xbe, 0x7b, 0x22, 0x9c, 0xb7,
	0xf0, 0xae, 0xf8, 0x8e, 0x72, 0xe5, 0xab, 0xf2, 0x08, 0xe7, 0x92, 0x71, 0x04, 0x57, 0x9e, 0xcc,
	0x7a, 0xd9, 0xb4, 0xce, 0xbb, 0xd5, 0xe4, 0xf3, 0xf0, 0xaf, 0x59, 0x84, 0x4e, 0x77, 0xe0, 0x57,
	0x0e, 0xba, 0x35, 0xe2, 0xd3, 0x02, 0xaf, 0x04, 0x35, 0xbe, 0x9a, 0xbc, 0xd5, 0x5a, 0x9f, 0x2b,
	0xbe, 0xdf, 0xcf, 0xdc, 0xf7, 0xb7, 0x41, 0x91, 0x36, 0x97, 0x8a, 0x88, 0x7d, 0x32, 0x50, 0x5b,
	0x46, 0xac, 0x28, 0xe1, 0xcc, 0x41, 0xde, 0x68, 0x3f, 0xc3, 0x6b, 0x35, 0x0d, 0xdb, 0x5b, 0x0f,
	0xea, 0x3a, 0xe5, 0x46, 0x3f, 0x73, 0xd7, 0x4d, 0x20, 0xa1, 0xc9, 0x80, 0xa3, 0x0e, 0x26, 0xa9,
	0x89, 0x26, 0x7b, 0x27, 0x84, 0x26, 0x42, 0xb5, 0x20, 0x25, 0x3d, 0x09, 0xa9, 0xc4, 0xbf, 0x38,
	0xe8, 0xed, 0x4a, 0x87, 0xc3, 0x4b, 0xc1, 0xd8, 0xc6, 0xeb, 0x2d, 0x07, 0x35, 0x1c, 0xf3, 0x93,
	0x7e, 0xe6, 0x6e, 0x0c, 0x62, 0x88, 0x38, 0xce, 0xe9, 0xe5, 0x81, 0xb6, 0x98, 0x44, 0xb5, 0xa8,
	0x22, 0x2d, 0x2a, 0x89, 0x9d, 0xe7, 0x82, 0x3d, 0xfe, 0xd9, 0x41, 0xb7, 0x46, 0x78, 0xdd, 0x50,
	0x07, 0x5c, 0x60, 0xc3, 0x43, 0x1d, 0x70, 0xa1, 0x7f, 0xde, 0xed, 0x67, 0xee, 0xed, 0x10, 0x8e,
	0xc4, 0x4b, 0xc3, 0xd7, 0x12, 0x2d, 0xd5, 0x18, 0xff, 0xed, 0x20, 0x77, 0x94, 0x9b, 0xe1, 0xd5,
	0xa0, 0x8e, 0x01, 0x7b, 0x41, 0x3d, 0x8f, 0xf4, 0xbf, 0xee, 0x67, 0xee, 0x17, 0xe7, 0xb7, 0xa8,
	0x7e, 0x70, 0x62, 0xdc, 0x88, 0xd8, 0x61, 0x65, 0xe4, 0x80, 0x76, 0x40, 0x12, 0x91, 0xe0, 0x3f,
	0x1c, 0x74, 0xb3, 0x5a, 0xa0, 0xf1, 0x72, 0x30, 0xbe, 0x47, 0x79, 0x2b, 0x75, 0x24, 0xdf, 0xff,
	0xb2, 0x9f, 0xb9, 0x9f, 0xbe, 0xce, 0x5b, 0x77, 0xa5, 0xe9, 0x80, 0x98, 0x26, 0x96, 0x27, 0x11,
	0xc9, 0xeb, 0x2d, 0x3d, 0xc8, 0x09, 0xff, 0xee, 0xa0, 0x9b, 0xd5, 0xaa, 0x38, 0x44, 0xfa, 0x7c,
	0xb5, 0x1e, 0x22, 0x7d, 0x81, 0xce, 0xfa, 0x9f, 0xf7, 0x33, 0xf7, 0xe3, 0x4d, 0xc6, 0x46, 0x93,
	0xb5, 0x9f, 0xee, 0x55, 0x42, 0xf1, 0x8f, 0x83, 0xde, 0x19, 0xa9, 0x7d, 0x38, 0x08, 0x6a, 0x29,
	0xb3, 0xb7, 0x56, 0x53, 0x53, 0xfd, 0xaf, 0xfa, 0x99, 0xfb, 0x99, 0x89, 0xbb, 0x0c, 0x7d, 0xef,
	0x5e, 0x3f, 0x73, 0xc9, 0x13, 0xbe, 0x97, 0xd2, 0xf4, 0x84, 0xec, 0xb4, 0x68, 0x9a, 0xcf, 0xa7,
	0x04, 0xa5, 0x78, 0x72, 0x20, 0x89, 0x84, 0x34, 0x0f, 0x7b, 0xd4, 0xfc, 0xc1, 0x71, 0xfe, 0x0f,
	0x00, 0x00, 0xff, 0xff, 0xda, 0xec, 0x25, 0x8c, 0x25, 0x0f, 0x00, 0x00,
}
