// Code generated by protoc-gen-go.
// source: steammessages_partnerapps.steamclient.proto
// DO NOT EDIT!

package unified

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package unified is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package unified to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CPartnerApps_RequestUploadToken_Request struct {
	Filename         *string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Appid            *uint32 `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPartnerApps_RequestUploadToken_Request) Reset() {
	*m = CPartnerApps_RequestUploadToken_Request{}
}
func (m *CPartnerApps_RequestUploadToken_Request) String() string { return proto.CompactTextString(m) }
func (*CPartnerApps_RequestUploadToken_Request) ProtoMessage()    {}
func (*CPartnerApps_RequestUploadToken_Request) Descriptor() ([]byte, []int) {
	return partnerapps_fileDescriptor0, []int{0}
}

func (m *CPartnerApps_RequestUploadToken_Request) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *CPartnerApps_RequestUploadToken_Request) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

type CPartnerApps_RequestUploadToken_Response struct {
	UploadToken      *uint64 `protobuf:"varint,1,opt,name=upload_token,json=uploadToken" json:"upload_token,omitempty"`
	Location         *string `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
	RoutingId        *uint64 `protobuf:"varint,3,opt,name=routing_id,json=routingId" json:"routing_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPartnerApps_RequestUploadToken_Response) Reset() {
	*m = CPartnerApps_RequestUploadToken_Response{}
}
func (m *CPartnerApps_RequestUploadToken_Response) String() string { return proto.CompactTextString(m) }
func (*CPartnerApps_RequestUploadToken_Response) ProtoMessage()    {}
func (*CPartnerApps_RequestUploadToken_Response) Descriptor() ([]byte, []int) {
	return partnerapps_fileDescriptor0, []int{1}
}

func (m *CPartnerApps_RequestUploadToken_Response) GetUploadToken() uint64 {
	if m != nil && m.UploadToken != nil {
		return *m.UploadToken
	}
	return 0
}

func (m *CPartnerApps_RequestUploadToken_Response) GetLocation() string {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return ""
}

func (m *CPartnerApps_RequestUploadToken_Response) GetRoutingId() uint64 {
	if m != nil && m.RoutingId != nil {
		return *m.RoutingId
	}
	return 0
}

type CPartnerApps_FinishUpload_Request struct {
	UploadToken      *uint64 `protobuf:"varint,1,opt,name=upload_token,json=uploadToken" json:"upload_token,omitempty"`
	RoutingId        *uint64 `protobuf:"varint,2,opt,name=routing_id,json=routingId" json:"routing_id,omitempty"`
	AppId            *uint32 `protobuf:"varint,3,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPartnerApps_FinishUpload_Request) Reset()         { *m = CPartnerApps_FinishUpload_Request{} }
func (m *CPartnerApps_FinishUpload_Request) String() string { return proto.CompactTextString(m) }
func (*CPartnerApps_FinishUpload_Request) ProtoMessage()    {}
func (*CPartnerApps_FinishUpload_Request) Descriptor() ([]byte, []int) {
	return partnerapps_fileDescriptor0, []int{2}
}

func (m *CPartnerApps_FinishUpload_Request) GetUploadToken() uint64 {
	if m != nil && m.UploadToken != nil {
		return *m.UploadToken
	}
	return 0
}

func (m *CPartnerApps_FinishUpload_Request) GetRoutingId() uint64 {
	if m != nil && m.RoutingId != nil {
		return *m.RoutingId
	}
	return 0
}

func (m *CPartnerApps_FinishUpload_Request) GetAppId() uint32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

type CPartnerApps_FinishUploadKVSign_Response struct {
	SignedInstallscript *string `protobuf:"bytes,1,opt,name=signed_installscript,json=signedInstallscript" json:"signed_installscript,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *CPartnerApps_FinishUploadKVSign_Response) Reset() {
	*m = CPartnerApps_FinishUploadKVSign_Response{}
}
func (m *CPartnerApps_FinishUploadKVSign_Response) String() string { return proto.CompactTextString(m) }
func (*CPartnerApps_FinishUploadKVSign_Response) ProtoMessage()    {}
func (*CPartnerApps_FinishUploadKVSign_Response) Descriptor() ([]byte, []int) {
	return partnerapps_fileDescriptor0, []int{3}
}

func (m *CPartnerApps_FinishUploadKVSign_Response) GetSignedInstallscript() string {
	if m != nil && m.SignedInstallscript != nil {
		return *m.SignedInstallscript
	}
	return ""
}

type CPartnerApps_FinishUploadLegacyDRM_Request struct {
	UploadToken      *uint64 `protobuf:"varint,1,opt,name=upload_token,json=uploadToken" json:"upload_token,omitempty"`
	RoutingId        *uint64 `protobuf:"varint,2,opt,name=routing_id,json=routingId" json:"routing_id,omitempty"`
	AppId            *uint32 `protobuf:"varint,3,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	Flags            *uint32 `protobuf:"varint,4,opt,name=flags" json:"flags,omitempty"`
	ToolName         *string `protobuf:"bytes,5,opt,name=tool_name,json=toolName" json:"tool_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) Reset() {
	*m = CPartnerApps_FinishUploadLegacyDRM_Request{}
}
func (m *CPartnerApps_FinishUploadLegacyDRM_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CPartnerApps_FinishUploadLegacyDRM_Request) ProtoMessage() {}
func (*CPartnerApps_FinishUploadLegacyDRM_Request) Descriptor() ([]byte, []int) {
	return partnerapps_fileDescriptor0, []int{4}
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) GetUploadToken() uint64 {
	if m != nil && m.UploadToken != nil {
		return *m.UploadToken
	}
	return 0
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) GetRoutingId() uint64 {
	if m != nil && m.RoutingId != nil {
		return *m.RoutingId
	}
	return 0
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) GetAppId() uint32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Request) GetToolName() string {
	if m != nil && m.ToolName != nil {
		return *m.ToolName
	}
	return ""
}

type CPartnerApps_FinishUploadLegacyDRM_Response struct {
	FileId           *string `protobuf:"bytes,1,opt,name=file_id,json=fileId" json:"file_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Response) Reset() {
	*m = CPartnerApps_FinishUploadLegacyDRM_Response{}
}
func (m *CPartnerApps_FinishUploadLegacyDRM_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CPartnerApps_FinishUploadLegacyDRM_Response) ProtoMessage() {}
func (*CPartnerApps_FinishUploadLegacyDRM_Response) Descriptor() ([]byte, []int) {
	return partnerapps_fileDescriptor0, []int{5}
}

func (m *CPartnerApps_FinishUploadLegacyDRM_Response) GetFileId() string {
	if m != nil && m.FileId != nil {
		return *m.FileId
	}
	return ""
}

type CPartnerApps_FinishUpload_Response struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CPartnerApps_FinishUpload_Response) Reset()         { *m = CPartnerApps_FinishUpload_Response{} }
func (m *CPartnerApps_FinishUpload_Response) String() string { return proto.CompactTextString(m) }
func (*CPartnerApps_FinishUpload_Response) ProtoMessage()    {}
func (*CPartnerApps_FinishUpload_Response) Descriptor() ([]byte, []int) {
	return partnerapps_fileDescriptor0, []int{6}
}

type CPartnerApps_FindDRMUploads_Request struct {
	AppId            *int32 `protobuf:"varint,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CPartnerApps_FindDRMUploads_Request) Reset()         { *m = CPartnerApps_FindDRMUploads_Request{} }
func (m *CPartnerApps_FindDRMUploads_Request) String() string { return proto.CompactTextString(m) }
func (*CPartnerApps_FindDRMUploads_Request) ProtoMessage()    {}
func (*CPartnerApps_FindDRMUploads_Request) Descriptor() ([]byte, []int) {
	return partnerapps_fileDescriptor0, []int{7}
}

func (m *CPartnerApps_FindDRMUploads_Request) GetAppId() int32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

type CPartnerApps_ExistingDRMUpload struct {
	FileId           *string `protobuf:"bytes,1,opt,name=file_id,json=fileId" json:"file_id,omitempty"`
	AppId            *uint32 `protobuf:"varint,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	ActorId          *int32  `protobuf:"varint,3,opt,name=actor_id,json=actorId" json:"actor_id,omitempty"`
	SuppliedName     *string `protobuf:"bytes,5,opt,name=supplied_name,json=suppliedName" json:"supplied_name,omitempty"`
	Flags            *uint32 `protobuf:"varint,6,opt,name=flags" json:"flags,omitempty"`
	ModType          *string `protobuf:"bytes,7,opt,name=mod_type,json=modType" json:"mod_type,omitempty"`
	Timestamp        *uint32 `protobuf:"fixed32,8,opt,name=timestamp" json:"timestamp,omitempty"`
	OrigFileId       *string `protobuf:"bytes,9,opt,name=orig_file_id,json=origFileId" json:"orig_file_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPartnerApps_ExistingDRMUpload) Reset()                    { *m = CPartnerApps_ExistingDRMUpload{} }
func (m *CPartnerApps_ExistingDRMUpload) String() string            { return proto.CompactTextString(m) }
func (*CPartnerApps_ExistingDRMUpload) ProtoMessage()               {}
func (*CPartnerApps_ExistingDRMUpload) Descriptor() ([]byte, []int) { return partnerapps_fileDescriptor0, []int{8} }

func (m *CPartnerApps_ExistingDRMUpload) GetFileId() string {
	if m != nil && m.FileId != nil {
		return *m.FileId
	}
	return ""
}

func (m *CPartnerApps_ExistingDRMUpload) GetAppId() uint32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func (m *CPartnerApps_ExistingDRMUpload) GetActorId() int32 {
	if m != nil && m.ActorId != nil {
		return *m.ActorId
	}
	return 0
}

func (m *CPartnerApps_ExistingDRMUpload) GetSuppliedName() string {
	if m != nil && m.SuppliedName != nil {
		return *m.SuppliedName
	}
	return ""
}

func (m *CPartnerApps_ExistingDRMUpload) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

func (m *CPartnerApps_ExistingDRMUpload) GetModType() string {
	if m != nil && m.ModType != nil {
		return *m.ModType
	}
	return ""
}

func (m *CPartnerApps_ExistingDRMUpload) GetTimestamp() uint32 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *CPartnerApps_ExistingDRMUpload) GetOrigFileId() string {
	if m != nil && m.OrigFileId != nil {
		return *m.OrigFileId
	}
	return ""
}

type CPartnerApps_FindDRMUploads_Response struct {
	Uploads          []*CPartnerApps_ExistingDRMUpload `protobuf:"bytes,1,rep,name=uploads" json:"uploads,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *CPartnerApps_FindDRMUploads_Response) Reset()         { *m = CPartnerApps_FindDRMUploads_Response{} }
func (m *CPartnerApps_FindDRMUploads_Response) String() string { return proto.CompactTextString(m) }
func (*CPartnerApps_FindDRMUploads_Response) ProtoMessage()    {}
func (*CPartnerApps_FindDRMUploads_Response) Descriptor() ([]byte, []int) {
	return partnerapps_fileDescriptor0, []int{9}
}

func (m *CPartnerApps_FindDRMUploads_Response) GetUploads() []*CPartnerApps_ExistingDRMUpload {
	if m != nil {
		return m.Uploads
	}
	return nil
}

type CPartnerApps_Download_Request struct {
	FileId           *string `protobuf:"bytes,1,opt,name=file_id,json=fileId" json:"file_id,omitempty"`
	AppId            *int32  `protobuf:"varint,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPartnerApps_Download_Request) Reset()                    { *m = CPartnerApps_Download_Request{} }
func (m *CPartnerApps_Download_Request) String() string            { return proto.CompactTextString(m) }
func (*CPartnerApps_Download_Request) ProtoMessage()               {}
func (*CPartnerApps_Download_Request) Descriptor() ([]byte, []int) { return partnerapps_fileDescriptor0, []int{10} }

func (m *CPartnerApps_Download_Request) GetFileId() string {
	if m != nil && m.FileId != nil {
		return *m.FileId
	}
	return ""
}

func (m *CPartnerApps_Download_Request) GetAppId() int32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

type CPartnerApps_Download_Response struct {
	DownloadUrl      *string `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl" json:"download_url,omitempty"`
	AppId            *int32  `protobuf:"varint,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CPartnerApps_Download_Response) Reset()                    { *m = CPartnerApps_Download_Response{} }
func (m *CPartnerApps_Download_Response) String() string            { return proto.CompactTextString(m) }
func (*CPartnerApps_Download_Response) ProtoMessage()               {}
func (*CPartnerApps_Download_Response) Descriptor() ([]byte, []int) { return partnerapps_fileDescriptor0, []int{11} }

func (m *CPartnerApps_Download_Response) GetDownloadUrl() string {
	if m != nil && m.DownloadUrl != nil {
		return *m.DownloadUrl
	}
	return ""
}

func (m *CPartnerApps_Download_Response) GetAppId() int32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func init() {
	proto.RegisterType((*CPartnerApps_RequestUploadToken_Request)(nil), "CPartnerApps_RequestUploadToken_Request")
	proto.RegisterType((*CPartnerApps_RequestUploadToken_Response)(nil), "CPartnerApps_RequestUploadToken_Response")
	proto.RegisterType((*CPartnerApps_FinishUpload_Request)(nil), "CPartnerApps_FinishUpload_Request")
	proto.RegisterType((*CPartnerApps_FinishUploadKVSign_Response)(nil), "CPartnerApps_FinishUploadKVSign_Response")
	proto.RegisterType((*CPartnerApps_FinishUploadLegacyDRM_Request)(nil), "CPartnerApps_FinishUploadLegacyDRM_Request")
	proto.RegisterType((*CPartnerApps_FinishUploadLegacyDRM_Response)(nil), "CPartnerApps_FinishUploadLegacyDRM_Response")
	proto.RegisterType((*CPartnerApps_FinishUpload_Response)(nil), "CPartnerApps_FinishUpload_Response")
	proto.RegisterType((*CPartnerApps_FindDRMUploads_Request)(nil), "CPartnerApps_FindDRMUploads_Request")
	proto.RegisterType((*CPartnerApps_ExistingDRMUpload)(nil), "CPartnerApps_ExistingDRMUpload")
	proto.RegisterType((*CPartnerApps_FindDRMUploads_Response)(nil), "CPartnerApps_FindDRMUploads_Response")
	proto.RegisterType((*CPartnerApps_Download_Request)(nil), "CPartnerApps_Download_Request")
	proto.RegisterType((*CPartnerApps_Download_Response)(nil), "CPartnerApps_Download_Response")
}

func init() { proto.RegisterFile("steammessages_partnerapps.steamclient.proto", partnerapps_fileDescriptor0) }

var partnerapps_fileDescriptor0 = []byte{
	// 896 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xc4, 0x96, 0xcf, 0x6f, 0xe3, 0x44,
	0x14, 0xc7, 0xe5, 0x74, 0xd3, 0x24, 0x2f, 0x5d, 0x0e, 0xc3, 0xae, 0x08, 0x81, 0xdd, 0x9d, 0x75,
	0x8b, 0x08, 0xdb, 0xca, 0x40, 0x39, 0x20, 0xa4, 0x3d, 0xc0, 0x66, 0x37, 0xab, 0x55, 0xa1, 0x20,
	0xb7, 0xe5, 0x00, 0x42, 0xd1, 0xd4, 0x99, 0xa4, 0x23, 0x6c, 0x8f, 0xf1, 0x8c, 0xa1, 0x95, 0x38,
	0x00, 0x27, 0x2e, 0xfc, 0x01, 0xdc, 0xb9, 0x81, 0x90, 0x38, 0x54, 0xe2, 0xcf, 0xe3, 0x8d, 0x7f,
	0x24, 0x76, 0x4a, 0x52, 0x73, 0xa8, 0x38, 0xce, 0x9b, 0xe7, 0xf7, 0x3e, 0xf3, 0x7d, 0x6f, 0xde,
	0x18, 0x76, 0x95, 0xe6, 0x2c, 0x08, 0xb8, 0x52, 0x6c, 0xc6, 0xd5, 0x38, 0x62, 0xb1, 0x0e, 0x79,
	0xcc, 0xa2, 0x48, 0x39, 0xe9, 0x8e, 0xe7, 0x0b, 0x1e, 0x6a, 0x27, 0x8a, 0xa5, 0x96, 0xfd, 0xbd,
	0xaa, 0x73, 0x12, 0x8a, 0xa9, 0xe0, 0x93, 0xf1, 0x29, 0x53, 0xfc, 0xaa, 0xb7, 0xfd, 0x25, 0xbc,
	0x39, 0xfc, 0x2c, 0x8b, 0xf7, 0x11, 0xc6, 0x1b, 0xbb, 0xfc, 0x9b, 0x84, 0x2b, 0x7d, 0x12, 0xf9,
	0x92, 0x4d, 0x8e, 0xe5, 0xd7, 0x3c, 0x2c, 0x4c, 0xa4, 0x0f, 0xed, 0xa9, 0xf0, 0x79, 0xc8, 0x02,
	0xde, 0xb3, 0xa8, 0x35, 0xe8, 0xb8, 0xf3, 0x35, 0xb9, 0x03, 0x4d, 0xc4, 0x11, 0x93, 0x5e, 0x03,
	0x37, 0x6e, 0xbb, 0xd9, 0xc2, 0xfe, 0xd9, 0x82, 0xc1, 0xf5, 0xd1, 0x55, 0x24, 0x43, 0xc5, 0xc9,
	0x43, 0xd8, 0x4a, 0x52, 0xfb, 0x58, 0x9b, 0x8d, 0x34, 0xc5, 0x2d, 0xb7, 0x9b, 0x2c, 0x7c, 0x0d,
	0x81, 0x2f, 0x3d, 0xa6, 0x85, 0x0c, 0xd3, 0x44, 0x48, 0x50, 0xac, 0xc9, 0x3d, 0x80, 0x58, 0x26,
	0x5a, 0x84, 0xb3, 0x31, 0x62, 0x6c, 0xa4, 0x1f, 0x77, 0x72, 0xcb, 0x8b, 0x89, 0xfd, 0x3d, 0x3c,
	0xac, 0x90, 0x8c, 0x44, 0x28, 0xd4, 0x59, 0x06, 0x32, 0x3f, 0x61, 0x0d, 0x84, 0x6a, 0x9a, 0xc6,
	0x52, 0x1a, 0x72, 0x17, 0x36, 0xf1, 0xe8, 0x05, 0x41, 0x26, 0x04, 0x66, 0xff, 0x6a, 0x49, 0x87,
	0x72, 0xf6, 0x83, 0xcf, 0x8f, 0xc4, 0xac, 0xa4, 0xc3, 0xbb, 0x70, 0x47, 0xa1, 0x01, 0x4b, 0x26,
	0x42, 0xa5, 0x99, 0xef, 0x2b, 0x2f, 0x16, 0x91, 0xce, 0x25, 0x7f, 0x39, 0xdb, 0x7b, 0x51, 0xde,
	0xb2, 0xff, 0xb6, 0xe0, 0xd1, 0xca, 0xf8, 0x1f, 0xf3, 0x19, 0xf3, 0x2e, 0x9e, 0xba, 0x9f, 0xdc,
	0xf8, 0x31, 0x4d, 0x17, 0x4c, 0x7d, 0x36, 0x53, 0xbd, 0x5b, 0x99, 0x35, 0x5d, 0x90, 0xd7, 0xa0,
	0xa3, 0xa5, 0xf4, 0xc7, 0x69, 0xe3, 0x34, 0xb3, 0xb2, 0x19, 0xc3, 0x21, 0xae, 0xed, 0x11, 0xec,
	0xd6, 0x22, 0xcf, 0xc5, 0x79, 0x05, 0x5a, 0xa6, 0xe7, 0x4c, 0xe6, 0x4c, 0x8f, 0x4d, 0xb3, 0x44,
	0x85, 0x77, 0xc0, 0x5e, 0x57, 0xdf, 0xec, 0x73, 0xfb, 0x31, 0x6c, 0x2f, 0x7b, 0x4d, 0x30, 0x7e,
	0xe6, 0x36, 0x6f, 0xcf, 0xd2, 0xf1, 0x4c, 0x92, 0x66, 0x51, 0xc5, 0x1f, 0x1b, 0x70, 0xbf, 0xf2,
	0xf9, 0xb3, 0x73, 0xa1, 0x8c, 0x22, 0xf3, 0x10, 0x2b, 0xf9, 0x4a, 0x21, 0x1b, 0x65, 0xc5, 0x5e,
	0x85, 0x36, 0xf3, 0xb4, 0x8c, 0x0b, 0x29, 0x9b, 0x6e, 0x2b, 0x5d, 0xe3, 0xd6, 0x36, 0xdc, 0x56,
	0x49, 0x14, 0xf9, 0xe6, 0xf2, 0x96, 0xa4, 0xdb, 0x2a, 0x8c, 0x87, 0xf9, 0xbd, 0xcb, 0x14, 0xdf,
	0x2c, 0x2b, 0x8e, 0x51, 0x03, 0x89, 0xd5, 0xbd, 0x88, 0x78, 0xaf, 0x95, 0x7e, 0xd5, 0xc2, 0xf5,
	0x31, 0x2e, 0xc9, 0xeb, 0x58, 0x0c, 0x81, 0xc3, 0x41, 0xb3, 0x20, 0xea, 0xb5, 0x71, 0xaf, 0xe5,
	0x2e, 0x0c, 0x84, 0xc2, 0x96, 0x8c, 0xc5, 0x6c, 0x5c, 0x9c, 0xa1, 0x93, 0x7e, 0x0c, 0xc6, 0x36,
	0xca, 0x74, 0x66, 0xb0, 0xb3, 0x5e, 0xc1, 0xbc, 0x50, 0x1f, 0x40, 0x2b, 0xeb, 0x27, 0x85, 0x42,
	0x6c, 0x0c, 0xba, 0xfb, 0x0f, 0x9c, 0xf5, 0xd2, 0xb9, 0x85, 0xbf, 0xfd, 0x29, 0xdc, 0xab, 0xb8,
	0x3e, 0x95, 0xdf, 0x85, 0x95, 0x6b, 0x5a, 0x53, 0xe4, 0x79, 0xdd, 0xbe, 0x58, 0x2a, 0x5b, 0x29,
	0xe0, 0x62, 0xf6, 0x4c, 0x0a, 0x63, 0x12, 0xfb, 0x79, 0xd8, 0x6e, 0x61, 0x3b, 0x89, 0xfd, 0x15,
	0xb1, 0xf7, 0xff, 0x00, 0xe8, 0x96, 0x62, 0x93, 0xbf, 0x2c, 0xe8, 0xe5, 0x9c, 0xd9, 0xc5, 0x2e,
	0xcd, 0x3a, 0x32, 0x70, 0x6a, 0xce, 0xda, 0xfe, 0x5b, 0x4e, 0xdd, 0xb9, 0x69, 0x7f, 0xf8, 0xd3,
	0x65, 0xef, 0x71, 0xee, 0x40, 0x33, 0x0d, 0x69, 0x7a, 0xaf, 0xe9, 0x54, 0xc6, 0xb4, 0x32, 0x43,
	0xa8, 0xd1, 0xa9, 0xf0, 0x79, 0x9b, 0x9a, 0x51, 0x82, 0x25, 0x20, 0x7f, 0x5a, 0x70, 0x37, 0x0f,
	0x30, 0x2f, 0xc7, 0xff, 0x06, 0xcc, 0xcf, 0xb9, 0x97, 0x68, 0x76, 0x8a, 0xa0, 0x55, 0x5a, 0x7c,
	0xaf, 0x3c, 0x7c, 0xd4, 0x0c, 0xf0, 0xe5, 0x02, 0x78, 0xf8, 0xec, 0xf9, 0x8d, 0x03, 0x3f, 0x47,
	0xe0, 0xe1, 0x4a, 0x60, 0x2f, 0x51, 0x5a, 0x06, 0xb5, 0xb8, 0x7f, 0xb7, 0x80, 0x5c, 0x1d, 0xfd,
	0xc4, 0x76, 0xae, 0x7d, 0x9a, 0x96, 0x71, 0xd7, 0x3c, 0x20, 0xf6, 0x08, 0x71, 0x9f, 0x0c, 0x65,
	0x10, 0x08, 0x4d, 0x03, 0xae, 0xcf, 0xa4, 0xa1, 0x4d, 0x8b, 0x4d, 0x59, 0xb8, 0xd4, 0x10, 0x6c,
	0xaa, 0x79, 0x6c, 0xcc, 0x39, 0xae, 0x50, 0xd4, 0x93, 0x41, 0xe4, 0x73, 0xcd, 0xc9, 0x6f, 0xa8,
	0x72, 0x39, 0xcf, 0x62, 0xca, 0xed, 0x3a, 0xf5, 0x5f, 0x9b, 0xfe, 0x9e, 0xf3, 0x1f, 0x06, 0xbc,
	0xfd, 0x0e, 0xc2, 0xef, 0x55, 0xe1, 0xff, 0xad, 0x2b, 0x4a, 0xa2, 0xfe, 0xba, 0x84, 0x39, 0xef,
	0x88, 0x5a, 0xba, 0x6e, 0x3b, 0x35, 0x9e, 0x8d, 0xf7, 0x11, 0xea, 0xbd, 0xab, 0x50, 0x2b, 0x2a,
	0x5f, 0x62, 0xfb, 0xc5, 0x82, 0x97, 0xaa, 0x13, 0x92, 0xec, 0x38, 0x35, 0x5e, 0xa0, 0xfe, 0x1b,
	0x4e, 0x9d, 0x29, 0x6b, 0x3b, 0x08, 0xf6, 0xc8, 0x6c, 0x2a, 0x7a, 0x48, 0x03, 0x89, 0xed, 0x19,
	0x73, 0x0f, 0x7f, 0xee, 0x90, 0x41, 0x20, 0x60, 0x3e, 0x51, 0xe9, 0xe9, 0x05, 0x4d, 0x7f, 0xc8,
	0xc8, 0x01, 0xb4, 0x8b, 0xe1, 0x47, 0xee, 0x3b, 0x6b, 0xa7, 0x6c, 0xff, 0x81, 0xb3, 0x7e, 0x68,
	0xf6, 0xf7, 0x31, 0xb9, 0x73, 0xc4, 0xe3, 0x6f, 0x85, 0xc7, 0x73, 0x59, 0x54, 0xaa, 0x0b, 0xe6,
	0xa2, 0x01, 0x0b, 0xf1, 0xf7, 0x33, 0x30, 0x2c, 0x98, 0x3d, 0xff, 0x63, 0x55, 0x4f, 0x36, 0x7e,
	0xb0, 0xac, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x42, 0x12, 0xc6, 0xae, 0xcf, 0x0a, 0x00, 0x00,
}
